angband/angband

src/gen-monster.c
=> Small fix to gen-monster

src/obj-slays.c
Reported by Darin on oook at http://angband.oook.cz/forum/showthread.php?p=101117#post101117
=> Same fix as e7be61e, but for appending brands to randarts.

lib/gamedata/monster.txt
I think game picks up some specific spider, but this is not correct behavior.
=> There is no monster named just "spider", it is monster base

src/mon-list.c
Monster list should always update now.
=> Fix monster list not updating.

lib/gamedata/trap.txt, src/list-trap-flags.h, src/trap.c
- fix bug reported on forum
- document trap.txt
=> Fix & documentation

src/list-options.h, src/ui-input.c
see more in this thread: https://www.reddit.com/r/roguelikes/comments/4z317w/libtcod_games_and_accessibility/d6shc26
=> Add highlight_player option for VI users

configure.ac, readme.txt, src/Makefile.src, src/angband.man, src/buildid.h, src/stats/db.c, src/win/readpng.c
This is my first time submitting a pull request on github in a long time.  I just tried updating the version numbers.
=> Updated version numbers to 4.0.5 and a copyright range to include 2016.

lib/customize/keys-gcu.prf, src/config.h
Some unobtrusive changes necessary to facilitate installation and play on the angband webclient
=> Modifications for server play

src/game-input.h, src/ui-object.c, src/ui-object.h, src/ui-spell.c
Pretty straightforward - stops everyone having to macro them all the time
=> Automatically assign spellbooks tags 1-9 based on sval

src/ui-knowledge.c
a bit of tweaking to the knowledge menus, esp with regard to feature visuals
on a separate branch, so should I think avoid the probably-unwanted detection stuff...
=> Uiknowledge

compiling.txt, faq.txt, lib/help/command.txt
line 254 of command.txt had a typo "may will die", this merge corrects this to "may well die"
=> Fix some typos and spelling

src/Makefile.sdl2, src/main-sdl2.c, src/main.c, src/main.h
This adds main-sdl2.c, an SDL2 port of the game. It also adds
a Makefile to compile it, but no changes to autoconf system.
=> Add SDL2 frontend to Angband

compiling.txt
Added small clarification to MinGW instructions to use the MinGW shell to run the commands
=> Updating compiling.txt - Using MinGW clarification

src/project-mon.c
Restores messages for teleport other, etc.
=> Allow messages for spell effects that do no damage

docs/customize.rst, docs/dungeon.rst, lib/gamedata/object.txt, src/cmd-cave.c, src/ui-display.c
Thanks for maintaining Angband!
Changes:
- minor spelling fixes to `docs/customize.rst` and comments
- command letter highlighting fix in `docs/customize.rst`
- grammatical fix in floor feeling
- Weapon description spelling fix
=> Minor spelling and grammar fixes

src/cave-map.c, src/gen-cave.c
This is an attempt to make some small improvements in the town layout to make it a little more convenient without compromising on flavor.
Also included is a shift to granite for the fill material of the town and a fix for the lighting in town during the day.
=> Lay out town along a crossroads

src/main-cocoa.m, src/ui-term.c
Adds the feature requested in [issue 3618](https://github.com/angband/angband/issues/3618).
=> Add OS X support for double-height tiles

src/main-cocoa.m
See [mrfy's report in the post 4.2.0 thread](http://angband.oook.cz/forum/showpost.php?p=143148&postcount=112).
=> Made sound operational again on OS X.

src/gen-chunk.c, src/init.c, src/obj-init.c, src/player-birth.c, src/player.c, src/player.h, src/project.c, src/ui-options.c, src/ui-visuals.c, src/wiz-debug.c
These changes appear to plug the memory leaks in [issue 4335](https://github.com/angband/angband/issues/4335); the exceptions being leaks D1 and D2.
=> Plug most memory leaks in issue 4335

src/gen-cave.c
=> Fix double door placement in labyrinths

lib/gamedata/ui_entry.txt, lib/gamedata/ui_entry_base.txt, src/Makefile.src, src/init.c, src/ui-equip-cmp.c, src/ui-equip-cmp.h, src/ui-knowledge.c
Tries to address issues #2953, #4035, and #4234.
=> Implement a "resistance grid for home".

src/cmd-cave.c, src/player-util.c, src/player-util.h
=> Changed so digging auto-swap will use a stack if that's best.

src/tests/message/message.c, src/tests/message/suite.mk
=> Added unit tests for message.c.

src/mon-list.c, src/mon-list.h, src/ui-mon-list.c, src/ui-output.c, src/ui-output.h
Hi Nick!
I've made a small modification to the '[' command to sort monsters by the kill experience. If you want to add it to Vanilla let me know. Thank you and great job!
=> Sort Monsters by Exp

src/cmd-cave.c
Nick, I know you want to release 4.2.1 very soon, so this is a small improvement (I think). I don't have any other pull requests pending.
=> The alter command closes doors and open chests.

src/mon-util.c
The implementation makes the player aware of the mimic if the source or destination location is visible to the player.  An alternative would be to never make the player aware of the mimic in monster_swap() and handle whether that happens prior to calling monster_swap().  That would mean changes in effects.c, mon-summon.c, and project-mon.c (and any other places where monster_swap() could be called on a mimic).
=> To resolve issue #4455, added handling of mimics in monster_swap().

src/Makefile.src, src/save-charoutput.c, src/save-charoutput.h, src/savefile.c
This is an initial draft of changes to resolve #4482 .  It generates a CharOutput.txt every time a savefile is written.
=> Save CharOutput.txt for angband.live

src/cmd-obj.c
See the discussion at http://angband.oook.cz/forum/showthread.php?t=10172&page=11 .
=> Drop empty lantern after refueling if no room in the pack

src/cmd-obj.c
Fixes luneya's reported bug from http://angband.oook.cz/forum/showpost.php?p=147604&postcount=47 .
=> Adjust the messaging again in use_aux() for unused single-use items

src/cmd-cave.c, src/player-util.c
Has no effect on the current Vanilla but makes it easier for variants that have bonuses to unarmed digging.
=> Change to accept the possibility that the best digger is NULL

src/effects.c
Resolves part of Sideways' report here, http://angband.oook.cz/forum/showpost.php?p=147649&postcount=142 , about FirstAgeAngband.
=> Use singular in probing result if only one hit point

src/effects.c
Resolves dhouseholder's bug report for FirstAgeAngband here, http://angband.oook.cz/forum/showpost.php?p=147542&postcount=106 .
=> Drop extra "the" from message for JUMP_AND_BITE

src/mon-attack.c
That's to make it consistent with the movement decisions in mon-move.c.  It looks like some of the group AI logic in mon-move.c does still only considers the player's position.  I left that as it is.
=> For spell decisions in mon-attack.c, use the decoy's position if it is present

src/main-sdl2.c
See the report here #4522 .  Adds a user-selectable option for whether to send KC_MOD_KEYPAD to Angband.  By default that is off, so the translation of key and modifiers is always handled upstream (SDL2 or elsewhere) for all keys that translate to text.  Hopefully, upstream will know how to properly handle alternate keyboard layouts.  When that option is on, the prior behavior is restored: KC_MOD_KEYPAD is sent to Angband when the keypad is used but some keyboard layouts are not handled properly for key + modifier combinations that mimic what could come from the keypad.
=> Attempt to resolve issue with SDL2 and some keyboard layouts

src/win/angband_visual_studio_step_by_step.txt
This is partly based on the reports in http://angband.oook.cz/forum/showthread.php?t=8779 .  I don't have access to Windows or Visual Studio so it may be worth it for someone who does to check that the step for enabling sound is right (I cribbed Microsoft's instructions for how to define a preprocessor macro) and to double-check that the project type selection step is clear enough (one of the posters in the thread seemed to run into a problem with that).
=> Update Visual Studio instructions

src/load.c, src/save.c, src/ui-display.c, src/ui-options.c, src/ui-term.c, src/ui-term.h
Nick, feel free to make any change you want.
=> Added topbar (stats and other info). Added a new subwindow type too.

lib/gamedata/old_class.txt
Drop exp modifier.  Use "divine" rather than "light" realm.  Should resolve #4593  .
=> Update old_class.txt to be parseable in Angband 4.2.0+.

lib/gamedata/class.txt, lib/gamedata/hints.txt, lib/gamedata/object.txt, lib/gamedata/player_property.txt, lib/gamedata/store.txt, src/effects.c, src/player-attack.c
Biggest change is swapping the positions of Whirlwind Attack and Leap into Battle. Assorted minor changes.
=> BG Tweaks for 4.2.2

.github/workflows/release.yaml
Also rearrange an overly long line in a comment.
=> Release script:  mark any release that isn't a prerelease as a draft

src/win/vs2019/Angband.vcxproj, src/win/vs2019/Angband.vcxproj.filters
I made the changes manually and haven't tested them by loading the result into Visual Studio.
=> Bring the list of files in the Visual Studio 2019 project files up to date

src/tests/unit-test-data.h
- Align test_timed with the current value for TMD_MAX.
- Add an initialized player_shape structure.
=> Some modernization for unit-test-data.h

src/init.c
See PowerWyrm's post here, http://angband.oook.cz/forum/showpost.php?p=152595&postcount=32 .
=> Include PowerWyrm's fix for kinds of books not picking up the base's kind_flags

src/gen-room.c
Makes them compatible with the existing tunneling code.  Appears to fix the aberrant tunneling around those rooms (the first part of https://github.com/angband/angband/issues/4177 ).  The disadvantages that I see are:
- The available floor space is more diamond-like, especially at the smaller radii and isn't as pleasing to the eye.
- Players are likely familiar with the way tunnels currently behave around circular rooms and could miss that like they miss the rodent skeletons and brown yeeks.
=> Change drawing of outer walls about circular rooms

src/gen-room.c
That's so treasure and monsters added by '8' and '9' can appear to the right or below the location of the '8' or '9'.  In the one pass form, the floors to the right and below the location haven't been laid down yet so '8' or '9' wouldn't add stuff there.
=> Split building template rooms into two passes

src/cmd-cave.c, src/player-util.c
Resolves https://github.com/angband/angband/issues/4746 .
=> Take sticky curses into account when autoswapping to dig

src/main-cocoa.m, src/main-sdl.c, src/main-sdl2.c, src/main-win.c
Resolves Cuboideb's bug report here, http://angband.oook.cz/forum/showpost.php?p=152819&postcount=32 .
=> Take into account sidebar/topbar in double-height tile rendering

src/trap.c
Should resolve https://github.com/angband/angband/issues/4739 .
=> If hit a trap and the trap remains, update player's memory and map

src/main-sdl2.c, src/z-file.c
Resolves https://github.com/angband/angband/issues/4737 .
=> Apply user673679's changes to get main-sdl2.c to work when compiled with MSVC

src/main-win.c, src/main.c, src/snd-sdl.c, src/sound-core.c, src/sound.h, src/ui-init.c, src/ui-knowledge.c, src/ui-knowledge.h
=> Remove last two uses of atexit()

src/ui-command.c, src/ui-display.c, src/ui-map.c, src/ui-target.c, src/ui-term.c, src/ui-term.h
This is useful in the android port. It helps you to concentrate your eyes in only one point. I leave this to your consideration.
Don't forget to validate these changes against the recent modifications to ui-term
Kind regards
=> When sidebar_mode is Top, display the status line at the top too.

src/ui-options.c
That's one way to resolve https://github.com/angband/angband/issues/4719 .
=> Remove broken option to display help from the options screen

src/main-stats.c
The monsters are still killed (that's convenient for preventing any uniques present from respawning on later levels; that routine is also where the monster statistics are collected), but that happens after the objects on the floor have been examined.  Resolves part of https://github.com/angband/angband/issues/3545 , but not the parts related to disaggregating some information and being able to ask about combinations of flags or modifiers.
=> In main-stats.c, get drop statistics by traversing each monster's inventory

src/player-calcs.c
In other words, a confused state makes positive device skill less positive and a negative device skill more negative; being blessed makes a positive device skill more positive and a negative device skill less negative.  For a positive device skill, the amount of change should be the same as before.
Related to https://github.com/angband/angband/issues/4663 , so variants based on Angband can use negative values for the device skill with less code changes.
=> Keep same direction of adjustments to the device skill if the device skill is negative

src/gen-chunk.c, src/generate.c, src/main-gcu.c, src/main-test.c, src/main-x11.c, src/main.c, src/message.c, src/parser.c, src/player-properties.c, src/player-util.c, src/sound-core.c, src/ui-object.c, src/ui-prefs.c, src/z-file.c, src/z-quark.c
Done as part of https://github.com/angband/angband/issues/2141 .
=> Reduce usage of standard string functions (strcmp() and sprintf())

src/cave-map.c
Most notably that it isn't currently disabled.
=> Update comment about what's to be done for hallucination

src/player-attack.c
=> Allow the equipped melee weapon (if it isn't stickily cursed) to be thrown

src/cave-view.c
This is the same as the change made to FirstAgeAngband except for the test for being outside.
=> Change lighting of walls on surface - in daylight, the glow doesn't have to come from a room

src/cave-map.c, src/cave.h, src/cmd-cave.c, src/effects.c, src/project-feat.c
Fixes some issues with clearing rubble in town and not seeing what was beyond the rubble.  For the cases not fixed, suspect that the recent lighting changes introduced problems with how the town is lit.
=> Update visuals after successfully tunneling

src/cmd-obj.c, src/effects.c, src/obj-gear.c, src/obj-gear.h, src/player-calcs.c
Makes it similar to the other functions for body slots and resolves #4962 .
=> Add a struct player argument to slot_type_is()

src/obj-knowledge.c, src/obj-knowledge.h, src/player-birth.c, src/store.c, src/tests/player/calc-inventory.c, src/tests/player/inven-carry-num.c, src/tests/player/inven-wield.c
Resolves https://github.com/angband/angband/issues/4968 (part of https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to object_set_base_known()

src/cmd-obj.c, src/obj-gear.c, src/obj-gear.h, src/obj-knowledge.c, src/project-obj.c, src/store.c, src/ui-player.c
Resolves https://github.com/angband/angband/issues/4971 (part of https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to gear_to_label()

src/ui-spell.c
Thought about requesting this myself recently, so if I'm not the only one, then maybe it's a good idea?
=> Show spell description by default when browsing (#4975)

src/effect-handler-attack.c
Resolves https://github.com/angband/angband/issues/4985 .
=> In TAP_UNLIFE or JUMP_AND_BITE, cancel the target set if the creature dies

src/cmd-obj.c, src/effect-handler-general.c, src/mon-blows.c, src/obj-gear.c, src/obj-gear.h, src/player-attack.c, src/player-util.c, src/project-obj.c, src/store.c, src/tests/player/calc-inventory.c, src/tests/player/inven-carry-num.c, src/tests/player/inven-wield.c
Some of its callers already expect such an argument.  Resolves https://github.com/angband/angband/issues/5000 .
=> Add player argument to gear_object_for_use()

src/obj-slays.c, src/player-attack.c
Resolves https://github.com/angband/angband/issues/4992 .
=> Apply temporary and off-weapon slays and brands to unarmed combat

src/cmd-obj.c, src/obj-gear.c, src/obj-gear.h, src/obj-ignore.c, src/obj-ignore.h, src/player-calcs.c
Resolves https://github.com/angband/angband/issues/5003 .
=> Add player argument to ignore_drop() and combine_pack()

src/obj-power.c
- Allows skipping of the formatting when the log file isn't open.  That'll reduce the overhead when object_power() is used to sort items.
- Avoids the side effect of altering format()'s internal buffer.
=> Convert obj-power.c's logging function to accept variable arguments

src/ui-target.c
Make those pieces a bit more independent of each other.  That's a small step towards resolving https://github.com/angband/angband/issues/3399 , assuming that ui-target.c inherited most of target.c's hideousness.  The current target.c isn't so bad.
=> Split set_target_interactive_aux() into pieces for readability

src/player-util.c, src/score.c, src/score.h, src/ui-score.c
Resolves https://github.com/angband/angband/issues/5014 (part of https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to enter_score() and build_score()

src/obj-knowledge.c
Somehow missed one in earlier changes.
=> Replace use of player global with function arg in update_player_object_knowledge()

src/gen-cave.c
For the former, that resolves https://github.com/angband/angband/issues/5025 , an instance where generating a lair level did not complete in a reasonable amount of time.  For the latter, that's safeguarding against potential similar problems, especially with smaller chunk sizes.
=> Limit the maximum number of attempts at rooms for modified and moria chunks

src/mon-lore.c
Related to https://github.com/angband/angband/issues/4934 .
=> In blow_color() use function argument rather than player global

src/cmd-pickup.c, src/obj-pile.c, src/obj-pile.h, src/player-util.c, src/ui-display.c, src/ui-object.c, src/ui-target.c
…scan_items().  Resolves a portion of https://github.com/angband/angband/issues/5042 (related to https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to scan_floor(), scan_distant_floor(), and

src/effect-handler-general.c, src/game-world.c, src/gen-cave.c, src/mon-make.c, src/mon-util.c, src/mon-util.h, src/player-calcs.c, src/project-mon.c
Resolves https://github.com/angband/angband/issues/5048 (part of https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to update_mon() and update_monsters()

src/main-cocoa.m
https://github.com/backwardsEric/hengband/issues/19 is an example (with Hengband's macOS front end) of the symptoms that are avoided.
=> macOS:  better handle if the font recorded in the preferences is not available

src/cmd-obj.c, src/cmd-pickup.c, src/effect-handler-general.c, src/obj-gear.c, src/obj-pile.c, src/obj-pile.h, src/player-attack.c, src/tests/player/inven-wield.c
Resolves https://github.com/angband/angband/issues/5060 (part of https://github.com/angband/angband/issues/4934 ).
=> Add a player argument to floor_object_for_use()

src/ui-equip-cmp.c
Related to https://github.com/angband/angband/issues/2277 as the implementation up to now only used the keyboard.
=> Allow the mouse to do more in the equippable comparison screen

docs/hacking/how-it-works.rst
This is related to resolving https://github.com/angband/angband/issues/4241 .
=> Docs:  put in first draft of "how it works" for dungeon generation

docs/hacking/modifying.rst
Those are minor regressions introduced by https://github.com/angband/angband/pull/4970 .
=> Documentation:  fix two warnings from sphinx

src/cmd-obj.c
Resolves the first part of PowerWyrm's report here, http://angband.oook.cz/forum/showpost.php?p=156166&postcount=126 .
=> Trigger update after canceled object use

src/ui-prefs.c
Resolves https://github.com/angband/angband/issues/5138 .
=> Include color 0 when dumping colors, even if the color components are zero

src/mon-util.c
Resolves robinjohnson's report here, http://angband.oook.cz/forum/showthread.php?t=10973 .
=> Request redraw for player's gold total after successful theft.

src/ui-store.c
Resolves part of https://github.com/angband/angband/issues/3808 .
=> Generate sounds when entering or leaving stores

docs/playing.rst
Missed that matching playing.rst to commands.txt.
=> Mention "See abilities", "S", command

docs/playing.rst, src/ui-knowledge.c
Intended to help resolve https://github.com/angband/angband/issues/4976 .
=> Knowledge menu for shapes:  add a note about item use and how to change back to normal

src/doc/command.txt
Related to https://github.com/angband/angband/issues/4241 .
=> Update notes about the command system.

lib/customize/pref.prf
Related to https://github.com/angband/angband/issues/3522 .
=> Update comment about swap weapons keymap in pref.prf

src/ui-target.c
Resolves https://github.com/angband/angband/issues/4681 .
=> In open targeting mode, allow running keys to step 10 grids at a time

src/cmd-cave.c, src/effect-handler-general.c, src/game-world.c, src/gen-cave.c, src/mon-attack.c, src/mon-make.c, src/mon-move.c, src/mon-util.c, src/mon-util.h, src/player-calcs.c, src/project-mon.c, src/project-obj.c
That was added in https://github.com/angband/angband/pull/5049 and https://github.com/angband/angband/pull/4945.  That's in response to PowerWyrm's comment here, https://github.com/angband/angband/issues/5048#issuecomment-995629838 .
=> Remove player argument to update_monsters(), update_mon(), and become_aware()

src/tests/list-tests
Fixes #5202 (running CMake from within a Makefile)
=> Fix list-tests script when run from within make

src/main-gcu.c
Resolves https://github.com/angband/angband/issues/5210 .
=> GCU:  also set background color on standard screen

src/player-attack.c
Resolves https://github.com/angband/angband/issues/5215 .
=> Clarify rejection message for the fire command

src/ui-options.c
Resolves https://github.com/angband/angband/issues/5236 .
=> Change messages when a new keymap is entered.

lib/gamedata/trap.txt
Related to https://github.com/angband/angband/issues/4162 .
=> trap.txt:  remove duplicated visibility lines.  

src/mon-init.c
Resolves https://github.com/angband/angband/issues/5304 .
=> Adjust parsing of lore.txt to handle lines added to monster.txt in 4.2.4

docs/hacking/compiling.rst, lib/customize/font-ibm.prf, lib/customize/font.prf, src/Makefile.ibm, src/config.h, src/main-ibm.c, src/main.c, src/savefile.c, src/ui-knowledge.c, src/ui-prefs.c, src/z-file.c, src/z-file.h, src/z-form.c, src/z-textblock.c, src/z-util.c, src/z-util.h
This is for building Angband using DJGPP and the "IBM" display code adapted from version 3.0.6.
* djgpp.txt was incorporated into docs/hacking/compiling.rst
* the ifdefs in savefile.c, ui-prefs.c, and z-textblock.c were moved into z-file.c
* the dos-compat.* files were completely removed
* the commit history was squashed down into a single commit
=> Second pass at DOS port

src/wiz-stats.c
Output seems to have been forgotten, though the data was being collected
=> Output gold stats in wizard stats generator

lib/gamedata/Makefile
Otherwise angband doesn't start
=> Install ui_knowledge.txt

src/generate.c
Resolves https://github.com/angband/angband/issues/5621 .
=> Combine loops in finish_parse_profile()

src/ui-store.c
When selecting an item, then selecting purchase from the context menu, the player may end up buying something.  If so, we want to redraw the store.  If the player didn't buy something, redrawing the store is unecessary, because the inventory hasn't changed, and it may overwrite a message explaining why a purchase attempt was unsuccessful.
=> Only redraw the store if you bought something

src/cmd-cave.c
This makes disarm match the behavior of open.
=> Become aware of mimics on disarming

docs/playing.rst
Resolves https://github.com/angband/angband/issues/5633 .
=> Update documentation about command repetition

docs/command.rst, docs/dungeon.rst
Mention that it is off by default.
=> Match name of the "lose artifacts" option in the docs to what's in game

lib/gamedata/object.txt
That helps the distribution of randart lights.  There's some discussion here, http://angband.oook.cz/forum/showthread.php?t=11479 .
=> Set Wooden Torches to appear on all levels

docs/dungeon.rst
Resolves https://github.com/angband/angband/issues/5642 .
=> Fix reference to repeat feelings command in the documentation

lib/gamedata/monster.txt
That's for consistency with the other hydras and addresses this report, http://angband.oook.cz/forum/showpost.php?p=142953&postcount=183 , by PowerWyrm.
=> All hydras bash rather than open doors

lib/gamedata/monster.txt
Resolves https://github.com/angband/angband/issues/5646 .
=> Change hezrou's innate frequency from 25 (the fallback value) to 3

src/effect-handler-attack.c
Resolves part of https://github.com/angband/angband/issues/5652 .
=> Have HEAL_HP effect work if there's no base or bonus in the amount to heal

src/obj-util.c, src/obj-util.h, src/player-attack.c, src/ui-context.c
Resolves https://github.com/angband/angband/issues/5678 .
=> Only show the "Throw" context menu option for objects that can be thrown

src/gen-cave.c
Affects Modified, Moria, Lair, and Gauntlet levels.
=> Keep generated levels in the bounds set by constants.txt

src/ui-display.c
Resolves PowerDiver's report here http://angband.oook.cz/forum/showthread.php?t=11535 .
=> Display spell points even if encumbrance drops maximum to zero

docs/command.rst, lib/gamedata/ui_entry_renderer.txt, src/list-ui-entry-renderers.h, src/ui-entry-combiner.c, src/ui-entry-combiner.h, src/ui-entry-renderers.c
Resolves https://github.com/angband/angband/issues/5694 (there's also discussion at http://angband.oook.cz/forum/showthread.php?t=11538 ).
=> Character sheet: use '~' for something with resist and vulnerability

src/ui-entry.c
Resolves https://github.com/angband/angband/issues/5696 .
=> Character sheet: show '?' for an item in more circumstances

src/player-calcs.c
That lets elemental resistances stack correctly if the shape provides a vulnerability or a resistance that's not a immunity and the other things affecting that resistance include both a resistance and a vulnerability.  Does not impact the shapes currently in Vanilla.  Pukel-man is the only one providing resistances:  one is an immunity and the other is for an element that does not have vulnerabilities.
=> Apply shape's attributes before applying the vulnerabilities from all sources

src/obj-info.c
The latest report of a problem with this is Bogatyr's here, http://angband.oook.cz/forum/showthread.php?t=11540 .
=> When examining a weapon, fix thrown damage shown with slay or brand in effect

src/ui-score.c
Ported from NarSil's https://github.com/NickMcConnell/NarSil/pull/319 .
=> Score display: change the prompt displayed if full scrolling is not allowed

src/ui-input.c
Ported from NarSil's https://github.com/NickMcConnell/NarSil/pull/321 .
=> textui_get_rep_dir(): honor allow_5 when processing a queued direction

docs/customize.rst
That's a response to smbhax's post here, http://angband.oook.cz/forum/showpost.php?p=161295&postcount=6 .
=> Mention the toggle ignore command in the ignoring section

src/borg/borg9.c
needed to add rolling hp.  Not sure why this wasn't an issue before.  I didn't look to see if the base code changed.  I might want to revert to using do_cmd_accept_character() but I am not sure that will get me the right stuff.  IIRC I had trouble with it before.
=> bad hp on resurection

src/ui-display.c
Resolves https://github.com/angband/angband/issues/5743
=> Separate repeat/rest info on status line from what follows

src/borg/borg1.c, src/borg/borg1.h, src/borg/borg2.c, src/borg/borg2.h, src/borg/borg3.c, src/borg/borg3.h, src/borg/borg4.c, src/borg/borg4.h, src/borg/borg5.c, src/borg/borg5.h, src/borg/borg6.c, src/borg/borg6.h, src/borg/borg7.c, src/borg/borg7.h, src/borg/borg8.c, src/borg/borg8.h, src/borg/borg9.c, src/borg/borg9.h
This should handle all the recent borg fixes done while I was traveling in one go
=> Latest pull requests from the borg

src/borg/borg6.c
including avoiding flowing to dig when you can't because you are hungry
=> some borg digging fixes 

src/borg/borg5.c, src/borg/borg6.c
this should link to issue https://github.com/angband/angband/issues/5740 
changes 
1) trigger the "vault on level" better
2) make sure the code to dig works
3) a couple of resting issues druids (the ones I tested the two above with) had.
=> improve digging out vaults

src/obj-init.c
=> For instant artifact kinds, inherit the flags and element info of the tval

src/borg/borg4.c, src/borg/borg6.c, src/borg/borg7.c, src/borg/borg8.c
add code to allow more random artifact activations.  This is the set that does attacks. There are still several that aren't used by the borg.
=> attack activations

src/mon-move.c
Resolves https://github.com/angband/angband/issues/5765 .
=> Never allow uniques to multiply

src/borg/borg3.c, src/borg/borg4.c, src/borg/borg6.c
last major activations change and spell RESISTANCE no longer does poison
=> Borg activ4

src/ui-mon-lore.c
Resolves https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781748 .
=> For spoilers, use full set of flags rather than those currently in lore

src/Makefile.ibm
Resolves https://github.com/angband/angband/issues/5771 .
=> Have DOS port shorten the name for ui_knowledge.txt

src/borg/borg1.c, src/borg/borg1.h, src/borg/borg2.c, src/borg/borg2.h, src/borg/borg3.c, src/borg/borg3.h, src/borg/borg4.c, src/borg/borg4.h, src/borg/borg5.c, src/borg/borg5.h, src/borg/borg6.c, src/borg/borg6.h, src/borg/borg7.c, src/borg/borg7.h, src/borg/borg8.c, src/borg/borg8.h, src/borg/borg9.c, src/borg/borg9.h
Try to be more aligned with the formatting of the base Angband code. This should have no impact on functionality.  
The code also needs to be broken into functional supportable units instead of clumped into borg1, 2, 3 etc.  That step is going to take a lot of work.
=> standard formatting of the code. 

src/main-sdl2.c
Allows for better diagnostics if run from a desktop file or other situations where the user can not see what is written to standard error.
=> SDL2: display quit message to the screen

src/main-sdl2.c
Also provide clearer diagnostics if there is trouble with lib/fonts.  See http://angband.oook.cz/forum/showpost.php?p=161635&postcount=14 and the posts after it for some discussion.
=> SDL2: more robustly handle unusable configured font

src/cmd-cave.c
Hey, one of my first changes in the base code rather than purely borg stuff :)
Not sure if you want this change or if I am messing something up (like if other code is parsing the dig message and I missed it.
=> add a clause to digging to make it obvious that you are use the digger

src/effect-handler-general.c
See discussion here, https://forum.angband.live/forum/showthread.php?t=11614 .  In object detection, also scan full pile for noticing.
=> Object sensing: scan full pile for noticing; do not notice known ignored items

src/borg/borg-fight-attack.c, src/borg/borg-fight-defend.c, src/borg/borg-fight-perm.c, src/borg/borg-flow-dark.c, src/borg/borg-flow-kill.c, src/borg/borg-flow-misc.c, src/borg/borg-flow-stairs.c, src/borg/borg-flow-take.c, src/borg/borg-flow.c, src/borg/borg-flow.h, src/borg/borg-inventory.c, src/borg/borg-magic.c, src/borg/borg-magic.h, src/borg/borg-think-dungeon.c, src/borg/borg-think.c, src/borg/borg-trait-swap.c, src/borg/borg-trait.c
fixes including heroism, high level borgs not picking things up, spelling issues, speed calculations, digging and other things
=> borg fixes including:

src/main-nds.c
Resolves https://github.com/angband/angband/issues/5810 .
=> Add solid/hybrid wall support for Nintendo front end

src/obj-knowledge.c
Also forget if the player's knowledge no longer covers the trait.  Resolves part of https://github.com/NickMcConnell/FAangband/issues/398 .
=> player_know_object(): forget traits no longer present

src/sdl2/pui-misc.c
Introduced by https://github.com/angband/angband/pull/5813 .
=> SDL2: fix whitespace

m4/buildsys.m4, mk/buildsys.mk.in, mk/extra.mk.in
The new option to configure, --disable-silent-rules, may be useful for diagnosing problems in the build process.
=> Merge in buildsys's upstream changes as of 2023/09/10

src/main-sdl2.c
Avoids lag reported by Ituirth here, https://forum.angband.live/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248123#post248123 .
=> SDL2: compress consecutive mouse motion events

src/cave-square.c, src/cave.h, src/generate.c
Restrict those squares to ones that are passable (old behavior) and not damaging (new).
=> Add predicate for squares that could be used as feeling squares

src/main-sdl2.c
Resolves tangar's report here, https://forum.angband.live/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248154#post248154 , of being able to resize the window till the menu bar does not fit.
=> SDL2: be smarter about the minimum window size

src/obj-randart.c
Resolves https://github.com/angband/angband/issues/5854 .
=> Randarts: have artifact_prep() reset curses to those for the selected kind

src/mon-util.c
Resolves https://github.com/angband/angband/issues/5852 .
=> Include number in stack for monster's reaction to player theft

src/main-sdl2.c, src/sdl2/pui-dlg.c, src/sdl2/pui-dlg.h
Addresses Ituirth's report here, https://angband.live/forums/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248258#post248258 .  That's a regression introduced by d8518ad36119589cd966e18615881fcec0be1300 .
=> SDL2: restore popping down menu for mouse press outside the menu

src/player-path.c
=> Pathfinding: square_isnotknown() is not the same as !square_isknown()

src/ui-init.c
Resolves https://github.com/angband/angband/issues/5915 .
=> Reinitialize the knowledge menus when playing again

src/ui-target.c
Suggested by Gwarl here, https://angband.live/forums/forum/angband/development/248274-so-i-added-auto-explore-to-angband?p=248292#post248292 .  '>' and '<' will move the selection to the nearest (by path) known stairs of the appropriate type.  'x' moves the selection to the nearest unexplored area (known passable square with unknown neighbors or known closed door/impassable rubble with unknown neighbors).
=> Add analogues of the exploring commands to the targeting interface

lib/gamedata/object.txt
Fixing Main Gauche plural to be in line with proper french
=> Issue #5651 fix

src/borg/borg-flow-kill.c, src/borg/borg-home-notice.c, src/borg/borg-io.c, src/borg/borg-io.h, src/borg/borg-item-wear.c, src/borg/borg-log.c, src/borg/borg-store-buy.c, src/borg/borg-store-sell.c, src/borg/borg-store.c, src/borg/borg-store.h
changes 
1) get rid of extra borg_massage_special_chars parameter
2) turn home into a constant, tested at startup
3) make shop wares a dynamic array
=> borg: get rid of some magic numbers like home=7

src/effect-handler-attack.c
Reported by PowerWyrm here, https://angband.live/forums/forum/angband/vanilla/10689-angband-4-2-5?p=248545#post248545 .
=> Fix damage notification for TAP_UNLIFE

src/borg/borg-fight-defend.c, src/borg/borg-store-buy.c
renamed and commented a bit hopefully making it a bit more supportable.  And cleaning up random spelling errors as I go.
=> borg: clean up genocide code a bit

src/borg/borg-item-decurse.c
if wrong on decursing swap items
=> Borg decurse swap

src/ui-signals.c
That is to help diagnose issues like https://github.com/angband/angband/issues/5952 .
=> For exits due to a signal, use non-zero exit code and indicate signal number

src/borg/borg-init.c, src/borg/borg-init.h, src/borg/borg-io.c, src/borg/borg-io.h, src/borg/borg.c
This should fix some messaging done when starting the borg.
=> borg: some initialization changes

src/borg/borg-formulas-calc.c, src/borg/borg-formulas.c, src/borg/borg-reincarnate.c, src/borg/borg.txt
some renames to make debugging in msvc easier and make sure I free things correctly when reloading borg.txt
=> borg: a couple of typos in borg.txt and

src/borg/borg-update.c, src/borg/borg.txt
and a crash when resizing windows while the borg is running (don't do that!  not sure I got all the places where that might happen)
=> borg: a formula (borg.txt) fix 

src/borg/borg-flow-misc.c, src/borg/borg-think-dungeon-util.c
Also remove redundant test when extending the list of sites to excavate.
=> Borg: fix vault excavation logic

src/cave-view.c
Reverts change made in 2019, https://github.com/angband/angband/commit/ab3fad0966e256ae25ac43f0c404f6c250af83f2 .  Resolves agoodman's report here, https://angband.live/forums/forum/angband/vanilla/248821-spear-of-light#post248821 .
=> Allow glowing terrain that's not in a room or on the surface to light a wall

src/borg/borg-flow.c
avoid queueing up a normal flow over a monster if afraid
=> borg: another fix for trying to attack when afraid

src/borg/borg-flow-take.c, src/borg/borg-flow-take.h, src/borg/borg-flow.c, src/borg/borg-init.c, src/borg/borg-inventory.c, src/borg/borg-io.c, src/borg/borg-io.h, src/borg/borg-item.c, src/borg/borg-junk.c, src/borg/borg-store-sell.c, src/borg/borg-think-dungeon.c, src/borg/borg.c, src/borg/borg.h, src/borg/borg.txt
adding a configuration setting to help debug issues.  Hopefully my event handling code is right.
Tossed in a minor fix that caused bells (junking while recalling) and one that didn't allow selling of unID junk you have two of.
=> borg: add config borg_stop_on_bell and fix an selling issue

src/borg/borg-caution.c, src/borg/borg-flow-dark.c, src/borg/borg-flow-kill.c, src/borg/borg-flow-misc.c, src/borg/borg-flow-misc.h, src/borg/borg-flow-stairs.c, src/borg/borg-flow-take.c, src/borg/borg-junk.c, src/borg/borg-junk.h, src/borg/borg-think-dungeon.c
optimize some of the flow code (hopefully I didn't break anything) and fix twitchiness which, due to an off by one error, would never flow to the upper right.
=> borg: optimize some flow code

src/borg/borg-fight-attack.c, src/borg/borg-flow-take.c, src/borg/borg-formulas.c, src/borg/borg-io.c, src/borg/borg-io.h, src/borg/borg-item-wear.c, src/borg/borg-junk.c, src/borg/borg-magic-play.c, src/borg/borg-store-buy.c, src/borg/borg-think-dungeon.c, src/borg/borg-trait-swap.c, src/borg/borg-util.c, src/borg/borg-util.h, src/borg/borg.c
getting more reports of "unexpected request for direction" which is an edit I added so that the borg would halt when asked for a direction when it wasn't expecting one since this indicates that the key queue is messed up.
=> borg: more debug info for when it halts on asking for direction

src/borg/borg-junk.c, src/borg/borg-junk.h, src/borg/borg-think-dungeon.c, src/borg/borg.c
minor changes mostly in code location and names and messages the borg produces.
=> Borg junk renames

src/ui-input.c
Resolves agoodman's report here, https://angband.live/forums/forum/angband/vanilla/249005-message-ending-being-cut-off .  Avoids having to apply this workaround, https://github.com/angband/angband/pull/5991 , for the borg.
=> Avoid truncation of "-more-" prompt

src/borg/borg-flow-kill.c, src/borg/borg-flow-kill.h, src/borg/borg-messages.c, src/borg/borg-update.c, src/borg/borg.c
also got rid of some old or debug code
=> borg: add a special case for hallucinating and afraid to avoid getting stuck

src/ui-input.c
Avoids the need to patch the borg with https://github.com/angband/angband/pull/5997 .
=> Guarantee "-more-" has a space in front of it

src/effect-handler-general.c
Proposed by agoodman here, https://angband.live/forums/forum/angband/development/249089-remove-curse#post249089 .
=> Tighten check for removable curse

src/borg/borg-fight-attack.c, src/borg/borg-formulas.c, src/borg/borg-home-notice.c, src/borg/borg-item-use.c, src/borg/borg-item-wear.c, src/borg/borg-item-wear.h, src/borg/borg-item.c, src/borg/borg-item.h, src/borg/borg-junk.c, src/borg/borg-messages.c, src/borg/borg-power.c, src/borg/borg-store-buy.c, src/borg/borg-store-sell.c, src/borg/borg-store.c, src/borg/borg-store.h, src/borg/borg-think-store.c, src/borg/borg-think.c, src/borg/borg-trait-swap.c, src/borg/borg-trait.c, src/borg/borg-trait.h, src/borg/borg-update.c, src/borg/borg.c
hopefully this will speed up a much complained about and buggy "put on best equipment" process.
=> borg: change how 'best' items are selected

src/borg/borg-item-wear.c
=> borg: take care of more than one when taking from home during best 

src/obj-pile.c
Addresses issue raised by PowerWyrm here, https://angband.live/forums/forum/angband/vanilla/10689-angband-4-2-5/page4#post249292
=> Do not allow mimicked objects to stack

src/borg/borg-io.c, src/borg/borg-item-wear.c, src/borg/borg-junk.c, src/borg/borg-log.c, src/borg/borg-think-dungeon-util.c, src/borg/borg-update.c, src/borg/borg.c
pushing up @backwardsEric's changes
=> Borg format warnings

src/borg/borg-log.c, src/borg/borg.c
a fix for https://github.com/angband/angband/issues/6038
=> borg: fix quantities when dumping the log

src/main-sdl2.c
Resolves https://github.com/angband/angband/issues/6047 .
=> SDL2: direct mouse presses to menus then to starting moving/sizing

src/main-sdl2.c
Resolves https://github.com/angband/angband/issues/6052 , a regression introduced by https://github.com/angband/angband/pull/6049 .
=> SDL2: improve responsiveness when moving/resizing subwindows

src/ui-knowledge.c
Related to https://github.com/angband/angband/issues/6061 .
=> Ego knowledge menu:  avoid another trigger for the address sanitizer

src/obj-info.c
Resolves https://github.com/angband/angband/issues/6065 .
=> Generate recall for everburning lights

src/effect-handler-general.c
Reported by RegalStar here, https://angband.live/forums/forum/angband/vanilla/249364-what-is-the-point-of-necromancer-s-command-spell-having-a-chance-of-being-resisted#post249364
=> Necromancer's command: deduct mana and take a turn if resisted

src/borg/borg-danger.c, src/borg/borg-fight-attack.c, src/borg/borg-formulas.c, src/borg/borg-item-wear.c, src/borg/borg-messages.c, src/borg/borg-power.c, src/borg/borg-prepared.c, src/borg/borg-store-buy.c, src/borg/borg-think-dungeon-util.c, src/borg/borg-trait.c, src/borg/borg-trait.h, src/borg/borg.c, src/borg/borg.txt
moved stat use into traits as much as possible.
=> borg: fix up stat use

src/borg/borg-prepared.c, src/borg/borg-update.c
I also got rid of the code that made clevel 50 and play_risky override the unqiues check.
=> borg: fix check for 3 living uniques

src/borg/borg-junk.c
messed up when changing junk code from crushing to dropping.
=> borg: messed up dropping junk

src/borg/borg-danger.c, src/borg/borg-fight-attack.c, src/borg/borg-flow-kill.c
to let money scum work better and remove some money scum restrictions
=> borg: change how the danger of stun is calculated

src/borg/borg-fight-defend.c, src/borg/borg-flow-take.c
don't hide in summon corridor
when money scumming in town pick up gold even if we have lots
=> borg: when in town,

src/borg/borg-messages.c
When looking into the aim issue I noticed a lot of assumed misses and figured out that death messages were being ignored.
=> borg: there are more death messages I missed

src/main-sdl2.c
Resolves https://github.com/angband/angband/issues/6058 .
=> SDL2: remove menu entry to close window 0

CMakeLists.txt, lib/user/archive/.gitignore, src/main-win.c
Also ensures lib/user/archive is set up for self-contained installs via CMake.
=> Ensure archive directory presence if running Windows front end in place

src/borg/borg-init.c, src/borg/borg-log.c, src/borg/borg-think.c, src/borg/borg-update.c, src/borg/borg.c, src/borg/borg.h, src/borg/borg.txt
the dumps the borg makes will be put in the archive directory
some flags are now configurable in game
expose borg_autosave which allows a backup of the savefile to the archive directory.  now in borg.txt instead of requiring a code change.
=> borg: move some borg files to the archive directory

src/sdl2/pui-ctrl.c
Resolves https://github.com/angband/angband/issues/6134 .
=> SDL2: change appearance of menu toggles

src/borg/borg-caution.c, src/borg/borg-prepared.c, src/borg/borg-prepared.h, src/borg/borg-think-dungeon-util.c, src/borg/borg-think-dungeon.c
1) try to make sure if the borg kills Sauron before being ready for morgoth he doesn't spend time on lvl 100
2) try not to make the borg walk down to lvl 100
3) prevent a couple of places the borg was fleeing levels when hunting uniques
=> borg: try to handle end game hunting of uniques a little better

src/borg/borg-caution.c, src/borg/borg-think-dungeon-util.c
and add a message when there is no choice
=> borg: try not to hop up and down the same set of stairs when restocking

src/ui-object.c
Resolves https://github.com/angband/angband/issues/6164 .
=> Plug memory leak and account for awareness in display_object_kind_recall()

src/ui-mon-list.c
Resolves https://github.com/angband/angband/issues/6166 .
=> Apply purple_uniques to monster list glyphs

src/borg/borg-flow.c, src/borg/borg-item-wear.c, src/borg/borg-store.c, src/borg/borg-store.h, src/borg/borg-think-dungeon-util.c, src/borg/borg-think-store.c
added checks in the middle for full inventory or home for "best" processing
also added a little code for staying on good levels longer and leaving bad levels earlier.
=> borg: intermediate checks in best for full inv or home

docs/attack.rst, docs/birth.rst, docs/dungeon.rst, docs/index.rst, docs/playing.rst
Resolves https://github.com/angband/angband/issues/6176 though there's many more index entries that could be added.
=> docs: remove the "Module Index" link; start populating the index

src/game-world.c
Resolves https://github.com/NickMcConnell/FAangband/issues/437 .
=> Update player's cave properly if trap timeout expires while in view

src/main-sdl2.c
As part of porting Angband to the Nintendo Wii, I need to add support for the controller. This branch adds reading input events from the GameController SDL2 API.
While this is already functional, I would appreciate some input on how to improve further (can be in a separate MR, if you deem that this is good enough to go):
- I'd like to make it so that the START button opens the menu, but I didn't find a way to do it. Is it possible to open the menu without using a mouse?
- Arrow buttons now move the character by one cell only. I'd like to make it so that if the button stays pressed, the character continues to move on that direction. Any hints on how to achieve this?
=> Add GameController support to SDL2 backend

src/ui-object.c
To do so click the row above where an item menu is displayed in the main window (for instance the row saying "Select Item: (Equip ...)").  The location clicked must not be to the left of column with the selection letters or numbers for the menu.  Clicking in such a location dismisses the list regardless of the row clicked.  A context menu will appear which allows selection of the new source of the list or to back out from displaying the item menu.
=> Allow switching between equipment/inventory/quiver/floor by mouse

lib/gamedata/activation.txt, src/cmd-obj.c, src/obj-info.c, src/obj-init.c, src/obj-randart.c, src/object.h, src/tests/parse/objact.c
Resolves https://github.com/angband/angband/issues/6187 .
=> Configure activation difficulty for randarts or egos from activation.txt

src/borg/borg-store-buy.c
=> Borg buy theft check

src/obj-util.c
=> Make level in get_use_device_chance() consistent with changes elsewhere

src/tests/parse/parse.c
Test handling of multibyte characters and additional characters that are not ':'.
=> Add to unit test cases for data file parsing of single characters

docs/hacking/modifying.rst
Old link http://angbandplus.github.io/AngbandPlus/ 404s.
=> Docs: AngbandPlus link fix

docs/customize.rst
Resolves https://github.com/angband/angband/issues/6243 .  Also describe how that window<->subwindow relationship is managed.
=> Fix missing word in the documentation about configuring SDL2

src/main-gcu.c
This pr adds help doc for these options `-left` `-right` `-top` `-bottom` `-spacer` incase of gcu system
=> add help doc for manual window setup for gcu

docs/customize.rst, docs/hacking/borg.rst
From: https://github.com/angband/angband/issues/6253#issuecomment-2989128387
Also started `Customizing` section with `TODO`.
=> Add Logging section to Borg documentation

docs/conf.py
Please let me know if there's a preferred format or if you'd like this updated dynamically going forward.
=> Update copyright year in documentation footer to 2025

src/borg/borg-cave.h, src/borg/borg-flow-glyph.c, src/borg/borg-flow-take.c, src/borg/borg-flow.h, src/borg/borg-home-power.c, src/borg/borg-store-buy.c, src/borg/borg-store.c, src/borg/borg-think-dungeon-util.c, src/borg/borg-think-dungeon.c, src/borg/borg-think-store.c, src/borg/borg-think.c, src/borg/borg-trait-swap.c, src/borg/borg-trait.c, src/borg/borg-update.h
Follow up from: https://github.com/angband/angband/pull/6271 - Something in my search there was wrong. I didn't get all remaining legitimate borg code comments.
=> Remove borg 'Hack --' comments pt 3

docs/hacking/how-it-works.rst
File referenced: https://github.com/angband/angband/blob/master/src/doc/monster-ai.md
=> Dev How It Works documentation: Monster AI

docs/hacking/how-it-works.rst
Referenced: https://github.com/angband/angband/blob/master/src/doc/event.txt
=> Dev How It Works documentation: Events

src/borg/borg-danger.c, src/borg/borg-fight-attack.c, src/borg/borg-fight-defend.c, src/borg/borg-flow-dark.c, src/borg/borg-flow-glyph.c, src/borg/borg-flow-glyph.h, src/borg/borg-flow-kill.c, src/borg/borg-flow-kill.h, src/borg/borg-flow-misc.c, src/borg/borg-flow-misc.h, src/borg/borg-flow-take.c, src/borg/borg-formulas.c, src/borg/borg-io.c, src/borg/borg-junk.c, src/borg/borg-think-dungeon-util.c, src/borg/borg-think-dungeon-util.h, src/borg/borg-think-dungeon.c, src/borg/borg-update.c, src/borg/borg.c
update of my compiler is giving me a bunch of warnings.  These changes shouldn't effect functionality
=> borg: get rid of some unused parameter warnings

src/borg/borg-flow-dark.c, src/borg/borg-flow-misc.c, src/borg/borg-flow-misc.h, src/borg/borg-flow-stairs.c, src/borg/borg-flow-take.c
extract some of the leash processing and turn it off if the borg gets twitchy.  When the borg can't think of what to do and he is on a leash it means he can't get to the exit.  He needs to explore to find it so I made it so when "distance/cost of getting to the stairs" is 255 (which was coded in as "more distance than the map allows"), it goes "off leash" to find some stairs.
=> borg: change the leash a bit

src/ui-game.c
Resolves https://github.com/angband/angband/issues/6289 .
=> Skip processing keymap's remainder if command lookup/prereq/confirmation fails

src/borg/borg-escape.c, src/borg/borg-fight-attack.c, src/borg/borg-fight-defend.c, src/borg/borg-flow.c, src/borg/borg-projection.c, src/borg/borg-projection.h, src/borg/borg-think-dungeon-util.c
the way the targeting code functions is not working with the curse spell.  Disabling it till a solution is found.
=> borg: fix curse spell

src/store.c
Resolves https://github.com/angband/angband/issues/6362 .  In home_carry(), absorb the known version of the object as that may be a source for the misaligned numbers.
=> Work around mismatched numbers in do_cmd_retrieve()

src/option.c, src/option.h, src/ui-options.c
Scroll those shown as necessary.  Resolves https://github.com/angband/angband/issues/6367 .
=> Remove limit on number of options shown per category
