fix/readme-compile-url

The url to the compilation instructions in the Readme.txt file is broken. I believe it's been moved to http://trac.rephial.org/wiki/Compiling.

Fixed broken link to compilation instructions

---

lib/xtra/sound/sound.cfg

For some reason the sound config file parsing doesn't like multiple spaces, or trailing spaces on lines.
Without this, the console where the game is run gets lots of "src/angband: Couldn't read from RWops: Is a directory" warning messages

Cherry-picked fix to sound config file, removing double and trailing spaces

---

src/ui-object.c

Fix the corner cases of exactly stack_size missles in the quiver.
Can't use quiver_cnt % stack_size, as that will show 0 rather than 40, so I just subtracted the rest of the quiver from the count for the last slot.
Likewise the number of slots isn't simply 1 +, as that will give 2 slots if there are exactly 40. It has to be a formal rounding up.

Make sure quiver slots are rounded correctly, and report the correct number of missiles

---

src/gen-cave.c
src/store.c

Don't use STORE_HOME to check for last store. In gen-cave.c, room with calculation has a problem with internal int cast. Change '2' to '2.0' there to avoid round-off bug when calculating room size.

Fixes to avoid potential problems when adding new stores

---

src/obj-power.c

Restored 3.5 behavior of multiplying power by shot count when evaluating extra shots ability on randarts.
This should make for more reasonable randart launchers.

Another randart fix

---

src/player-calcs.c

Previously characters fighting unarmed would always get exactly
one attack. With this patch, multiple blows are calculated as
they would be for the lightest weapon. This means unarmed combat
is up to six (6) times better than before!
(Bron points out on Oook that the real reason to do this is that
it makes it easier to understand the STR/DEX interplay for
multiple attacks during character creation.)
This is a modified version of bron's suggested patch.

Improve unarmed combat blows.

---

src/player-attack.c

Fixed `py_attack_hit_chance()`.  It was adding the player state to_h bonus rather than the weapon to_h bonus when calculating the chance of hitting.

py_attack_hit_chance() not using weapon to_h

---

src/main.c
src/main.h
src/ui-birth.c
src/ui-birth.h

Useful for programs like dgamelaunch to play with others, standardizing highscores and configuration files.
Useage: Add -f to the commandline arguments. This enforces *nix username
or username invoked by -u.

Small hack to for server play, enforces usernames with -f

---

src/main-sdl.c

When launching with `-g -msdl -u${USER}`, angband would fail to load tiles due to incorrect tileset paths.  The game would produce these warnings:
> angband: Can't find file /home/kjfletch/usr/share/angband/tiles/8x8.png - graphics mode 'Original Tiles' will be disabled.
> angband: Can't find file /home/kjfletch/usr/share/angband/tiles/16x16.png - graphics mode 'Adam Bolt's tiles' will be disabled.
> angband: Can't find file /home/kjfletch/usr/share/angband/tiles/32x32.png - graphics mode 'David Gervais' tiles' will be disabled.
> angband: Can't find file /home/kjfletch/usr/share/angband/tiles/8x16.png - graphics mode 'Nomad's tiles' will be disabled.
> angband: Can't find file /home/kjfletch/usr/share/angband/tiles/64x64.png - graphics mode 'Shockbolt's tiles' will be disabled.
By …

Fixed graphical tile loading in SDL.

---

autogen.sh
configure.ac

This patch includes the m4 directory through configure.ac rather than aclocal arguments in autogen.sh. It should be functionally equivalent, but this will make the build system easier to use on platforms that don't use autogen.sh to create the files, as is the case for the FreeBSD port.

Add m4 directory to configure.ac.

---

src/z-file.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.

Avoiding conditional directives that break statements.

---

src/main-cocoa.m

Not exactly the recommended way of doing this - this patch just starts drawing everything at the highest dpi available on any monitor attached to the system, but I can't see a way of easily mapping back a drawing command to a window to be able to easily derive its dpi.  (On a system with multiple scale factors on different monitors this just means slightly slower drawing on all monitors, and slightly higher memory allocation for the buffers even on standard-dpi monitors - no big deal!)
This improves both ASCII rendering and graphical tile detail, which is great.

Add HiDPI/Retina support to the OS X port

---

src/cave.c
src/cave.h
src/game-input.h
src/game-world.h
src/generate.c
src/generate.h
src/init.h
src/mon-attack.h
src/mon-summon.h
src/obj-ignore.h
src/project.h
src/savefile.h
src/trap.h
src/ui-birth.c
src/ui-birth.h
src/ui-game.h
src/ui-input.h
src/ui-output.c
src/ui-output.h
src/ui-prefs.h
src/ui-signals.h
src/z-util.h

This is a low-priority change that fixes a problem with duplicate symbols while linking. Xcode seems to pass flags (or has other configurations) that cause linker failures, whereas building with `make` from `Makefile.osx` does not have these issues. It is also a bit of cleanup for code correctness.
These changes shouldn't break building on other systems, but this has only been tested on OS X versions of `clang` and `ld` and such. There should also be no effect when running the actual built product.

Extern globals to prevent link issues in some configurations.

---

src/init.c
src/main-cocoa.m
src/z-file.c

This fixes the documents path issue on OS X. Note that this change will create and look for files in their correct locations. Users transitioning to this build will need to manually move their files from the incorrect location to the correct location: `~/Documents/Angbandsave/` to `~/Documents/Angband/save/`.
These changes make path building a bit more robust by handling the existence or lack thereof of a trailing path separator on the paths that are passed into `init_file_paths()`. This has not been tested on other platforms, but it has been tested with various combinations of paths with and without path separators in various positions.

Make building directory paths a bit more robust.

---

src/mon-list.c
src/ui-mon-list.c

This fixes a few things about the monster list:
- The second part of 1970, when the monster list isn't updated when it should be. The monster list should be much more responsive to changes. I don't think this should cause any noticeable performance problems, especially due to the next fix.
- This also fixes an issue where processing monster list could cause lots of churn, resulting in relatively long sorting and drawing times. A lot of times, this could also lead to a crash (which is also fixed below).
- An array bounds crash was fixed.
- Corrects the "asleep" string when only one member of a group is asleep:
`2 Jackals (asleep)` will now correctly render as `2 Jackals (1 asleep)`

Fixes for monster list.

---

src/cmd-pickup.c

Sets `PR_ITEMLIST` on pickup and auto pickup. There didn't seem to be any issues with the object list updating when dropping from equipment or inventory, wielding from the floor, or when monsters drop. This should fix the first part of 1970.

Update object list on pickup. [1970]

---

src/ui-birth.c
src/ui-knowledge.c
src/z-textblock.c

Reworks text block wrapping so that a trailing \n isn't required to wrap properly.

Wrap textblocks properly without forced line breaks. [1804]

---

src/obj-list.c
src/wiz-debug.c

This fixes additional issues in 1611 relating to prefixes for soft armors in two parts:
- The first part of the fix prevents the object list from trying to unique the list by object type. `?..@.?` would only show one book with the coordinates of the eastern one (since it's the closest). Now, that same situation would show both books separately with correct coordinates. This also handles stacks correctly. If the left `?` was a stack of books, the stack will be shown on its own line, and the singular book to the right will be on its own line. This new behavior seems to me more consistent and clear than the old.
- The second part just fixes some implementation errors with the specific checks for soft armors and such. Some data isn't being cleared somewhere, which was triggering incorrect …

Fix more object list stuff.

---

src/player-util.c

If the map panel changes when the player is running, the map is not refreshed. The player stops running when 'disturbed', which is an ideal time to refresh the players view of the world

Force map refresh if player is disturbed while running

---

src/game-world.c
src/player-timed.c
src/player-timed.h

Replaced magic numbers of CUT timer values with constants as they are used in several places.
I considered suffixing the constants with ```_MAX``` to emphasis that the timer values are the upper limit of the associated cut type:
```
#define TMD_CUT_NONE        0
#define TMD_CUT_GRAZE_MAX   10
#define TMD_CUT_LIGHT_MAX   25
#define TMD_CUT_BAD_MAX     50
#define TMD_CUT_NASTY_MAX   100
#define TMD_CUT_SEVERE_MAX  200
#define TMD_CUT_DEEP_MAX    1000
```

Removed magic numbers from CUT timer.

---

lib/help/option.txt
src/cmd-cave.c
src/effects.c
src/gen-util.c
src/generate.c
src/list-options.h
src/main-stats.c
src/obj-pile.c
src/ui-display.c

Also rearrange the options a bit so they're more thematic - randarts,
dungen, object difficulty options are grouped together.
Silently breaks savefile compat for ongoing characters - renamed options will reset to their defaults
As suggested by Nomad http://angband.oook.cz/forum/showpost.php?p=110029&postcount=54

Fix the worst cases of double negative options

---

src/generate.c
src/init.c
src/mon-init.c
src/parser.c
src/parser.h
src/player-quest.c
src/store.c

Removed call to `quit` from `parse_file`.  Quitting is now performed by new wrapper function, `parse_file_quit_not_found`.  This creates two entry points, a one for optional config files like _lore_ (`parse_file`) and a one for mandatory config files (`parse_file_quit_not_found`).
This removes checking for "lore" filename within `parse_file`, makes the function more generic, and makes it clear in the calling code if a failure to locate the file will result in a `quit`.

Parser arg to state err or quit on file not found.

---

src/effects.c
src/project-player.c
src/wiz-debug.c

* Make debug mode trap creation ask for the trap name.  This makes testing new traps a ton less frustrating
* Allow traps to use ball effects that can hurt the player

Improving trap effect handling & debug mode

---

lib/help/attack.txt
lib/help/command.txt
lib/help/copying.txt
lib/help/customize.txt
lib/help/debug.txt
lib/help/dungeon.txt
lib/help/general.txt
lib/help/guide.txt
lib/help/help.hlp
lib/help/modifying.txt
lib/help/option.txt
lib/help/playing.txt
lib/help/version.txt

Just went through help and spell checked a bunch of stuff. I also reformatted a couple of places where the text was over 80 characters, with a few changes to word choice just to make that easier. 
I didn't change spelling mistakes in Robert Alan Koeneke's email excerpt in Version Information, for historical reasons, and also because I thought it was super cute :3 
Thanks!

fixed spelling errors in help

---

lib/gamedata/class.txt
lib/gamedata/monster.txt
src/gen-room.c
src/init.c

Shimmering monsters should actually shimmer.  Iridescent beetle should shimmer blue (for electric attack.) dependent is not usually spelled dependant, and currently it is spelled both ways in various files.

Few minor fixes.

---

configure.ac

Some systems (like OpenBSD) do not ship pkg-config/ncurses5-config information
for ncurses, since it's part of their base system, and not necessary. In that
case, fallback to checking for a function (`initscr`) in `libncursesw`.
Additionally, define `_XOPEN_SOURCE_EXTENDED`, which ensures that angband
picks up the right definitions of `mvwaddnwstr`.
This fixes #1638, #1682, #1939 and #1976 in trac.

Fallback to AC_CHECK_LIB if pkg-config check fails

---

src/cave.h
src/mon-spell.h
src/monster.h
src/obj-properties.h
src/player.h
src/trap.h
src/z-bitflag.c
src/z-bitflag.h

--
The code was causing a compiler warning:
```
z-bitflag.c: In function ‘flag_comp_union’:
z-bitflag.c:319:7: warning: promoted ~unsigned is always non-zero [-Wsign-compare]
if (!(~flags1[i] & ~flags2[i])) delta = true;
^
```
... but looking into it I discovered that the function wasn't actually used anywhere, so it might as well be removed.

Remove unused flag_comp_union()

---

src/cmd-cave.c
src/mon-init.c

--
This was causing compilation warnings on gcc 6.1.1 (at least I *think* the compilation was using gcc... might have been clang 3.8.0).

Indentation fixes

---

lib/gamedata/ego_item.txt
src/cmd-obj.c
src/init.c
src/obj-info.c
src/obj-make.c
src/object.h

Fizzix tweaked allocation probabilities in commit abd780f but these were only incompletely applied because the underlying code wasn't using those all the new values.
ego_item.txt had two lines about generation chance: `alloc` and `info`.  Both lines specified depth and rarity in two different formats (due to unfinished work started in commit 0321b59).  The game got rarity information from `info`, but the depth information came from `alloc`.  This commit fixes that.
This pull request:
- switches to the 'new style' allocation lines and removes the old ones
- refactors the ego item selection code to make the flow more obvious
- runs and loads but is not tested for balance

Enable fizzix's probability tweaks from 2012

---

src/obj-make.c

When I removed the CHR stat, I dropped the amount of gold created by 10% to compensate for the lower prices.  Looking at the actual values again, I noticed that in the early game CHR would increase prices by more like 20% compared to current.  This change thus reduces the amount of gold generated by 20% compared to versions that had CHR, a further 10% reduction from 3.5.
Also, avoid capping gold at SHORT_MAX - instead reduce the amount by 1d200 so it doesn't feel quite so much like you're maxxing out game internals.
(File under 'making things harder')

Reduce the supply of gold, in line with its value in older versions

---

src/cave-square.c
src/cave.h
src/cmd-cave.c
src/cmd-core.c
src/player-path.c
src/project.c
src/project.h
src/ui-target.c

Running count for distances between "I want RSI" and "I want to feed my character to anything that wanders in from outside detection range". This exposed a bug where p->u->running drops to 0 that wasn't plausible without running count (technically you could use earthquake or something to make a loop to run around or something, but...)
Targeting changes prevent an information leak by showing where a target is blocked by unseen barriers
This should have been two separate pulls, but I think I needed to make a sub-fork before I started or something.

Allow count for running

---

.gitignore

Updating .gitignore because save files on Linux are now based on user name rather than user id.

.gitignore all save files on Linux

---

src/ui-input.c
src/ui-input.h
src/ui-options.c
src/ui-options.h
src/ui-player.c
src/ui-player.h

The argument -f, force player names, was added to facilitate playing on a server, in my case for dgamelaunch. Currently, players can save to arbitrary files, which allows "/" and "." characters. This is not safe for playing on a shared system online. I added alternate file saving functions which checks for that argument.
Character dumps have file names consisting of the player name and timestamp. 
Players can no longer change their name in the Character menu ('C').
Player .pref files are saved in the pref directory, and the file name consists of their playername.pref.
Functionally, the game should perform normally without the -f argument given.

Added alternate file save method for server play

---

lib/gamedata/hints.txt

Since with the new ID system, you can't use a scroll of Identify on a
potion or scroll, this rumor no longer makes much sense.

Remove rumor suggesting scroll of ID on consumables

---

.travis.yml

After setting up an account for angband at https://travis-ci.org, this should automatically build the project and run the tests when pull requests are opened and when pushes are made.  See the same PR at [my fork](https://github.com/AlexMooney/angband/pull/1) for an example (make sure to click on `show all checks`).
You should be able to see, for instance, that using clang you get this warning:
```
obj-properties.c:62:17: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
va_start(args, id);
^
obj-properties.c:55:44: note: parameter of type 'bool' is declared here
void create_obj_flag_mask(bitflag *f, bool id, ...)
^
1 warning generated.
Successfully compiled obj-properties.c.
```
We could also set up CI to test the mac …

Add a basic Travis CI to compile and run tests

---

lib/help/option.txt
src/list-options.h
src/option.h
src/ui-display.c
src/ui-player.c

```
Show effective speed as multiplier '[effective_speed]'
Instead of showing absolute speed modifier (e.g. 'Slow (-2)' or
'Fast (+38)'), show the effective rate at which the character is
moving (e.g. 'Slow (x0.8)' or 'Fast (x4.1)').
```
This was suggested on the forums as a way to help players understand the diminishing returns of ever higher speed numbers.

Add option to display effective speed

---

src/effects.c
src/effects.h
src/game-input.h
src/player.h
src/ui-object.c
src/ui-object.h

Unfortunately had to use a new global in player->upkeep to keep track of
the power of the recharge effect from the effect_handler through several
layers of function calls to have it available for the show_obj code.
This version is based on advice from @takkaria.  Thanks for the advice!

Show recharge failure chances in item list

---

src/mon-lore.c

This will greatly improve the use of the monster lore by simply telling the player how bad the attacks are in aggregate.
> It can hit to attack with damage 4d8 with a 76 percent chance to hit, and hit to attack with damage 4d8 with a 76 percent chance to hit, which is about 28 damage per turn total.
Verified that `0.76*8*4.5 = 27.36`, which rounds up to 28.
> He can hit to shatter with damage 20d10 with an 89 percent chance to hit, hit to shatter with damage 20d10 with an 89 percent chance to hit, hit to reduce all stats with damage 10d12 with an 87 percent chance to hit, and touch to drain charges with an 88 percent chance to hit, which is about 253 damage per turn total.
Verified that `0.89*40*5.5 + 0.87*10*6.5 = 252.35`, which rounds up to 253.

Show total expected monster damage in lore

---

acinclude.m4
configure.ac
src/main-sdl2.c

Looks like there were three things wrong:
1) main-sdl2.c: USE_SDL2 is defined in autoconf.h, so it must be
included (via angband.h) before "ifdef USE_SDL2".
2) configure.ac: AM_PATH_SDL2, of course, instead of AM_PATH_SDL.
3) acinclude.m4: SDL2 uses SDL.h and not SDL2.h (yes, it's strange).

Fix build system for SDL2 port

---

src/Makefile.osx

Build architectures can now be configured by setting `ARCHS`. This helps prepare for macOS Mojave, where you can't build for i386 anymore (at least not with the MacOSX10.14 SDK).

Allow macOS build architectures to be configured

---

src/Makefile

This ensures any `LDFLAGS` the user has requested are used.

Use LDFLAGS when linking angband.o

---

src/cmd-core.c

Check against the value pointed by the pointer 'dir' instead of the value of  the pointer.
The bug was introduced in the following change.
Commit: 02c1db88fd2c659e7478d4ce859458f98cc53794 [02c1db8]
Parents: 7c5a0c4d14
Author: Andi Sidwell <andi@takkaria.org>
Date: 4 Mar 2014 2:00:24
Committer: Andi Sidwell
Commit Date: 5 Mar 2014 16:55:28
Remove some replicated code

Check the validity of the direction returned from cmd_get_arg_direction()

---

src/load.c

As the type of the function is bool, it should return false instead of -1.

Change the return value of rd_monster() when the monster race does not exist.

---

src/store.c

The game should call gear_to_label() before calling 
gear_object_for_use() as done in inven_drop().

Fix a bug where stashing an entire stack of an object does not show the label of the object

---

lib/help/modifying.txt

I've drafted new documentation for modifying.txt that explains in detail how to define a new graphical tileset from scratch. My goal is to lower the bar to entry for artists that would like to contribute tilesets in the hopes that we might see more art contributions. I tried to keep it terse but without missing any important details. As I'm mostly unfamiliar with the code base I'm looking for feedback and corrections (especially where I may be unintentionally telling lies).
I have tested my own documentation and was able to create a new tileset and get it to work in game. Albeit it was only for a single tile to replace the home tile in town. I've also tested generating the manual and it appears to render well in the PDF and HTML versions.
As a side note, I do find the help format to be …

Tiles docs

---

src/effects.c
src/main-gcu.c
src/obj-properties.c
src/obj-properties.h
src/z-type.c
src/z-type.h

1) Define _XOPEN_SOURCE_EXTENDED so macOS ncurses.h will provide mvwaddnstr()
2) Don't use a bool (which auto-promotes) as the last argument in a variadic
function in create_obj_flag_mask()
3) Small rewrite in effect_handler_TELEPORT_TO() to fix a case where the player
picks DIR_TARGET but has no valid target, or picks any other direction
(although the latter should be impossible here).

Fix warnings on macOS

---

src/main-win.c

The game may crash if ShowWindow() triggers a WM_PAINT event
before term_data_link() creates and initialize the term data,
trying to access yet unallocated data (old and scr) at Term_fresh().

Initialize the term data before showing sub windows

---

src/player-birth.c

When Player rolls a new character, the previous character's history is saved
but then freed in do_cmd_roll_stats(), making the saved history a dangling
pointer. If player goes back to the previous character and then reroll,
the game tries to free already free data.

Set player->history NULL after saving it to birther

---

src/ui-store.c

If Player is in a store/home and clicks the header line (line 3,
where "Store/Home Inventry" is displayed) and the store/home is
empty (hence oid is -1 because cursor is not on a list item),
the game still thinks press is on a list item and tries to
show the store item context menu for non-existant item and make
an illegal memory access.
Checking if clicked location is actually on a list item (if y is
more than or equal to 4) ensures this does not happen.

Ensure press is on a list item before showing the context menu

---

src/ui-object.c

The game crashes in the following scenario.
1. The player character is on item(s).
2. The player right-clicks on the player character.
3. Choose "f) Floor" command from the context menu.
context_menu_player_display_floor() calls get_item() with
the parameter 'pmt' NULL and textui_get_item() calls
strlen() with it.

Perform a null check before calling strlen() in textui_get_item()

---

configure.ac

It is needed on systems where libtinfo is separate from libncurses.
See: https://bugs.gentoo.org/679942

Link against tinfow or tinfo if needed

---

src/target.c
src/ui-display.c

This results wrong monster description when 'l'ooked and
wrong color for the monster health bar.

Fix wrong if-conditions for monster timed effects

---

src/player-path.c

This bug was causing is_valid_pf to return true for all known, harmless squares.

Fix pathfinding bug.

---

src/ui-help.c

Added 'j' and 'k' to scroll down/up in the help screen. Mirrors the roguelike keyset movement keys.

Add j/k keys for scrolling help text

---

src/main-cocoa.m

If the font is changed, update the minimum window size and force the window to be at least that size.  Put the minimum window size calculation in a separate function so it can be called at initialization and in response to font changes.

OS X - recalculate minimum size in response to font change

---

src/main-cocoa.m

That way SYS evaluates as "mac" in preference files rather than "xxx".

OS X: set ANGBAND_SYS before calling load_prefs()

---

src/main-cocoa.m

Changed to skip saving the window size to the defaults from windowDidEndLiveResize() if resize is due to transitioning to or from full screen mode.  That fixes Angband issue 4114 ( https://github.com/angband/angband/issues/4114 ):  exiting Angband while in fullscreen mode and then restarting leaves terminal 0 acting as if it was the full screen size even though the actual window is not that size (because the attempt to resize to the size saved in the defaults presumably failed).

OS X:  don't save size to defaults at end of live resize if transitioning to/from fullscreen

---

src/h-basic.h
src/load.c
src/z-file.c

Changes will enable compilation using VS2019 (tested), and I think VS2017 and VS2015 (not tested), but deprecate VS2013 and earlier.

Changes for VS 2019 compilation

---

.gitignore

VS creates a lot of intermediate files that should never be checked in. 
They are all in 3 sub-folders immediately under the project root, and this update
to .gitignore ignores the 3 folders. 
Also, to use VS, the developer will copy the angband.vcxproj* files from src\win\vs2019 to the root of
the angband tree, and those files should not be checked in from there, so ignore them too.

gitignore VS build intermediates

---

src/main-cocoa.m

Disable the save menu entry while on the splash screen and during player birth.  Disable the command menu entries during player birth.

OS X:  save menu entry and command menu entry sensitivity

---

src/ui-term.c

The padding of scaled up tiles seems wrong:  the current logic adds dummy characters to a (tile_width + 1) x (tile_height + 1) box skipping the uppermost row and clipping by the status message row.  I had expected dummy characters in a tile_width x tile_height box skipping the upper left corner (already marked with the real tile information) and clipping by the status message row.
Adding an assertion for x + hor < t->wid in Term_big_queue_char() and running with the new OS X tile scaling (default scaling; Menlo regular 13 point font; 123 column x 31 row main window, I could trigger the assertion when I changed from classic ASCII to Adam Bolt's tiles while in the dungeon.
The pull request changes the loop logic to add dummy characters to a tile_width x tile_height box skipping the upper …

Correct loop logic in Term_big_queue_char()

---

src/cocoa/AppDelegate.h
src/cocoa/AppDelegate.m
src/main-cocoa.m

Porting the automatic reference counting (ARC) changes to Hengband revealed some parts that didn't work well with code derived from an older version of Angband.  Refactor so the OS X front end can be more similar for the two code bases and hopefully more useful to other variants or older versions.

OS X: refactor ARC changes to be more compatible with Hengband

---

.gitignore
src/main-gcu.c
src/ui-map.c

This PR fixes two GCU issues.
1. It fixes the bug where solid walls are displayed as hybrid walls (described [here](http://angband.oook.cz/forum/showthread.php?t=9353)). The problem was that it was just inverting the bg and fg colors rather than setting them both to the same color.
1. I adds a new flag `-D` for instructing it to NOT use the terminal's default background color. I use a color scheme with a light background color and the game is unplayable with it. Personally, I think Angband should use black by default (since this is known to be playable) and have a flag if you want to use your terminal default, but I didn't want to change existing behavior.
Let me know if you want any changes.

GCU fixes: solid walls & black background

---

src/main-cocoa.m

The change to better handle font changes during play had the side effect of causing a crash if the font or tile set was changed on the splash screen and then the player proceeded with character generation.  It would also cause a crash if the font or tile set was changed during character generation.
This pull request fixes that.

OS X:  correct regression for changing font or tile set and character generation

---

src/ui-term.c

With the post 4.2.0 code base and either the X11 front end on Linux or the OS X front end, the following,
1. Bring up the knowledge menu with ~.
2. In that, bring up the monster recall for  a specific creature.
3. While that is displayed, resize the window.
4. Leave the knowledge menu.
, would leave uncleared characters on the screen.  This pull request, which handles all of the saved stack of terminals in Term_resize() and not just the uppermost one, appears to resolve that.

Change Term_resize() to handle all of the saved stack of terminals

---

src/main-cocoa.m

Also took the opportunity to do some refactoring of the tests for the graphics mode.

OS X: fix bug; user tile set scaling change at splash/birth does not stick

---

src/ui-map.c

That was seen with the current OS X front-end in post 4.2.0.  The subwindow flags were the default:  one terminal was set up as the overhead view.  This change (in print_rel_map() write the padding characters for the scaled up tile to the same terminal as the attributes for the tile) appears to fix that.

With scaled up tiles, projection effects would occasionally wipe parts of the stats area

---

src/main-cocoa.m

Make the increment in x the current width for a column.  Make the increment in y the current height for a row.  Increments less than that just add unused border space on the right and bottom.  Could factor in the tile scaling to the increments for the same reason, but I was concerned that, at least for the Shockbolt tiles with the default scaling, that coarse of an increment wouldn't feel natural during resizes.

OS X: constrain incremental size changes to the windows by the user

---

src/main-cocoa.m

That makes the handling the same as the number of rows:  prefer empty space to a partially cutoff character.  It reverts a change in Ben Semmler's May 27th, 2013 commit, "Remove resize snapping for now".  If user changes to the size are limited to integral number of columns or rows, this change will only have an effect after font changes or for programmatic size changes (which aren't constrained by NSWindow's contentSizeIncrements).

OS X: round down when calculating the number of columns

---

src/main-cocoa.m

That helps performance (though to me the subjective gains aren't anywhere near to what the measurements were suggesting, possibly because there's still a lot of variation and the slow renders probably dominate the subjective perception of the performance) but complicates the code.  There's more details in the commit message.

OS X:  change normal rendering path to avoid our own offscreen buffer

---

src/main-cocoa.m

Clicks on the title bar were being passed on with a negative y coordinate and that was one source of invalid coordinates triggering an infinite loop in the interactive target selection, [issue 4217](https://github.com/angband/angband/issues/4217).  This isn't sufficient to resolve that issue:  even with this change resizing the window while in targeting can lead to a mouse event with coordinates that trigger the infinite loop.

Only pass along mouse events if they fall in the terminal bounds.

---

src/ui-target.c

For cases where the potential target coordinates are reset via the mouse, the targeting loop isn't done, and the coordinates aren't otherwise known to be valid, check that they're valid.  If not, reset them to the player's location.  That avoids more of the triggers for the infinite loop in issue 4217 (resizing the window while in targeting mode on OS X no longer seems to fall into the infinite loop for instance).

In interactive targeting, add some coercion for coordinates from mouse events

---

src/load.c

It's possible that the previous code could explain Glorfindel's report of a unique coming back to life in issue 4245 ( https://github.com/angband/angband/issues/4245 ), i.e. if the previous entry had an invalid name and scanning that theft count plus Quaker's name caused Quaker's name to not be recognized, but that seems unlikely.  It wouldn't explain sinquen's report about Beorn since there the monster knowledge listed Beorn as dead.

When reading monster memory, skip both kill and theft count if name unknown

---

lib/customize/font-gcu.prf

As discussed in [this thread](http://angband.oook.cz/forum/showpost.php?p=143936&postcount=20), there's probably no need for the treasure tiles to be specially mapped to the block character in the GCU version any more. I suspect that this is a hold over from when solid walls were originally implemented. I think it makes more sense for everything to be ascii by default and only use blocks when solid walls are enabled.

GCU: remove custom treasure mappings

---

src/store.c

This is related to [issue 4335](https://github.com/angband/angband/issues/4335) but didn't come up in those runs.

Plug memory leak when an unidentified worthless item is sold

---

src/obj-info.c

Was mentioned as a possibility in [this forum post](http://angband.oook.cz/forum/showthread.php?p=141118#post141118l).  Verified that leaks were flagged by Xcode's Leaks instrument.

Plug leak of memory for slays/brands/curses in object_info_ego()

---

src/wiz-debug.c

Was mentioned as a possibility in [this forum post](http://angband.oook.cz/forum/showthread.php?p=141118#post141118).  Verified that Xcode's Leaks instrument flagged memory leaks.

Plug leak of memory for slays/brands/curses in wiz_reroll_item()

---

src/cave-square.c
src/cave.h
src/cmd-pickup.c
src/effects.c
src/mon-make.c
src/mon-move.c
src/project-obj.c
src/wiz-stats.c

Given the number of place that use the combination of square_excise_object(), delist_object(), object_delete(), square_note_spot(), and square_light_spot, it seems useful to have a convenience function to perform that sequence of operations.  This change calls it square_delete_object(), puts the prototype in cave.h, and puts the definition in cave-square.c.
The change makes use of the new function in the places where that combination appeared.   For the deletion of a mimicked object in delete_monster_idx(), the change has the effect of adding a call to square_note_spot().

Add a convenience function, square_delete_object()

---

src/effects.c

Currently the sense/detect objects effects can only add marks to the map and won't remove marks if a location is sensed/detected as empty. I tried in [this thread](http://angband.oook.cz/forum/showthread.php?t=9961) to get a sense if the community thought removing marks would be a good or bad thing, but didn't get a strong response either way.
If it seems like a desirable thing to do, this change allows both the sense and detect objects effects to remove marks if a location in range is empty.

Change to allow sense/detect objects to remove marks on the map if empty

---

src/effects.c

Like the object sense/detect effects, the detect buried treasure effect currently can only add marks to the map.  This change allows it to remove previously seen or marked buried treasure if now none is detected at the location.
Probably most useful for dwarves who would have a bit of advance warning for an incoming umber hulk if there's some buried treasure in its way.

Change to allow the detect buried treasure effect to remove marks on the map

---

src/cave.c
src/mon-make.c
src/mon-move.c
src/mon-util.c
src/obj-knowledge.c
src/obj-pile.c

The first part of the change is to enforce that an object in the cave or a monster's inventory which has a known version will have that known version included in the object list of the player's cave.  If that known version has a position that's unknown (it either hasn't been sensed or detected since the object was dropped in the cave or is in a monster's inventory) the known version will have it's grid location set to (0,0) but it is not in the pile at (0,0).  From my understanding of how the savefiles are written and loaded, this does not break compatibility with old savefiles (any known objects which weren't in the object list of the player's cave would not have been recorded in the savefile).
The second part of the change is for what happens when a monster picks up an object or an …

Change object handling in the cave for issues 4348 and 4335

---

lib/help/commands.txt

To resolve https://github.com/angband/angband/issues/4352 .

Mark'(' (former load screen dump command) as unused.

---

src/ui-command.c

Does it by skipping over the padding in the map with scaled up tiles.

Fix screenshots with scaled tiles (resolves #4289)

---

docs/customize.rst
src/cmd-pickup.c
src/obj-util.c
src/obj-util.h
src/tests/object/util.c

To address #2658 and #2932 , changes cmd-pickup.c to look for =g<number> inscriptions (as in Unangband) to limit the number of item's automatically picked up to be max(number - number in pack, 0).  Since 4.2.0 allows the 'always pickup' option to override !g inscriptions, it also overrides the =g<number> inscription in this version.  The 'pickup if in inventory' option honors the =g<number> inscription.
This doesn't implement the =d<number> and =i<number> inscriptions mentioned in #2658 and in the Unangband documentation.  Though it does not use the Max=# form suggested in #2932 , it addresses the same issue.  The autoinscription mentioned in #2932 is not implemented; presumably a player could configure it with the existing autoinscription feature.

Use =g<n> (i.e. =g8) inscription to limit auto pickup

---

src/cmd-obj.c

is read from the floor.  Earlier change to push_object() left the object reference in use_aux() dangling.  Has the drawbacks of extra overhead (more copying of objects on use), more message spam (and extra call to drop_near() if on floor) for cases where a scroll isn't used, and the messages about removing a single-use item are printed before identification so they won't show the newly identified type on first use.
Resolves part of #4360 - Diego Gonzalez's report. sphara's report indicates that the rune of protection scroll was in the inventory when the crash happened.  I haven't been able to reproduce that and this change should not help in that case.

Restructure use_aux() to avoid crash when a Rune of Protection scroll

---

lib/gamedata/Makefile
lib/gamedata/object_property.txt
lib/gamedata/player_property.txt
lib/gamedata/ui_entry.txt
lib/gamedata/ui_entry_base.txt
lib/gamedata/ui_entry_renderer.txt
src/Makefile.src
src/init.c
src/list-ui-entry-renderers.h
src/obj-init.c
src/player-calcs.c
src/player.c
src/player.h
src/ui-entry-init.h
src/ui-entry-renderers.c
src/ui-entry-renderers.h
src/ui-entry.c
src/ui-entry.h
src/ui-options.c
src/ui-player.c
src/ui-prefs.c
src/ui-prefs.h

Added infrastructure to drive the resistance panel and object stat/sustain information in the character screen from the configuration files. ui_entry_renderer.txt configures types of formatting. The backend code is in list-ui-entry-renderers.h, ui-entry-renderers.h, and ui-entry-renderers.c. ui_entry.txt (with templates from ui_entry_base.txt) configures the links between object or player properties and those formatters. It also sets some details of the character screen (labels, category, order within category). The backend code is in ui-entry.h and ui-entry.c. ui-entry-init.h exposes the bits needed by init.c for initialization and cleanup. ui-player.c for the resistance panel and stat/sustain object information now largely just does placement and iteration over the elements. The data …

Have more of the 2nd character sheet controlled by the configuration files

---

src/obj-init.c
src/obj-knowledge.c
src/ui-game.c

Mark the known versions of the stock curse objects as touched so full knowledge can propagate to them in the normal way.  Backed out the prior change to resolve those since it should now be redundant and had an issue with changing the modifier on a curse.  When resuming from a savefile, call update_player_object_knowledge() so the stock curse objects are up-to-date with the knowledge of the newly loaded character.  That resolves #4377 where immediately looking at the character screen after loading with a cursed item did not show the effects of the curse.

Use an alternate method for resolving curse ID issues ( #4190 and #4334 )

---

lib/gamedata/brand.txt
src/obj-init.c
src/obj-slays.c
src/obj-slays.h
src/object.h
src/player-attack.c

Resolves #4198 .
I used two as the multiplier for the extra damage since that's the multiplicative factor in project-mon.c and man-blows.c.  So a weak fire/cold brand would add 40% to the damage dice against a HURT_FIRE/HURT_COLD monster in standard combat and a strong fire/cold brand would add 60% to the damage dice in the same situation.  For O-combat, the modifier is set to (config_mod-10)*2+10 when a brand hits an especially vulnerable monster.  Is that the right thing to do?

Increase player's melee/missile/thrown damage if brand hits vulnerability

---

src/obj-make.c
src/tests/object/alloc.c
src/tests/object/suite.mk

Prompted by #2746, this adds a binary search in get_obj_num().  The gains are modest (called in a tight loop, get_obj_num(level, false, 0) takes about .74x of what it did before the change; get_obj_num(level, true, 0) takes about .90x of what it did).  If looking for performance gains in level setup, some current hot spots are ensure_connectedness(), find_empty(), and lookup_kind().

Add alloc table binary search

---

src/tests/artifact/name.c
src/tests/game/basic.c
src/tests/game/mage.c
src/tests/object/util.c
src/tests/unit-test.c

Brings it into agreement with the README and the usage in unit-tests.c's main().  Some of the unit tests also declare teardown_test() that way.  Change them as well.  Since none use the argument only the declaration changes.

Change prototype for teardown_test() in unit-test.c

---

lib/gamedata/ui_entry.txt
src/ui-entry.c
src/ui-equip-cmp.c

Fixes:
- Some attributes couldn't be selected with the quick filter because of having the same (up to capitalization) two character label.
- Setting a quick filter when another was in place wouldn't switch the property index used and would require clearing the previous filter first.
- Plug memory leak every time the equipment comparison is reopened.
Code cleanup:
- Bring up to date with the changes to allow for display of a total value.
- Update some configuration file and code comments.

First batch of equipment comparison fixes

---

src/tests/z-textblock/textblock.c
src/ui-equip-cmp.c
src/z-textblock.c
src/z-textblock.h

In the equipment comparison, using the option to show information on 'Sting' and something else would truncate the description for 'Sting' at the damage to animals because internally it used textblock_append(tb1, "%ls", textblock_text(tb2)) which ran into the limit of the internal buffer in vstrnfmt().
This adds a function, textblock_append_textblock(), to append a textblock to another.  It modifies the equipment comparison to use the new function.

Add function to append textblocks

---

src/obj-make.c
src/player-util.c
src/z-form.c
src/z-form.h
src/z-textblock.c

This pull request contains the following changes.
- Use INT32_MIN for -2147483648 and INT32_MAX for 2147483647
- Initialize a pointer variable with NULL 
- Remove va_copy() workaround for MSVC
See each commit massages for detail.

Fix various compilation problems for MSVC

---

src/message.c

Resolves the test that crashed (message_lookup_by_sound_name() if the name did not match anything) and the other that failed.(counter wraparound in message_add()).

Change message.c for failed unit tests

---

src/project-player.c
src/z-textblock.c

This pull request contains two commits that fix two ASAN failures.
- Fix an out-of-bounds access to el_info in ajust_dam()
If the `type` is equal to ELEM_MAX (25) or larger, 
e.g. LIGHT_WEAK (25), the access to `p->state.el_info`
is out of bounds.  This fix is similar to the following commit:
704ff8be982ebfe8ad8c02c5eeb1897085f099aa
- Account terminating '\0' for buffer length calculation in textblock_vappend_c()
This bug causes a textblock to have non-terminated text, leading
to a buffer over-run.  For example, generating a monster spoiler triggers
this and causes ASAN failure termination/windows build to crash.

Fix two ASAN failures

---

docs/hacking/compiling.rst
src/Makefile.msys2
src/Makefile.msys2.sdl2
src/main-win.c
src/main.c
src/sound-core.c
src/z-file.c

Msys2 is useful to manage dependencies on Windows, but it is not straightforward to build Angband with that. This adds two makefiles:
1. Makefile.msys2 : build ncurse client
2. Makefile.msys2.sdl2 : build sdl2 client
What's working:
* run angband with `./angband.exe -uPLAYER`
What's not working:
* load saved game without the `-uPLAYER` arguments
* sound in sdl2 client
* the display in sdl2 client can be bugged after resize, you have to change the font in the menu to force redraw the whole thing. And the redraw shortcut `^R` is missing in sdl2 client?
I think this can be merged for further testing and for others to work on the relevant code. For example, I don't understand autotools so I don't know how to / if I should integrate this with autotools.

Makefiles for compiling with ncurse and sdl2 on Windows msys2 shell

---

src/obj-init.c

This Addresses #4432.
When lookup_sval() returns a negative value (happens when the object 
specified does not exist), lookup_kind() returns NULL and causes a 
crash due to an improper member access through a NULL pointer.

Add sval validity check in parse_ego_item()

---

src/cave-map.c
src/cave-square.c
src/cave-view.c
src/cave.h
src/cmd-cave.c
src/effects.c
src/game-world.c
src/gen-cave.c
src/gen-chunk.c
src/gen-room.c
src/generate.c
src/mon-make.c
src/mon-move.c
src/mon-util.c
src/obj-pile.c
src/player-path.c
src/project-feat.c
src/project-mon.c
src/project.c
src/save.c
src/target.c
src/trap.c
src/ui-context.c
src/ui-target.c
src/wiz-debug.c

With the introduction of the square() function, access to a square in a 
cave chunk suffered performance reduction: every time square() is called,
struct square is created and content copied from cave->squares[x][y].
With this pull request, the function instead returns a pointer to the square
in the chunk, removes unnecessary copy operation. To enforce changes to
squares go through square_set_* functions, the pointer is const.
This may improve #4443.

Performance: Avoid copying when accessing a square in a cave

---

src/mon-make.c
src/mon-move.c
src/player-timed.c

- fixed apparent issue with trampling of shape-changed monsters
- fixed bug with food counter that stopped starvation when the counter hit 0 and caused the food indicator to disappear
- fixed bug with tracking of shape-changed monsters on destruction/trampling
- fixed bug with tracking of shape-changed monsters on leaving level
- fixed bug with tracking of shape-changed monsters on game loading, which should also fix a previously reported bug of the same unique being killed more than once

fixing bugs with shapechangers and food counter

---

src/cmd-obj.c
src/obj-knowledge.c

Change player_know_object() to also propagate knowledge of effect.  In testing with objects created by the debug commands, that resolves issue #4446 .   Follow up to revisit the recent change in use_aux() (to workaround knowledge propagation for single use objects) so that only the temporary object is accessed after use.

Change player_know_object() to also propagate knowledge of effect

---

configure.ac
src/sound-core.c

The first commit allows "./configure --enable-sdl2-mixer" and then compiling to generate an executable that includes the SDL sound module.  My Linux virtual machine doesn't appear to handle sound so I couldn't test it further than that.
As a result of the first commit, "./configure --enable-sdl2-mixer --enable-sdl-mixer" leads to duplicate symbols when linking so the 2nd commit rejects that with an error during the configuration step.
Those commits are an initial attempt to resolve #issue 4458 .

Attempt to resolve SDL2 sound configuration (issue 4458)

---

src/mon-make.c

obj->artifact would be dereferenced when the carry fails in the "Make some objects" loop.  Added a test for a non-NULL obj->artifact before dereferencing to avoid a crash.
I don't have a case where the crash occurred - just spotted this while trying to look for what might have caused the reported instance of generating the same randart twice in the same game.

Avoid crash in mon_create_drop() if carry fails

---

src/game-world.c

The placement of the call to search() may not be the best.  It's done after the initial display of the level feeling and won't be done for an arena level.

Search the surroundings (as if normal movement) upon changing a level

---

src/Makefile.osx

That should avoid the problem reported in http://angband.oook.cz/forum/showthread.php?t=10190 .  Do not have a system running 10.13 available for testing, but with this change, 'nm -u *.o | grep chkstk' doesn't report anything while it does report instances with the object files compiled without the change.

OS X: use -mmacosx_version_min for the C code as well

---

src/main-cocoa.m

Should have no noticeable effect on Vanilla and reduces the number of changes necessary when porting main-cocoa.m to a variant.  Can have some effect, because of the location of lore.txt, on https://github.com/NickMcConnell/FirstAgeAngband/issues/75 and https://github.com/NickMcConnell/FirstAgeAngband/issues/51 .  Will change the location of save files if adopted by a variant (like FirstAgeAngband) that was using the unchanged main-cocoa.m.

OS X: use VERSION_NAME instead of "Angband"

---

src/effects.c

Resolves https://github.com/NickMcConnell/FirstAgeAngband/issues/79 .

Allow a monster's confusion to affect breath targeting

---

lib/gamedata/object.txt

That distinguishes it from orange asterisks used for magma veins with treasure and is one way to resolve https://github.com/angband/angband/issues/4441 .

Use a white asterisk rather than an orange asterisk for detected gold on the floor

---

src/ui-entry.c

That works better than zero when the semantics of the underlying property are not known.  Should not have an effect on Vanilla but better handles FirstAgeAngband's resistance system.

Use UI_ENTRY_VALUE_NOT_PRESENT in initializations for player property values

---

src/obj-knowledge.c

Currently object_find_unknown_rune() is only called on an object with some unknown property so the leak  (even without this change) can't be triggered with the current version of Angband.

Plug memory leak if object_find_unknown_rune() returns early.

---

src/gen-util.c

Applied to the return values from find_empty(), find_nearby_grid(), and cave_find_in_range() to protect against accessing an uninitialized grid coordinates in the unlikely event of a search failure or, for find_nearby_grid(), a bogus starting point.

Check previously ignored return values from searches in gen_util.c

---

lib/gamedata/terrain.txt
src/cave-square.c
src/cave.h
src/init.c
src/ui-context.c
src/ui-target.c

The intent is to make it easier to resolve wobbly's report here, http://angband.oook.cz/forum/showpost.php?p=147606&postcount=129 , of cosmetic issues with FirstAgeAngband.  For Vanilla, the user visible changes are that the message for looking at lava will be "You see some lava" rather than "You see a lava", and the message for standing in a shop entrance will be "You are at the entrance to the ..." rather than "You are in the entrance to the ...".

Add terrain configuration items to help phrase messages for looking/targeting

---

src/effects.c

Should help diagnose the kind of errors like the one that caused this crash, http://angband.oook.cz/forum/showpost.php?p=147607&postcount=130 , reported by wobbly for FirstAgeAngband.

Add assertion to check for failed ego search in brand_object()

---

src/player-util.c

Should resolve Sideway's report about FirstAgeAngband here, http://angband.oook.cz/forum/showpost.php?p=147692&postcount=149 , but in cases where there's a difference in the strength modifier or where heavy wield comes into play, it may not choose the best digger.

Account for the weapon's weight in choosing the best digger

---

src/Makefile.src
src/effects-info.c
src/effects-info.h
src/obj-info.c
src/ui-knowledge.c

Attempts to resolve #4464 .  To display the effects triggered upon a shape change, some of the code from obj-info.c was refactored so it could be called both from obj-info.c and in the code to display the shape knowledge menu.

Add a shape knowledge menu

---

src/effects-info.c

That's a regression introduced when refactoring the code from obj-info.c into effects-info.c.  Resolves MITZE's report, for FirstAgeAngband, here, http://angband.oook.cz/forum/showpost.php?p=147742&postcount=159 .

Restore information about device skill boost on dragon's breath wand

---

src/obj-pile.c
src/wiz-debug.c

That's one place where objects are moved there wasn't special handling for them.  Also adds a debug mode command so it is easier to test push_object().

Add handling for unrevealed mimics in push_object()

---

src/obj-knowledge.c
src/obj-knowledge.h

Attempts to address some of the concerns raised here for FirstAgeAngband, http://angband.oook.cz/forum/showthread.php?t=10172&page=16 , starting with wobbly's post (number 157) and continuing till drquicksilver's post (number 168).  Has no effect on current Vanilla since the defined egos either have modifier ranges that are strictly zero or don't include zero.

Generalize player_knows_ego() to better handle modifier value ranges including zero

---

src/mon-move.c

The '!stagger' from before the change is equivalent to 'stagger == NO_STAGGER', but the revision had the negation of that.

Fix logic error introduced in confused move change

---

src/mon-group.c
src/mon-move.c

Adds checks in group_monster_tracking() so the returned tracker is active and is not the same as the monster looking to follow.
When group_monster_tracking() fails, will either continue to head to the monster's prior goal (if it was tracking at the end of its last active turn) or, when that's not possible, choose a random adjacent grid that is passable and not harmful as the target for the move.

Possible idea to resolve monsters failing to attack, #4444

---

src/wiz-stats.c

That mimics normal randart generation and avoids crashes in randart generation while accumulating the statistics.  Also, in the statistics with clearing and randart regeneration, reset to the artifact set from before statistics generation.

Statistics with randart regeneration: always use the standard artifacts as the base set

---

src/wiz-debug.c

- Was waiting for a keystroke which then interrupted the calculation before it started.
- Since make_object() can return NULL, there were crashes.
- Leaked the objects which were not matched to the original object's tval and sval.

Fix issues with statistics option in the object play debugging command

---

src/wiz-debug.c

That avoids crashes after rerolling or tweaking an object from the floor.

Preserve object's oidx, grid, and notice fields in object play debugging command

---

src/ui-knowledge.c
src/ui-menu.c
src/ui-menu.h

Resolves https://github.com/angband/angband/issues/4519 .  Could be partially done without the extension to ui-menu.c in the first commit (by setting cmd_keys and handling those keys after menu_select() returns), but then 4 and 6 are caught in the menu handling so alternate keys for the bookseller and magic shop would be needed.

Allow selection of store's contents by number in the knowledge menu

---

src/ui-entry.c

launcher will be null when a ranger character opens the resistances
window without a ranged weapon equipped, which causes a crash.

Fix crash in compute_ui_entry_values_for_player() with ranger character

---

src/main-cocoa.m

Wasn't considering the full GLYPH_COUNT glyphs:  introduced with the change to dynamically allocate working space.  With the default font, fixing the regression doesn't affect the display.  I didn't identify if there's one of the standard Mac fonts where it does make a difference.

OS X: fix updateGlyphInfo() regression in 4.2.1

---

src/obj-power.c

Fixes garbling of "Adding ... for extra shots ..." in randart.log.

log_obj():  output string as is (no % formatting)

---

src/wiz-stats.c

Attempts to fix some things noted with the disconnection statistics:
- The terminating condition for the distance calculation loop triggered after one iteration so all levels were considered disconnected.
- The logic used square_iswall() (i.e. not projectable) so doors would disconnect areas in the level.  Changed that to test for not passable and not door.  Impassable rubble will still disconnect areas for the purpose of the statistics.  Is that desirable?
- There was a memory leak.
- The distance calculation used some fixed size buffers though they were likely large enough to never overflow.  Changed to use dynamically allocated buffers that are resized as needed.  That change also replaces a copy with a swap for a bit of optimization.

Disconnection statistic changes

---

src/gen-cave.c
src/gen-util.c
src/generate.h
src/wiz-stats.c

Use it in a couple of places in the generation code when it bails on a failure.  Also use it in the implementation of the disconnection statistics to see the levels that are disconnected.  In the disconnection statistics, add an option to break out on the first level that is disconnected and remove the per-simulation message so a large number of simulations is less painful.

Add a facility to dump the level as HTML in gen-util.c

---

src/main-cocoa.m

Since the contents of Term aren't used, it isn't necessary.  Removing the call appears to resolve #4554 , a segmentation fault at startup on OS X 10.12.6 due to recursion (Term_init_cocoa() causes drawRect() to be called, which calls Term_activate(), which, in turn, ends up calling Term_init_cocoa()).

OS X:  don't bother to call Term_activate() from drawRect()

---

src/cmd-cave.c

When digging, the game switches you automatically to your best digger and recalculates your equipment bonuses.  After digging is complete it switches your weapon back, but doesn't recalculate equipment bonuses, so stat boosts from your weapon will not be applied until the next event that triggers a recalculation (such as equiping or taking off a piece of equipment).
This commit adds a recalculation after reequiping so that @s abilities will be accurate immediately.

Recalculate player equipment bonuses after digging.

---

src/ui-display.c

Hi ! The moves indicator overlapped the nutrition counter.

Fixed the display of the movement counter

---

src/sound-core.c

From http://angband.oook.cz/forum/showthread.php?t=8779 , that helps resolve a problem people had when following the instructions for compiling with Visual Studio.

Change sound-core.c to allow Windows builds without SOUND set

---

src/option.c
src/option.h
src/ui-options.c

Did that by adding three commands to the screen displaying the birth options at character generation.  They are:  's' to save the current settings for use as the defaults for future characters, 'r' to restore the current settings to what's in the saved defaults, and 'm' to restore the current settings to the maintainer's defaults.  The saved defaults appear as the file, customized_birth_options.txt, in the ANGBAND_DIR_USER directory.

Allow customization of the defaults for the birth options

---

CMakeLists.txt

I went to compile Angband for the first time in years, and saw it now had cmake support, and decided to try that.
As it turns out, two files were missing in the CMakeLists.txt file, and I had to add them to get it to compile, and I noticed that compiling with sound on SDL wasn't actually trying to bring in the SDL mixer, so I fixed that as well...

Add missing files to CMakeLists.txt, and fix SDL sound support.

---

src/gen-cave.c

When copying the normal half to the right side,  chunk_copy() already adjusts that position.  This may resolve Sphara's bug report, http://angband.oook.cz/forum/showpost.php?p=149394&postcount=138 , but I haven't seen the savefile to know.

In lair_gen(), remove correction to the player's position after chunk_copy()

---

src/main-cocoa.m

Add more thorough error checking when converting UTF-8 in Term_mbcs_cocoa().  Rather than terminate early on errors, substitutes U+FFFD in the converted result for a malformed sequence.
In the rendering, relax the assumption that a wchar_t fits in Apple's UniChar (a 16-bit type) and will use CFStringGetSurrogatePairForLongCharacter() (available since 10.6) to get a surrogate pair when a single 16-bit quantity isn't sufficient.  With that, the last two characters in "$¢€𐍈𐑙" can be properly rendered if the font in use has a representation for the character (likely not for the 4th one; the Geneva font has a representation for the 5th one).

OS X:  tweak Unicode handling

---

src/main-cocoa.m
src/tests/z-util/util.c
src/ui-birth.c
src/ui-event.c
src/ui-event.h
src/ui-input.c
src/z-util.c
src/z-util.h

The first two commits may be enough so [the change to remove the accents in FirstAgeAngband's history.txt](https://github.com/NickMcConnell/FirstAgeAngband/commit/8eb8c34bdbd8d627dc06fae214dd50696cbfd8c5#diff-bc2f48e9f8cac33b054e51af3816dfcbb73bae4c73634dfef18629694818eef7l) can be reverted, if the crashes that were seen were when someone tried to revise the history during birth.
There's some rough edges with this, especially with the Mac front-end:
- On all platforms, if a multibyte character is added to the character's name, player_safe_name() may be unduly restrictive in restricting the multibyte characters from filenames.
- The event handling by the Mac front-end bypasses the typical mechanisms for entering accented characters on a Mac so many of the multibyte characters that someone …

Accommodate multibyte characters in user text input

---

docs/customize.rst
docs/option.rst

- Remove the references to customizing the options from the preference files since that was removed some time ago.
- Document the new feature to save and restore the full set of birth options.

Update docs for option customization

---

lib/gamedata/dungeon_profile.txt
src/generate.c
src/generate.h

Replace the cutoffs for dungeon profile selection with allocation weights so there's no concern about maintaining ascending cutoffs or the relationship to the hardwired value of 200.  In the code, use PowerWyrm's selection algorithm from get_random_monster_object() so the selection can be done in one pass without extra storage.
The room selection algorithm is still the same and keeps the use of the cutoff values.

Make dungeon profile selection less error-prone

---

src/main-cocoa.m
src/main-win.c
src/mon-lore.c
src/mon-lore.h
src/ui-command.c
src/ui-entry-renderers.c
src/ui-equip-cmp.c
src/ui-mon-lore.c
src/ui-output.c
src/ui-player.c
src/ui-prefs.c
src/wiz-spoil.c
src/z-textblock.c
src/z-textblock.h
src/z-util.c
src/z-util.h

This is a resubmit of #4599 that will cleanly apply to the current master branch.
Those allow a front-end to override calls by the core to wctomb() or iswprint() so that a front-end that supplies a text_mbcs_hook can select behavior for reverse conversion and testing for printable characters that is compatible with what it does in text_mbcs_hook.
Replaced the current calls to wctomb() and iswprint() in the core with calls to functions that allow the platform-specific override.
In two places (textblock_to_file() and ui_entry_renderer_get_symbols()) where the core converted wide characters back to characters with simple casts, now use the replacement function for wctomb() to do the conversion. Removed the textblock_append_utf8() function since the back conversion in textblock_to_file() …

Add new wide character hooks

---

src/main-cocoa.m
src/main-win.c
src/z-util.c

Helps more on the Mac - perhaps because the custom fonts on Windows are missing glyphs for the multibyte characters I was using, ¢ and €, in my tests.
Also fixes a bug in the implementation of the iswprint hook in z-util.c.
Potential outstanding issues with multibyte characters:
-  choice of font with coverage for the characters of interest (the custom fonts on Windows and the old X11 font used by default with X11 may be the most problematic)
- for player input of multibyte characters, the interaction between the platform's input mechanism for those characters and Angband's event handling (definitely a problem with the Mac front end and entry of accented characters)
- whether the screening of the characters in player_safe_name() is still appropriate
- handling of character dumps on the …

Override iswprint with new hooks on Mac and Windows

---

src/wiz-debug.c

- Use get_string() rather askfor_aux() so the appropriate input mechanism for the front-end is used.
- Add some trailing spaces to parameter prompts for readability.

Some cleanup for do_cmd_wiz_effect()

---

.github/workflows/mac.yaml
src/Makefile.osx

Build universal binary targeting both x86_64 and arm64 architectures.
The game compiles on my computer (macOS 11.1, Xcode 12.3, ARM64) and yields a universal binary:
```
[brett] ~/git/angband [universal] ?? % file src/angband
src/angband: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
src/angband (for architecture x86_64):	Mach-O 64-bit executable x86_64
src/angband (for architecture arm64):	Mach-O 64-bit executable arm64
```
<del>But I don't have a macOS 10.x machine and don't know if this will work on macOS 10.x.</del> CI check result turns out to be, no. 😢

OS X: Build Mach-O universal binary

---

src/ui-equip-cmp.c

- Fix typo in displayed message (cosmetic problem present since 4.2.1).
- Like the resistance panel in the character sheet, alternate shading of columns so they're easier to track down the display.   Alternate the shading of the column labels as well to to hint that they should be parsed vertically rather than horizontally.  Both are responses to the suggestions here, http://angband.oook.cz/forum/showpost.php?p=150429&postcount=21 , and here, http://angband.oook.cz/forum/showpost.php?p=150844&postcount=8 .  The color choices for the labels are not currently configurable like the other colors used for the character sheet's resistance panel.
- Add an additional stage to the 'c' command so that only equipped items or items in the pack are shown.  That's a response to this suggestion, …

Tweak equipable comparison

---

.github/workflows/mac.yaml

- The macos11.0 runner is, for now only private preview (see https://github.com/actions/virtual-environments/issues/2486 ), so use macos-latest.
- Override the default SDK in the macos-latest runner so building a universal binary with the arm64 architecture works.

Switch runner for Mac CI environment

---

.github/workflows/release.yaml
scripts/pkg_win

Intends to meet the goals stated by Nick here, https://github.com/angband/angband/pull/4615#issuecomment-750850535 .
Uses scripts/pkg-win to generate the zip file for Windows.  Made some modifications to that so the result is closer to what's in the 4.2.1 zip file.
A sample release generated by workflow can be seen here https://github.com/backwardsEric/angband/releases/tag/4.2.0-565-g62dd324d .
Outstanding issues:
- Given the current state of the repository, the workflow gets the wrong version (4.2.0 rather than 4.2.1) for the release.  My best lead on why that happens is that the workflow uses git fetch with the --prune option when cloning the repository.  Running that command locally gives messages like "error: * Ignoring funny ref 'refs/remotes/origin//4.2-release' locally".  The …

Initial attempt to generate releases from a GitHub workflow

---

.github/workflows/linux.yaml

That avoids the problems that have been encountered since Arch updated the default glibc package to glibc-2.33-3.  To the extent that Arch has newer versions of the compilers and libraries, may lose some utility from the tests by using Ubuntu.
Something similar could be applied to the release and Windows workflows.  Because those haven't broken yet and there's pending pull requests for the release workflow, I didn't try to make those changes here.

Linux workflow: skip Arch and run directly on Ubuntu

---

.github/workflows/release.yaml
.github/workflows/windows.yaml

Since the Windows workflow has also broken, this changes the both it and the release workflow to run directly on Ubuntu.

Windows and release workflows: skip Arch

---

src/ui-equip-cmp.c
src/ui-knowledge.c

That better matches ordinary English spelling rules: "equip" -> "equipped", "equip" -> "equipping", "run" -> "runnable".  There's only one instance that's visible to the player; all the rest are in type names, enumeration constants, or comments.

Replace "equipable" with "equippable"

---

.github/workflows/release.yaml
scripts/pkg_win

- Ensure git is installed (likely a no-op since the Ubuntu runner has it already installed) so scripts/version.sh will work as expected.  If not present, would affect what angband.exe displays for the version number.
- Change pkg_win to include the *.woff fonts in the zip file: Angband 4.2.1's zip includes lib/fonts/16x16xw.woff.

Two adjustments for zip file produced by release workflow

---

.github/workflows/release.yaml
docs/conf.py
scripts/pkg_win
src/Makefile.osx

Should resolve https://github.com/angband/angband/issues/4630 : the zip and dmg files will get a set of HTML files that look like those on https://angband.readthedocs.io/en/latest/ .

In release workflow, copy converted docs to zip and dmg files

---

.github/workflows/release.yaml

It uses Python 3.  The package name for pip and the path to sphinx-build are different as a result of that causing the document conversion step to break (see https://github.com/NickMcConnell/FirstAgeAngband/actions/runs/576075696 for an example).

Fix release workflow for Ubuntu 20

---

.github/workflows/release.yaml
Makefile

Also some slight tweaks to how "make dist" works:
1. Exclude the continuous integration scripts (.travis.yml and contents of .github) from the result.
2. For the default TAG and version file, use the result of scripts/version.sh rather than call "git describe" directly.
This tries to address the second part of https://github.com/angband/angband/issues/4658 .

Release script: generate source archive with "make dist"

---

lib/gamedata/constants.txt
src/cmd-pickup.c
src/init.c
src/init.h
src/obj-gear.c
src/obj-gear.h
src/obj-pile.c
src/obj-pile.h
src/player-calcs.c
src/store.c
src/tests/player/calc-inventory.c
src/tests/player/inven-carry-num.c
src/tests/player/suite.mk
src/ui-store.c

- Add a utility function to test if the inscription on an item would put it in the quiver.
- Put the multiplier for non-ammo thrown items in constants.txt.
- Rewrite the logic in quiver_absorb_num() so it can consider expanding the number of slots used by the quiver or displacing an item in the quiver to another empty slot in the quiver.  Change calc_inventory() so it honors the limit imposed by quiver_slot_size when placing stacks in the quiver.  Allow it to consider splitting a stack in some circumstances to that part can go to the quiver.
- Modify combine_pack() so it honors the limit imposed by quiver_slot_size when trying to add to a stack in the quiver.
Along with those changes, simplify inven_carry_num() to drop the second argument since all current code calls it with the second …

Additional logic for thrown items in quiver

---

.github/workflows/release.yaml

Do that since there's some evidence, though not conclusive, that the builds on Ubuntu 20 aren't compatible with Windows 8.1:  see the posts starting with http://angband.oook.cz/forum/showpost.php?p=151841&postcount=253 .
Also run apt-get update before apt-get install for extra resilience against out-of-date package lists.

Build Windows release on Ubuntu 18

---

src/cmd-obj.c
src/player-attack.c
src/player-util.c
src/player-util.h

When casting while shapeshifted, you are given an opportunity to return to normal form, but are not prompted to select your book/spell unlike all other commands that let you cancel shapeshift.
In the first commit I thought that was a bug because I was so annoyed at having to type `mym4...` so often but now I realize it was probably intentional to allow players to change back to normal without having to ESC out of a command.
So my suggestion is to make all incompatible commands offer a 3-way choice:
* Change back and act
* Cancel the action
* Return to normal without acting
Still not sure these are the best names and locations for this code so I'm happy to make requested changes.

Fix form canceling when casting

---

lib/gamedata/activation.txt
src/effects-info.c
src/effects-info.h
src/obj-info.c
src/ui-spell.c

Improves the generic effect descriptions to include average damage. These descriptions are primarily used for objects, but also used for activations when the activation does not provide a description. Average damage calculation includes magic devices where appropriate, and will not be shown if there is no variance or a magic device bonus.
Descriptions are removed for basic damaging activations, so the game will fall back on the generic effect descriptions which include the average calculation. I checked for other references to the activation descriptions and do not foresee any other side effects from removing them. The generic descriptions are in most cases very similar, although sometimes slightly more wordy. Further improvements to the generic messages should be possible if desired. …

Display average damage for devices, spells, and activations

---

src/gen-cave.c

Appears to resolve https://github.com/angband/angband/issues/4720 .  Before the change, the disconnection statistics debugging command reported 441 disconnected levels with 176 of those disconnecting the player from the downstairs in 30000 attempts at generating level 37.  142 of the disconnected levels were gauntlet levels.  After the change, there were 233 disconnected levels with 28 of those disconnecting the player from the downstairs in 30000 attempts at generating level 37.  None of the those disconnected levels were gauntlet levels.
Remove the landing areas on each end of the gauntlet since they're no longer useful for helping connectivity.
Make two changes in join_region() that aren't related to the gauntlet connectivity issues:
- update the region counts for the connection that's …

Change logic in join_region() and gauntlet_gen() to avoid disconnected gauntlet levels

---

src/cave-view.c

That's for consistency with become_viewable() and resolves PowerWyrm's report here, http://angband.oook.cz/forum/showpost.php?p=152587&postcount=29 .

Use square_islit() rather than square_isglow() for initial determination of whether player's location is seen

---

src/gen-cave.c

- Skip the recoloring when connecting the cavern since the current version of join_region() maintains a consistent set of colors.  Also, the recoloring that was done was missing the step to reset the colors array to zero.
- Call ensure_connectedness() after drawing the landing area about the vault.  That way, the landing area will always be connected to the caverns.  For 5000 simulations with the disconnect stats debugging command at level 60 where only hard centre levels could be generated, without that change there were 93 levels with disconnected non-vault areas and 171 levels where the player was disconnected from the down stairs.  After the change, there were 0 levels with disconnected non-vault areas and 137 levels where the player was disconnected from the stairs (apparently all …

Adjust some logic for hard centre levels

---

src/gen-cave.c

- When testing for preemptive tunnel termination, don't overwrite the current state for the tunnel direction.
- Check for in bounds before attempting to suppress wall piercing at a grid.  Saw some out of bounds assertions without that change when running with modified dungeon profiles (only simple rooms for the modified and classic profiles; with the current state of find_space(), those could give an occasional room with a wall on the edge of the chunk).

Correct two logic errors in build_tunnel()

---

src/gen-room.c

It may not be worth the extra code but does allow tunnels to access those grids.  Would need a change to the tunneling code to have a tunnel coming through where the corner was to enter the room without bending away from the room and then bending back (i.e. tunnel goes through corner, considers going horizontally or vertically to a grid in the room's outer wall, and then, with a change to the tunneling code, is allowed to make the diagonal step to the room's interior).

For pillared rooms, cut off the corners when not adjacent to a floor

---

src/grafmode.c
src/grafmode.h
src/main-cocoa.m
src/main-sdl.c
src/main-sdl2.c
src/main-win.c
src/ui-term.c
src/ui-term.h

A front end will have to set the dblh_hook on the terminal to enable it and, to avoid unnecessary overhead, may want to set dblh_hook to NULL when using a tile set without double-height tiles.  As a convenience, provide a function, is_dh_tile(), in grafmode.h/grafmode.c that can be used for dblh_hook.  Modify the front ends that currently support double-height tiles (main-cocoa.m, main-sdl.c, main-sdl2.c, and main-win.c) to use this and not use the old method of calling Term_mark().  Tries to address performance issues when using the Shockbolt tiles.  See this thread, http://angband.oook.cz/forum/showthread.php?t=10720 , for a discussion.

Build in handling of double-height tiles into ui-term.c's change tracking

---

configure.ac
src/Makefile
src/tests/Makefile

Resolves a problem that came up in https://github.com/angband/angband/issues/4745 : rerunning configure with different flags for the front ends and then running make did not rebuild main.o.

Put -DHAVE_CONFIG_H in CPPFLAGS so it affects generated dependencies as well

---

src/main-sdl.c

- Remove two things that were set but not otherwise used.
- Streamline the clearing loop.

Tidy Term_pict_sdl()

---

src/main-win.c

Though, it doesn't seem to have a noticeable visual impact.

In Windows tile rendering, clear to cover full big tile dimensions

---

configure.ac

That's to avoid error messages during the dependency generation step which do not halt compilation (despite "fatal" in the message).  For --enable-sdl and --enable-sdl2, the error messages appeared after the recent change to put "-DHAVE_CONFIG_H" in CPPFLAGS.  For --enable-win, the error message was appearing before that change (see any of the old workflow results for Windows builds for messages about not finding png.h).

configure.ac:  adjust CPPFLAGS for more --enable options

---

docs/hacking/compiling.rst

Do that since there was some confusion in https://github.com/angband/angband/issues/4745 about what to do after compiling on Linux.

In the compiling documentation, briefly mention result and how to run for some common cases

---

src/obj-gear.c

- Don't require the inscription targeting the quiver to be the first inscription with '@'.  Allows a dagger inscribed with '@w0@v9' to appear in quiver slot 9.  As before, when choosing the preferred slot, only the first inscription targeting the quiver is consulted.
- Account for whether the original or Rogue-like keys are used when testing for an inscription to fire.  That resolves part of https://github.com/angband/angband/issues/4724 :  "@t1" as the inscription when using the Rogue-like keys did not place the object in quiver slot 1.

Improve quiver inscriptions

---

src/obj-info.c

The assertion happens when obj_known_digging() is called for a non-wearable item.

Change obj_known_digging() to avoid triggering assertion in slot_object()

---

src/gen-chunk.c
src/gen-room.c
src/generate.h

That's to add a little more variety in level generation.  I didn't edit room_template.txt to take out the ones that are now redundant with the internally applied transformations.
Transformations that would transpose the dimensions (90 or 270 degree rotations for instance) are disallowed if the centre is fixed rather than being dynamically chosen in the room builder.  When the center is not fixed, transformations that transpose the dimensions will be down weighted if the resulting room would be taller than it is wide.

Apply a (mostly-)random symmetry transformation when inserting vaults or room templates

---

src/cave.c
src/cave.h
src/gen-room.c

In initial pass add '#' as granite with the SQUARE_WALL_SOLID flag.  In the second pass through the room, convert the ones in the interior to SQUARE_WALL_INNER.  Simplifies compatibility with the tunneling code's procedure for passing through rooms.

Treat '#' similarly for vaults and room templates

---

src/gen-cave.c
src/gen-room.c
src/generate.h

Use a rather brutish approach to do that:
1. Add an argument to draw_rectangle() for whether it should overwrite something marked as permanent.
2. All calls to draw_rectangle() from gen-room.c don't allow the overwrite.
3. The calls to draw_rectangle() from gen-cave.c usually do allow overwrite as they set up or erase the borders.

Avoid simple rooms overwriting the permanent rock border

---

src/ui-map.c

Appears to resolve the second part of https://github.com/angband/angband/issues/4717 , at least for the SDL front-end.  With the Mac front-end, parts of the last row of big tiles still aren't cleared when coming back into town with an overhead view terminal that is more than large enough to show the town without clipping.

In prt_map_aux(), touch all locations in the terminal

---

src/ui-output.c
src/ui-term.c

Take advantage of that to remove the forced clear in screen_load() when big tiles are used.  Relates to Cuboideb's post, http://angband.oook.cz/forum/showpost.php?p=152990&postcount=35 .

ui-term.c:  check for changes in padded areas of big tiles and trigger redraw of tile if found

---

lib/tiles/adam-bolt/graf-new.prf

The column indices were off by two.  The most noticeable symptom was a change in appearance when a previously seen feature fell out of the line of sight:  up stairs appeared as a wall, down stairs as up stairs, and passable rubble as down stairs.

Adam Bolt's tiles:  change assignments for up stairs, down stairs, and passable rubble

---

src/ui-display.c
src/ui-map.c
src/ui-term.c
src/ui-term.h

Do that since the callers better know the purpose of the window than Term_big_queue_char() does (would have to look up the current terminal in angband_term and then get the flags from window_flag).  Resolves the last problem from https://github.com/angband/angband/issues/4717 : with big tiles there were clearing artifacts in the last row of the overhead view using the Mac front end.

Allow callers to set clipping for bottom of padding in Term_big_queue_char()

---

src/main-cocoa.m
src/main-sdl.c
src/main-sdl2.c
src/main-win.c
src/ui-term.c
src/ui-term.h

The previous test was that the row be greater than ROW_MAP + 1.  The new test is row greater than "first possible row for tile in terminal" + tile_height - 1, which for the main window is equivalent to ROW_MAP + tile_height - 1.  Put the "first possible row for tile in terminal" in ui-term.c since it uses the angband_term and window_flag arrays.  It isn't fully general (for one, it doesn't account for the main window being used to draw the overview map or for tile display in the knowledge menus; the old test didn't account for those either).
Does avoid some unnecessary dropping of upper halves, but the conditions for seeing that aren't particularly common (use a tile_height of one and have a double-height tile in the second row of the map in the main window; have a double-height tile in …

Be more consistent with the geometry in the tests for rendering upper halves of double-height tiles

---

src/obj-gear.c
src/tests/player/inven-carry-num.c

That's to be consistent with player_pickup_item().  Should resolve this bug report, http://angband.oook.cz/forum/showpost.php?p=153115&postcount=305 , for FirstAgeAngband.

Have inven_carry_num() return obj->number for any valid treasure type

---

src/main-cocoa.m

Check for isKeyWindow set to true on [event window] before processing mouse events.  That way the initial click in the main window when some other window has focus only changes focus and does not trigger any other actions.  Resolves https://github.com/angband/angband/issues/4782 .

Mac: be consistent with typical Mac behavior - require click to change focus

---

.github/workflows/linux.yaml
.github/workflows/windows.yaml

Hopefully, the transient failures avoided because the host system's package list is out-of-date with the package repository exceed the transient failures introduced because of the extra action invoked on the package repository.

Run 'apt-get update' before running 'apt-get install'

---

configure.ac
lib/user/Makefile
lib/user/archive/Makefile
lib/user/save/Makefile
lib/user/scores/Makefile
mk/buildsys.mk.in
mk/extra.mk.in
src/Makefile
src/datafile.c
src/datafile.h
src/h-basic.h
src/ui-game.c

Have it so "./autogen.sh; ./configure --with-setgid=games; make; sudo make install" is sufficient.  Most of the changes are only in the build system.  The exceptions are to remove the mention of SETGID in h-basic.h (since for a build using configure it's being set in autoconf.h) and to adjust the handling of the randart files to include grabbing/dropping privileges and incorporation of a per-user prefix when putting a file in a shared archive directory.
This indirectly resolves https://github.com/angband/angband/issues/3594 : in a shared system-wide install the proper directories will be created during installation so create_needed_dirs() will normally succeed without having to create anything (the exceptions would be if the installation is damaged or the names of the directories have …

Simplify shared system-wide installation

---

acinclude.m4
configure.ac

m4/buildsys.m4 triggers at least one other warning about obsolete autoconf stuff, but that's probably better dealt with as part of updating all the buildsys stuff to a later version.

Change acinclude.m4 and configure.ac to avoid obsolete macro warnings with Autoconf 2.70

---

src/main-sdl.c
src/main-win.c

Do so by refactoring Term_wipe_win() and Term_wipe_sdl().

For SDL and Windows, reduce number of graphics calls to clear big tiles

---

src/ui-knowledge.c
src/ui-output.c

1. In panel_should_modify(), modify_panel(), and textui_get_panel(), use dimensions that are consistent with verify_panel_int() and change_panel().
2. Do that as well for do_cmd_locate() but also impose a lower bound so there's no division by zero.  Since the panel dimensions are one half the displayed size, multiply by two when printing the panel coordinates to there's a change in the printed coordinates with each move.  Should resolve PowerWyrm's report, http://angband.oook.cz/forum/showpost.php?p=152675&postcount=43 , of tile size multipliers greater than 11 causing crashes in the locate command.

Make panel handling consistent for big tiles

---

autogen.sh

Do that because autoconf and automake on OpenBSD expect those environment variables to be set.  Allows someone to use the standard instructions for compiling from a cloned repository.  For someone doing packaging for OpenBSD, he or she can set AUTOCONF_VERSION and AUTOMAKE_VERSION before running autogen.sh to have tighter control over the results.

For autogen.sh on OpenBSD, set AUTOCONF_VERSION and AUTOMAKE_VERSION if not set

---

src/ui-display.c
src/ui-map.c
src/ui-output.c
src/ui-target.c

1. move_cursor_relative_map(), print_rel_map(), and prt_map_aux() treated those windows as if they were overhead views.  Instead have those functions be consistent with what display_map() generates.
2. Since those windows show a full (possibly compressed) view of the level, they don't need panel change logic.
3. When displaying the character in display_map(), get the terrain under the player for display as well (only has an effect when using a  graphics mode that supports blending the foreground with the terrain).
4. Adjust the dimensions calculations for display_map() when big tiles are used to avoid worrying about partial tiles on the right or bottom or loss of information when the level is small enough that it can be displayed without compression.
5. Drop the forced clearing of the …

Tweak handling of minimap (PW_MAP) subwindows

---

docs/hacking/compiling.rst

1. src/Makefile and src/tests/Makefile make use of GNU make features.  On systems where GNU make isn't the default, one likely has to use whatever will run GNU make rather than "make" after running ./configure.
2. Mention how to override ./configure's choice of the C compiler for cases where it chooses the wrong one.
3. Fix link to documentation about target triplets for cross-compilation.

Add notes in the compiling docs for some issues with ./configure

---

src/ui-output.c

Changes to big tile handling in ui-term.c and in the subwindows appear to have rendered it unnecessary.

Drop forced redraw_stuff() when big tiles are in use and there's a panel change

---

src/gen-cave.c
src/gen-room.c

Modify the tunneling code so they get the same treatment as other features internal to rooms (skipped over easily without modification).  Allows tunnels that start with vaults like the Maltese Cross (not marked as FEW_ENTRANCES, center is surrounded by permanent rock that requires diagonal moves to avoid) can make progress.

In vaults, automatically mark inner permanent walls with SQUARE_WALL_INNER

---

lib/gamedata/monster_spell.txt

Do that since the Pukel-man shape (and, in FirstAgeAngband, the green dragon shape) grant poison immunity,.  Use the same color scheme as is used for the four basic elements.  May resolve Chud's reported issue in https://github.com/angband/angband/issues/4189 (monster was a great swamp wyrm) and Mitze's reported issue in https://github.com/NickMcConnell/FirstAgeAngband/issues/163 (was lore entry for blacklock mages' poison ball) though it's not clear if the player had poison immunity in those cases.  Should not resolve Arralen's follow up to Mitze's report (priests don't have a poison attack).

Add lore-color-immune entry for monster's poison breaths, bolts, and balls

---

Makefile
configure.ac
m4/buildsys.m4
mk/buildsys.mk.in
mk/sinclude.mk.in

Keep the local modifications for installing DATA, CONFIG, and DOC and the post-install, pre-clean, and pre-distclean targets.  Did not adopt their renaming, PACKAGE to PACKAGE_NAME and VERSION to PACKAGE_VERSION.  Their subdirectory handling (as explicit dependencies using the directory names) didn't work in my hands so loop over all the directories (regardless of the directory timestamps) as before.

Merge in the current buildsys system, https://fossil.nil.im/buildsys

---

lib/gamedata/monster.txt
src/mon-lore.c
src/mon-make.c
src/mon-make.h

Resolves https://github.com/angband/angband/issues/4808 unless the monster lore should include details about the types of specific drops.
There's a bit of oddness with the interaction between specific drops and the the theft counts for uniques:  if someone steals a mushroom from Farmer Maggot, then he or she won't be able to kill Farmer Maggot and get a good item (other than mushrooms).  I figure that's not worth worrying about a resolution for that.

Change monster.txt's comments for specific drops; include count of them in monster lore

---

src/mon-make.c

There's no reported instances of that happening, but all current specified drops are for scrolls, books, or mushrooms.

Protect against artifact duplication in specified drops

---

.github/workflows/linux.yaml

Gets closer to covering what's desired in https://github.com/angband/angband/issues/3788 but implemented with Github's workflows rather than the buildbot.
As I see it, what's still missing is:
1. More extra warning flags in the build for the statistics front end.  Likely would want some option in the configure script to disable it's current disabling of -Wmissing-field-specifiers.  Also would likely want to change code so there's fewer warnings with the extra warning flags on.
2. Add workflows which exercise "make dist" (can what that produces be used to compile a working distribution), "make install", "make clean", and "make distclean".  Strictly speaking, those don't need to run with every push/pull request to the repository, just those that add, move, or remove files or that make a …

Add workflow checks to include SDL/SDL2 sound and statistics front end

---

.github/workflows/linux.yaml
configure.ac

Do it as an option (--enable-more-gcc-warnings) rather simply setting CFLAGS when calling configure so that it's easier to skip how the configure script adds -Wno-missing-field-initializers to the compiler options.
In the workflow output, the build with the extra warnings is "Statistics Build" in the Linux runs.  Also enabled sound and the test front end in that build to cover more of the code.

Add configure option for more compiler warnings; use that in one workflow

---

src/Makefile.osx

- Since compiling Objective-C uses both CFLAGS and OBJC_FLAGS, only need the minimum OS version in the former.
- Extend to set of default warning flags to be closer to what builds with configure use.
- Add $(EXE).o as a prerequisite for the tests rule so it works more reliably.
- Remove reference to the unused izzywizzy.

Tidy src/Makefile.osx

---

src/tests/parse/c-info.c

Once changed to match the current format, the equip0() test runs fine - no sign of the crash in lookup_sval() mentioned as the reason for disabling it.  Added some cleanup steps so enabling both that test and the magic0 test won't leak memory.

Enable the previously disabled equip0 and magic0 test cases for class.txt parsing

---

src/effects-info.c
src/effects.c
src/list-effects.h
src/tests/effects/chain.c
src/tests/effects/info.c
src/tests/effects/suite.mk

The issues are:
1. Handling of RANDOM/SELECT in a chain when the number of sub-effects is less than or equal to zero
2. Handling of RANDOM/SELECT in a chain when the number of sub-effects is more than what was actually supplied
3. Typo for one case in effect_get_menu_name()
4. Awkward name from effect_get_menu_name() for BOLT_STATUS_DAM effects
The tests added don't try to exhaust executing all the effect types.  They try to cover the execution of chains and then handling of effect_next(), effect_get_menu_name(), effect_damages(), effect_avg_damage(), and effect_projection().

Add tests for some aspects of effects; fix some issues the tests turned up

---

src/tests/parse/graphics.c
src/tests/parse/readstore.c

That ways there's less to wade through if one runs the tests under valgrind to look for potential issues.

Fix easily avoided leaks in the teardown for two test cases

---

src/tests/parse/a-info.c

It now has three separate lines for what once was on an "info" line.  The second of those new tests can't be run, like test_info0() could not, without enough initizlization so that lookup_kind() functions reasonably.

Split the test_info0() test case for artifact parsing into 3 to match artifact.txt's current format

---

src/init.c

That's a post 4.2.2 regression from the change to filter out starting equipment based on the birth options.

Plug memory leak from early return in parse_class_equip()

---

src/ui-options.c

Makes the local function, quality_menu() have the same prototype as textui_browse_object_knowledge().  With that, the action functions for the extra items have the same form and can use that form rather than an unspecified prototype.

Change prototype in ui-options.c to avoid warning with -Wstrict-prototypes

---

src/store.c

Add a private function that performs the tests (in addition to !store_is_staple()) for whether an object's stock should be reduced when sold.  For symmetry with the restocking process, also use that in store_find_kind() to screen possible matches.   Resolves this report, http://angband.oook.cz/forum/showpost.php?p=153716&postcount=110 , of dropping non-branded enchanted arrows in the general store and being able to buy them back while the store retained the same-sized stack.

Avoid sell/buy loop being able to reproduce magic arrows in the general store 

---

lib/gamedata/object.txt

Since it currently also influences the chance for safely recharging a wand or staff, an out-of-depth check for generating artifacts based on that kind, and the types of traps used on chests.

In object.txt, add to the comment about the level

---

src/target.c
src/target.h
src/ui-target.c

Addresses Sky's request here, http://angband.oook.cz/forum/showthread.php?t=10742 .  Doesn't address whether that can be applied in target_set_interactive():  since it's already refreshing the target list after a panel change it still limits the target list to the current panel.

Allow targeting the closest to pick up a target outside the current panel

---

src/tests/game/basic.c

That's to avoid memory leak warnings when run under valgrind.

In the game/basic test add cleanup before reloads and a call to wipe_mon_list() in the teardown

---

src/init.c
src/player-birth.c

1. Free ANGBAND_DIR_ARCHIVE in cleanup_angband().
2. Release cached player histories from the birth process when the character is accepted.

Add to the core game's cleanup to avoid valgrind warnings when running some test cases

---

lib/gamedata/dungeon_profile.txt
src/cave.c
src/cave.h
src/gen-cave.c
src/gen-room.c
src/gen-util.c
src/generate.c
src/generate.h

Also adjust the handling of Moria levels to match what's expected when using persistent levels.
Don't count staircase rooms when testing whether a greater vault or huge room is the first room on a level.  That way there's a chance those can be generated when using persistent levels and the level wasn't reach by a deep descent effect.

Allow classic, cavern, and lair levels when using persistent levels

---

src/main-stats.c

- The setup of the object_flags_list and object_mods_list tables was triggering "Couldn't prepare database!" failures at startup.
- The initialization of the player didn't set up the body triggering later assertions (in slot_by_name() called from the object power calculations).
- Skip already dead monsters in kill_all_monsters() to avoid crashes.
- After freeing the player history, set it to NULL to avoid double frees.
- Add cleanup for the cave to stats_cleanup_angband_run() so using more than one run doesn't trigger an assertion in prepare_next_level().
- Use list-origins.h so the table of origins is consistent with the rest of Angband.

Fix some runtime issues with statistics mode, main-stats.c

---

src/mon-make.c
src/mon-util.c

Or when they leave or enter the map. Currently this appears to be redundant with the addition of PU_MONSTERS to the update flags at the end of process_monsters() but could allow that to be removed while retaining correct behavior.  Because of that redundancy, I suspect it'll have no impact on the sporadic invisibility problem, https://github.com/NickMcConnell/FirstAgeAngband/issues/175 .

Add PU_MONSTERS to the player update flags when monsters with light move

---

src/project-feat.c

The disabling doesn't affect the line of sight so a full view updated isn't necessary, and the update to the map happens via a square_light_spot() call from square_disable_trap() or the functions it calls.

Remove flagging for full view update in the disable trap projection

---

docs/command.rst
docs/playing.rst

That follows up on the changes in https://github.com/angband/angband/commit/6e7f4e891aee60259187f5446e824f5642901eb8 .

Remove 'p' as a casting command in the documentation

---

docs/hacking/debug.rst
src/game-event.c
src/game-event.h
src/gen-cave.c
src/gen-room.c
src/generate.c
src/generate.h
src/wiz-stats.c
src/wizard.h

The game events are a partial step for implementing https://github.com/angband/angband/issues/2850 .  The design here is different than what magnate outlined in the comment there.  There isn't a single event signaling statistics versus normal mode; instead there's events that are always fired to signal start of level generation, completion of level generation, start of generating a room, completion of generating a room, and completion of a tunnel.
Add collection of statistics about cave generation using those events to the disconnection statistics debugging command, 'D', since it is already generating a bunch of levels at the same depth.  That might serve as a prototype for what cave generation data could be useful in main-stats.c.
Left main-stats.c as it is:  probably want to gain some …

Add game events for peeking into cave generation; use those to gather statistics with 'D' debugging

---

lib/gamedata/activation.txt

That aligns them with how the standard dragon scale mails are handled (i.e. the changes introduced in https://github.com/angband/angband/pull/4829 to resolve https://github.com/angband/angband/issues/3066 ).

Use SELECT rather than RANDOM for randart activations with multiple breath types

---

autogen.sh
configure.ac

That's to help avoid situations like this, http://angband.oook.cz/forum/showpost.php?p=154273&postcount=1 .
Also adjust a message from autogen.sh about OpenBSD so that it has the same "*info*" prefix as the other informational messages.

Add configure warning message if there's no player frontends enabled

---

src/cmd-wizard.c
src/gen-util.c
src/mon-make.c
src/mon-move.c
src/mon-summon.c
src/obj-pile.c

That's to handle the unlikely event (given that scatter() currently does up to 1000 tries internally) that all of scatter()'s attempts fail and the passed in value is never modified.
Also, adjust the logic for handling unrevealed mimics in push_object():  require an empty square for them rather than merely no player or monster.  Noticed that when checking the uses of scatter().

Always initialize second argument passed to scatter()

---

src/wiz-stats.c

- 50% of the time act as if came in via a down staircase.  The rest of the time is as before (i.e. like a word of recall).
- As a sanity check on the initial player position, count the number of times it isn't valid - i.e. either not a staircase when entered by a staircase and connected stairs are on or is not passable in all other cases.
The first lets the disconnection statistics exercise an aspect of the level generation it wasn't using before.  The second is to make the disconnection statistics more useful for diagnosing level generation problems.

Extend disconnection statistics

---

src/cmd-obj.c
src/cmd-wizard.c
src/gen-util.c
src/obj-curse.c
src/trap.c
src/ui-game.c

For two instances where the strings are internally sourced but variable, also process them through "%s" so they won't raise false alarms about security issues.
Related to https://github.com/angband/angband/issues/2950 .
Remove two unnecessary calls to format() that turned when auditing the calls to msg() and msgt().

Fix instances of potential format string security holes with msg() and msgt()

---

lib/gamedata/artifact.txt
lib/gamedata/class.txt
lib/gamedata/monster.txt
lib/gamedata/object.txt
lib/gamedata/player_property.txt
lib/gamedata/terrain.txt

I noticed a monster entry with 3 spaces after a period, and when I went to fix it, I found a couple instances.
Angband has a pretty strong convention of using 2 spaces after periods, so I checked on 1 space and found a handful of those.
Description lines are joined directly, so need spaces at the end of previous lines, or the beginning of new lines. End-of-line spaces are poor form in software projects, so I converted end-of-life spaces to beginning-of-next-line spaces, which was the more common convention anyway. A few instances of 1 or 3 spaces were hidden across line breaks, so these were fixed as well.
The 'desc' field description in monster.txt said some processing was done on description lines when joining, but that appears to no longer be the case so I updated the help text to …

Fix knowledge spacing after periods

---

src/effects-info.c
src/mon-lore.c
src/obj-info.c
src/ui-command.c

- Pass some internal strings through "%s" anyways when formatting to avoid raising false alarms about format string security and, for effect or origin descriptions that are expected to take no arguments, provide a bit of protection against programmer mistakes.
- Skip some calls to format() and let textblock_append_c() handle the formatting.

Make changes prompted by auditing strnfmt/textblock_append/file_putf

---

src/list-mon-message.h
src/mon-move.c
src/mon-msg.c
src/mon-util.c
src/player-attack.c
src/project-mon.c

These are an attempt to resolve #4902 .  The changes are essentially these things:
- When a camouflaged monster that's in view stops a projection, become aware of the camouflaged monster.
- Call update_mon() from become_aware() for revealed mimics since the mimicry influences visibility.
- Use monster_is_obvious() rather than monster_is_visible() in some places (deciding whether to flag a monster message as from an invisible source and within the handling of player missile or thrown attacks) since using monster_is_visible() with an unlit and unrevealed mimic whose mimicked object has a known position can lead to messages that reveal the mimics identity.
- When checking for whether the position of a monster is visible in project_m(), use monster_is_in_view() for unrevealed mimics rather …

Change handling of projections with unrevealed mimics

---

lib/gamedata/blow_effects.txt
src/mon-attack.c
src/mon-attack.h
src/mon-lore.c
src/mon-spell.c
src/mon-timed.c
src/mon-timed.h
src/player-attack.c
src/player-attack.h
src/tests/monster/attack.c
src/trap.c
src/trap.h
src/z-rand.c
src/z-rand.h

I want to suggest displaying life rating before armor rating in monster recall:
* Life rating is more important because it's always applicable, while armor rating is only applicable to non-magic attacks.
* Armor rating and the player's hit chance are closely related, so I'd like them to be next to each other.
* Using a % sign is consistent with the style later on, and makes it easier to pick out the hit rate when scanning.
Unfortunately, I noticed the duplication of to-hit logic used in mon-lore.c, so the majority of this work is to refactor that. My goal was to eliminate duplication and improve clarity without changing mechanics. To that end:
* I added a `random_chance` struct to represent chances and can be used to roll or just report out.
* I added a set of `chance_of_*_hit` functions …

Refactor hit chance calculation, and swap armor/life rating in recall

---

src/mon-attack.c
src/mon-spell.c

They're only currently used in one file.  Suppresses warning messages from -Wmissing-prototypes.

Declare three recently added functions static

---

src/target.c
src/ui-event.c
src/ui-event.h
src/ui-target.c
src/ui-target.h

Adds the ignore item command to the look/target menu.
* Ignore item can only be used when looking, not when targeting (TARGET_KILL)
* Items deep in a pile can be ignored but it's not very convenient: look, select the pile, recall details, select the item letter, esc once, ignore.
* Ignore item accepts both original and roguelike keys, but the help only describes the current keyset in use:
The target_set_interactive_aux() tracks monsters and objects as you move the cursor around, so the most recently tracked object is what gets ignored.
Of course, I had to refactor the entire `target_set_interactive()` function to figure out what was going on. I tried to keep all the existing functionality while restructuring the code to be more readable. This code is used for "look" (look mode) and …

Allow ignore while looking (close #3326)

---

src/Makefile.msys2.sdl2
src/effects-info.c
src/h-basic.h
src/main-sdl2.c

So far, Makefile.msys2.sdl2 has been the path of least resistance for me (developing with MSYS2 on Windows). I had to add -ldeflate to get it to work, and it's missing adequate warning coverage. There's also a few warnings in the front-end that can be squashed.
Contains a bonus uninitialized warning fix in effects-info.c.

Fix sdl2 warnings

---

src/gen-cave.c

A player could see that it was present by digging out one layer of wall around the town, waiting till dark, and then firing off a light area effect while on or adjacent to a former wall to see all the former walls light up.

For town generation, also clear room flag on the walls

---

src/effects.c
src/obj-tval.c
src/obj-tval.h

Remove the following static (local) redundant item testers from **effects.c**:
* `item_tester_hook_weapon`
* `item_tester_hook_armour`
* `item_tester_hook_recharge`
* `item_tester_hook_staff`
* `item_tester_hook_ammo`
* `item_tester_hook_bolt` (technically not redundant since I had to add `tval_is_bolt`)
I would like to reduce the almost 6000 line effects.c file size to a reasonable level (< 5000 at least). I ran some stats on the file:
* There are 136 functions
* The function sizes range between 6-285 lines. Only 8 functions are above 100 lines. Average function size is ~42 lines
* The majority of functions (80%) are effect_handlers, and the rest are helpers
I think the solution would be to break the file up into multiple parts. Based on the distribution of effect handlers, I think …

Remove redundant item testers

---

src/effects.c
src/project-mon.c

Banish and mass banish would strand the player in the arena.  While those would be one way to trigger #4249 , they don't explain the most recent report of that happening since the monster was the Witch King of Angmar.
Also disable polymorph in the arena.  It wouldn't leave the player stranded after killing the polymorphed monster, but, upon returning to the original cave, the original target of single combat would still be there.  I made one attempt to avoid that (using monster_index_move() so the polymorphed monster would keep the same ID in an arena level), but that didn't help.

Don't allow banish, mass banish, or polymorph in a single combat arena

---

src/load.c

Resolves one way to trigger https://github.com/angband/angband/issues/4249 : use Single Combat on a level, save while in single combat, kill the arena monster, use Single Combat again on the level, kill the arena monster, and get stuck in the arena.

Recompute depth by name lookup when loading chunk list for nonpersistent levels

---

src/mon-util.c

Barring bugs, the only way nonplayer hits should happen in an arena is with damaging terrain.  That seems highly  unlikely (player abilities aren't strong enough to convert a floor to lava; monsters that can do so are likely immune to lava), but, just in case, don't allow them to kill an arena monster and strand the player in the arena (i.e. trigger #4249 .

Don't allow nonplayer hits to kill an arena monster

---

.github/workflows/release.yaml

Does so by not compiling with debugging symbols.  This needs testing on proper Windows systems; I only exercised it by running the executable with Wine on Debian buster.  A zip file for Windows generated by the modified release workflow can be found here, https://github.com/backwardsEric/angband/releases/download/4.2.2-237-g50f26f22/Angband-4.2.2-237-g50f26f22-win.zip .
This is an attempt to resolve #4634 .  In my hands, I couldn't get a further reduction in size by removing the -static flag added for Windows builds by configure.ac or by also including -s (strip symbols and relocation information) or -Os (optimize for size) in the compiler options.  While the executable size does decrease substantially with this change (now around 2 MB), the impact on the size of the zip file is much more …

Build a smaller Windows executable in the release workflow

---

src/z-bitflag.c
src/z-bitflag.h

This matches `assert()` behaviour.

Disable all debug checks in z-bitflag.c if NDEBUG is defined

---

src/main-cocoa.m

It's never set to true and appears to be vestigial.

MacOS:  remove handling of open_when_ready

---

src/gen-cave.c

Resolves https://github.com/angband/angband/issues/4942 (part of https://github.com/angband/angband/issues/4934 ).

Add argument to modified_chunk() and moria_chunk() to avoid using the player global

---

src/cmd-cave.c
src/mon-attack.c
src/mon-move.c
src/mon-util.c
src/mon-util.h
src/project-mon.c
src/project-obj.c

The chunk argument is to avoid cases where the caller took a chunk argument but become_aware used the cave global.  Resolves https://github.com/angband/angband/issues/4944 part of https://github.com/angband/angband/issues/4934 .

Add a chunk and player argument to become_aware()

---

src/cave-view.c
src/cave.h
src/cmd-cave.c
src/obj-chest.c
src/player-util.c
src/ui-display.c

That way it doesn't need to access the global. Resolves https://github.com/angband/angband/issues/4950 (part of https://github.com/angband/angband/issues/4934 ).

Add a player argument to no_light()

---

src/main-cocoa.m

Use bool/true/false for data interchanged with Angband's core and BOOL/YES/NO for stuff that's only touched by the Objective C code.  Remove use of Boolean/TRUE/FALSE (historical Mac usage).

MacOS:  rationalize handling of Booleans

---

.github/workflows/release.yaml
configure.ac
src/cmd-obj.c
src/main-cocoa.m
src/ui-entry.c

Currently, it only add -DNDEBUG to CFLAGS.
Clean up some warnings when the code is compiled with -DNDEBUG.  Change the one case I saw where what's in the assert() had side effects (in use_aux(); though with all the callers of that as they are, throwing away the side effect when compiled with NDEBUG doesn't matter).
Change release.yaml to use the configure option for a release build when building for Windows.  For MacOS, override OPT when running Makefile.osx to set -DNDEBUG.
This is one way to resolve #4948 .

Add an option to configure for making a release build

---

acinclude.m4
configure.ac

- Use AS_HELP_STRING() in more places.
- Use lower case for the first letter and an imperative form (i.e. "enable" rather than "enables") in the explanation.

configure:  make "configure --help" prettier 

---

src/gen-cave.c
src/gen-chunk.c
src/gen-monster.c
src/gen-room.c
src/generate.c
src/generate.h
src/mon-make.c
src/mon-make.h
src/mon-summon.c
src/mon-util.c
src/project-mon.c

- In the monster creation and placement functions that already take a chunk, use the chunk's depth rather than the player's as the current depth.
- Add an argument for the current depth to get_mon_num() and mon_restrict().  Replace the player argument to chunk_find_adjacent() with the depth.
- Cache whether persistent levels are being used in the dun_data structure so room generation doesn't have to look at the player.
- Add a player argument to chunk_copy() so the cave generation can pass along their player argument if the player position needs to be updated.
Resolves #4956 and some parts of some of the other items in #4934 .  The remaining references to the global player from cave generation are primarily through object creation and destruction (make_artifact_special(), make_artifact(), …

Refactor cave and monster generation to reduce the dependencies on the player global

---

src/cave-view.c
src/mon-util.c

Since become_aware() directly calls update_mon(), there's no need to set PU_MONSTERS, unless the revealed monster affects lighting.  Since the revealed/unrevealed status doesn't affect the view calculations, also only set PU_UPDATE_VIEW if the revealed monster affects lighting.
As a bit of future- or variant-proofing, don't include a monster as a light source in the lighting calculations if it is camouflaged:  having it light its surroundings would likely spoil the point of the camouflage.

Tighten updates in become_aware(); hide camouflaged monsters in lighting calculations

---

src/mon-attack.c
src/mon-move.c
src/mon-util.c
src/player-attack.c
src/project.c
src/project.h
src/ui-target.c

One of its callers, projectable(), already expects a chunk argument.  Resolves https://github.com/angband/angband/issues/4964 (part of https://github.com/angband/angband/issues/4934 ).

Add a chunk argument to project_path()

---

src/effects.c
src/main-stats.c
src/mon-util.c
src/mon-util.h
src/player-attack.c
src/player-quest.c
src/player-quest.h
src/project-mon.c

Some of its callers already expect a player argument.  Resolves https://github.com/angband/angband/issues/4966 (part of https://github.com/angband/angband/issues/4934 ).  Since mon_take_hit() calls monster_death() and, in turn, quest_check(), add a player argument to those as well.

Add a player argument to mon_take_hit()

---

src/ui-target.c

That makes it possible to use 'k' to move north in the rogue-like keyset.  Resolves https://github.com/angband/angband/issues/4973 .

Tighten check for ignore key when targeting

---

src/gen-cave.c
src/gen-util.c
src/generate.h

With that change and #4730 (which would prevent the two reported instances of failures - both were Moria levels with a single room), it may be best to mark #4549 as resolved.

Add a return value to new_player_spot(); restart dungeon generation when it fails

---

src/gen-cave.c

That way, the included vault gets similar treatment to the rooms on classic, modified, or moria levels.

For hard centre levels, trigger the EVENT_GEN_ROOM_START and EVENT_GEN_ROOM_END events

---

src/load.c
src/obj-gear.c
src/obj-gear.h
src/obj-ignore.c
src/player-calcs.c
src/player-calcs.h
src/tests/player/calc-inventory.c
src/tests/player/inven-carry-num.c
src/tests/player/inven-wield.c

The change to gear_insert_end() resolves https://github.com/angband/angband/issues/4982 (part of https://github.com/angband/angband/issues/4934 ).  The change to gear_last_item() is so its prototype is analogous to gear_insert_end()'s.
Since calc_inventory() takes pieces of the player structure as arguments while still accessing the player global (including for what it would have to do to accommodate the change to gear_insert_end()'s prototype), have it take the entire player structure instead.  That makes the update_inventory() helper for update_stuff() superfluous so remove it, resolving https://github.com/angband/angband/issues/4981 (also part of #4934 ).  There was a comment in load.c about the possibility of working with copies of the upkeep and body; that would be harder with the …

Add a player arg to gear_insert_end() and gear_last_item(); change calc_inventory()'s arguments

---

configure.ac

That way, switching back and forth between release or a non-release build will trigger a full rebuild when make is run.  It also avoids the potential for missing flag_has_dbg or flag_on_dbg symbols:  configure with --enable-release, make, configure without --enable-release, change a source file that includes z-bitflag.h but not something that would otherwise trigger rebuilding z-bitflag.c, then run make and get linker errors.

configure:  with --enable-release also define a preprocessor directive in autoconf.h

---

src/mon-util.c

Resolves https://github.com/angband/angband/issues/4988 .

Prevent monster death message from a missile from being garbled

---

src/ui-input.c

Use the prompt early in case future changes to how EVENT_MESSAGE_FLUSH is handled invoke format() as a side effect.

Make textui_get_check() safer to use with a prompt constructed by format()

---

src/obj-info.c
src/obj-slays.c
src/obj-slays.h
src/player-attack.c

For convenience, there's one new function for melee attacks (learn_brand_slay_from_melee()), one for ranged attacks with a launcher (learn_brand_slay_from_launch()), and one for thrown attacks (learn_brand_slay_from_throw()).  Keep the declarations and implementations for those in obj-slays.{h,c} since they combine both object and monster learning and so aren't a natural fit for obj-knowledge.{h,c} or mon-lore.{h,c}.  Resolves https://github.com/angband/angband/issues/3668 .
Add a player argument to improve_attack_modifier(), player_has_temporary_brand(), and player_has_temporary_slay().  Add a Boolean argument to get_monster_brand_multiplier() to flag whether or not O-combat is desired.  Those changes resolve https://github.com/angband/angband/issues/4993 , …

Split off the learning and lore part from improve_attack_modifier(); add argument

---

src/player-calcs.c
src/tests/player/calc-inventory.c

Might plug the problem reported by wobbly here, http://angband.oook.cz/forum/showpost.php?p=153369&postcount=4 , which was after the last round of changes to the quiver handling.

When assigning inscribed items to the quiver, skip equipped items

---

src/player-calcs.c

Use an O(number in gear) algorithm rather than an O(number in gear * number of quiver slots) one for the placement of inscribed items in the quiver.
Use a temporary array to track what items in the gear have been dealt with to reduce calls to object_is_equipped() and avoid iteration over the newly assigned quiver and pack.
On an early 2015 MacBook Pro (2.7 GHz dual core I5) running macOS 11.5.1 and Angband compiled with "-g -O2 -DNDEBUG", reduces the time (tracked by a compute time profile using the Time Profiler from Instruments) for one million calls to calc_inventory() in a tight loop with a gear list of 24 items (9 equipped; 3 for the quiver) from 17.59 seconds to 5.4 seconds.

Make calc_inventory() more efficient

---

src/obj-gear.c
src/obj-knowledge.c
src/obj-knowledge.h
src/player-birth.c
src/player-util.c
src/store.c

Many of its callers already expect such an argument.  Resolves https://github.com/angband/angband/issues/5010 (part of https://github.com/angband/angband/issues/4934 ).

Add a player argument to object_flavor_aware

---

src/cave-square.c
src/cave.h
src/cmd-cave.c
src/effect-handler-general.c
src/game-world.c
src/gen-cave.c
src/gen-room.c
src/gen-util.c
src/generate.c
src/generate.h
src/player-quest.c
src/player-quest.h
src/player-util.c
src/player-util.h
src/trap.c

Remove duplicated declaration of is_quest() from cave.h leaving the declaration in player-quest.h.  Add a Boolean argument to place_random_stairs() and alloc_stairs() to indicate whether this is a quest level or not.  Cache the result of is_quest() in the dun_data structure for cave generation.
In the cave profile selection for quest levels, simply use classic levels since those are now allowed when persistent levels are used.  That also simplifies the logic in labyrinth_check() a bit.
Resolves https://github.com/angband/angband/issues/5027 .  Resolves https://github.com/angband/angband/issues/5028.  Both are part of https://github.com/angband/angband/issues/4934 :  places where callers take a struct chunk or struct player but end up calling functions that use the cave or player globals.

Add a player argument to is_quest() and dungeon_get_next_level()

---

src/cave-view.c

That way it can use the argument passed to update_view() rather than the player global.  Related to https://github.com/angband/angband/issues/4934 though the list there missed this use of the player global.

Change the prototype of cave-view.c's update_one()

---

src/cave-map.c
src/cmd-cave.c
src/cmd-pickup.c
src/effect-handler-general.c
src/mon-move.c
src/mon-util.c
src/obj-chest.c
src/obj-chest.h
src/obj-desc.c
src/obj-ignore.c
src/obj-ignore.h
src/obj-list.c
src/obj-pile.c
src/player-path.c
src/player-util.c
src/project-obj.c
src/target.c
src/ui-context.c
src/ui-equip-cmp.c

Some of its callers already expected such an argument.  Add player argument to ignore_known_item_ok() for consistency with that.  Rather than add an argument or make use of the player global in is_trapped_chest() or is_locked_chest() since those functions make use of ignore_item_ok(), remove those calls and have the callers is_trapped_chest or is_locked_chest() check for ignored objects (some already were making that check).  Add a player argument to chest_check() since it calls ignore_item_ok().
Resolves https://github.com/angband/angband/issues/5037 (part of https://github.com/angband/angband/issues/4934 ).

Add player argument to ignore_item_ok()

---

src/obj-gear.c

It's called by gear_object_for_use() which also expects a player argument.  That's related to resolving https://github.com/angband/angband/issues/4934 .

Add a player argument to gear_excise_object()

---

src/cmd-pickup.c
src/obj-gear.c
src/obj-gear.h
src/store.c
src/tests/player/inven-carry-num.c
src/ui-store.c

Resolves https://github.com/angband/angband/issues/5042 as much as is possible now:  inven_carry_okay() is used as an item_tester so its prototype is unchanged.  Mark the struct player* argument to pack_slots_used() as const so the player argument to inven_carry_num() can be const as well.

Add a player argument to inven_carry_num()

---

src/player-util.c

Resolves https://github.com/angband/angband/issues/5045 (part of https://github.com/angband/angband/issues/4934 ).  Does change the behavior:  camouflaged monsters will not be subject to the random attack.

Change player_attack_random_monster() to call py_attack() directly

---

src/obj-pile.c

By itself, that does not affect the inventory or bonuses.

Don't set player upkeep flags when using an item from the floor

---

src/main-gcu.c

Do that since, in principle, it could be modified.  Avoids a compiler warning when compiled with -Wwrite-strings.  Use setenv() rather than putenv() when possible.

In main-gcu.c, pass a writeable static buffer to putenv()

---

src/player-calcs.c

1) Fix paranoia checks that used quiver_size rather than quiver_slot_size.
2) Remove extraneous word in a comment.

Tidy calc_inventory() a bit

---

src/effects.c

Resolves https://github.com/angband/angband/issues/5068 .

Allow object identification in the case of rejecting the choice for a select effect

---

src/nds/nds-buttons.c
src/nds/nds-screenkeys.c

This conveniently handles all types of line endings.

nds: Use file_* functions for configuration files

---

src/game-event.c
src/game-event.h
src/player-birth.c
src/ui-birth.c
src/ui-input.c
src/ui-input.h
src/ui-menu.c
src/ui-menu.h
src/ui-options.c

Since the whole process can be completed (using a random or empty name) with just the mouse, that may be sufficient to resolve https://github.com/angband/angband/issues/2519 .
To have enough information to know whether a stat buy is possible, there's a change to the data associated with EVENT_BIRTHPOINTS and the prototype for event_signal_birthpoints().
Most of the interactions with the mouse are handled via context menus, and nothing was added to what's displayed to indicate where to click.  For the class, race, and roller selection screens, clicking on the hint or the line below it brings up the context menu.  For the birth options screen, clicking on the menu label brings up the context menu.  In the other cases (stat allocation or rolling and name selection) clicking on nearly any …

Make the mouse more useful during the birth process

---

src/cmd-cave.c
src/project-feat.c

- Make more robust against failures in place_object().  At least in current Vanilla, though, didn't see how place_object() could fail since the newly cleared spot will satisfy square_isobjectholding() as far as I know.  Resolves #5086 .
- When the rubble is cleared with stone-to-mud, use the same logic as is used when digging.

Tidy logic for message about revealed object when rubble cleared

---

src/obj-pile.c

Preserve records of drops from a unique when origin_race for the other object is NULL.  When origin_race is not set for either object, mark as mixed if origin or origin_depth differ (that restores the behavior of ~7 years ago for that case).  At least when tested with Angband, did not introduce a regression with the case described in https://github.com/NickMcConnell/FAangband/issues/289 .

Refine combining origins

---

src/main-cocoa.m

Resolves https://github.com/angband/angband/issues/3174 (other front ends use the default get_file() which already provides feedback to the user about the full path).

Mac:  provide feedback about full path selected with get_file()

---

src/tests/test-utils.c

Without the change, this
```
./autogen.sh
./configure --enable-sdl2 --with-no-install
make tests
```
was failing when it tried to link the first test case (no symbol found to satisfy the reference to init_sound_sdl() in angband.o).

Allow test cases to link properly if SDL2 sound was enabled

---

src/obj-init.c
src/tests/parse/a-info.c

Should resolve Ugramoth's report here, http://angband.oook.cz/forum/showpost.php?p=155613&postcount=105 , of the Arkenstone at the bottom of the object list.  That's part of resolving #4664 .
As a preparatory step, set up kind lookup for the artifact parsing tests so more of the tests can be run.

Also set kind's cost for special artifacts

---

lib/gamedata/artifact.txt
lib/gamedata/ego_item.txt
lib/gamedata/object.txt

That's mostly for how serial numbers are no longer used in artifact.txt, the splitting off of brands and slays from the values line, and addition of the curse line.
Related to https://github.com/angband/angband/issues/3522 .

Update comments in artifact.txt, ego_item.txt and object.txt

---

.github/workflows/release.yaml
.github/workflows/windows.yaml
configure.ac
docs/hacking/compiling.rst

Adjust the GitHub workflow scripts (dropping --disable-curses for Windows builds) and compiling documentation to match that change.

configure script:  with --enable-win don't try, by default, to build curses/X11/spoiler front ends

---

src/player-birth.c

Avoids a potential source of variation when generating artifact spoilers with the spoiler front end.

In player_make_simple(), use default point buy rather than rolling for stats

---

src/tests/parse/a-info.c

Was introduced by recent change.  For Vanilla, only affects total memory usage since the size used was larger than necessary.

Fix allocation size in artifact parsing test

---

src/main-gcu.c

Regression was introduced by https://github.com/angband/angband/pull/5094 (post 4.2.3).

GCU: fix regression that prevented player's color table from taking effect

---

src/main-cocoa.m
src/main-sdl.c
src/main-sdl2.c
src/main-x11.c

For the X11, SDL, and SDL2 front ends also reset background/clearing color in response to TERM_XTRA_REACT.
For the Mac front end, use angband_color_table[COLOUR_DARK] rather than RGB(0, 0, 0) when clearing.
Related to resolving #5132 .

More consistent background handling for X11, SDL, SDL2, and Mac

---

src/ui-prefs.c

That's more general than the previous fix (dumping color zero even if it has all zero components) and better handles dumping a color table where the user swapped the color zero entry for one of the other basic colors.

Allow dumping a color with all zero components if in the basic colors

---

src/main-nds.c
src/nds/nds-draw.c
src/nds/nds-draw.h
src/nds/nds-font-3x8.c
src/nds/nds-font-5x8.c
src/nds/nds-keyboard.c
src/nds/nds-screenkeys.c

Keyboard, on-screen keys and logging functions have been left with a white-on-black color combination deliberately.

nds: Support custom foreground and background colors

---

src/init.c

Removes a warning from the Visual Studio compiler.

Avoid unnecessary wchar_t to char conversion for trap's glyph

---

configure.ac

This is helpful when cross-compiling or when choosing an SDL prefix that is not in the default path.

Actually use the sdl-config binary that we found when configuring

---

lib/user/Makefile
lib/user/panic/Makefile
src/init.c
src/init.h
src/main-win.c
src/main.c
src/savefile.c
src/savefile.h
src/ui-game.c
src/ui-game.h
src/ui-signals.c

Resolves https://github.com/angband/angband/issues/2162 .
To avoid name clashes or limits on the length of the file name portion, uses a separate, parallel, directory for the panic saves.  Because of that, there's an extra ANGBAND_DIR_PANIC global and related stuff to initialize it and create it.
When loading a save file, looks to see if there is a panic save with the same name which is newer.  If there is, prompts the player for whether the panic save should be used.  If the player opts not to use the panic save, the ordinary save will be used.
Could use some testing on Windows.  I only tried the Windows front end using Linux with Wine.  With that, Wine caught the abort signal I sent to Angband to induce the panic save, and Angband's signal handler wasn't invoked.

Don't overwrite a normal save with a panic save

---

docs/playing.rst
lib/help/commands.txt

Resolves https://github.com/angband/angband/issues/5155 .
"Inspect" rather than "Observe" as suggested by tangar.  "Kill" rather than "End" for the suicide command.  Prefer descriptions that have the form "verb + something".  Match the command table in playing.rst to commands.txt.  Use the "as literal" markup in playing.rst for the keys in rogue-like command table as is done in the original command table (exception is "`" in both).

Adjust brief description for commands

---

docs/thanks.rst
docs/version.rst

The second one is a workaround for what appears to be a bug somewhere in the restructured text parsing (line in version.rst triggers an "undecidable source character" warning while the same line in thanks.rst does not).

docs:  fix two places referencing Timo Pietilä

---

src/store.c

When using the statistics front end, avoids the pile integrity checks for the stores taking up an increasing portion of the run time as the run number increases.

Also reset the known pile in store_reset().

---

src/ui-game.c

Primarily, that's to avoid the possibility of running out of stack space with repeated use of the start again option.  Also simplifies the call stack, though that may be a drawback rather than a feature:  can no longer know that the play again feature was used by merely looking at the backtrace.

Iterate, rather than recurse, when playing again in play_game().

---

src/obj-pile.c

Only affects artifact drops.  Encountered the out-of-bounds access once during a long statistics run (5000 trials); search started at (160,4) and ended with a crash at (165,-1)

Constrain search in drop_find_grid() to avoid out-of-bounds access.

---

configure.ac

In particular, allows compiling the SDL2 front end on OpenBSD without overriding the default compiler (the old behavior chose gcc which couldn't find a header included by the SDL2 headers).
On Debian Bullseye with the gcc package installed, the change appears to have no effect (/usr/bin/cc points to /etc/alternatives/cc which points to /usr/bin/gcc).  Similarly, there's no effect on macOS 11.6.1 with Xcode:  cc and gcc both end up invoking clang.

configure:  prefer cc to gcc for better compatibility with OpenBSD and FreeBSD

---

src/main-sdl2.c

SDL 2.0.18 adds a new feature that helps handling games rendering slowly when using high frequency mice that generate events too fast https://github.com/libsdl-org/SDL/pull/4794
I think that this feature is not relevant to angband, and leaving it enabled breaks the menu.

SDL 2.0.18 fix: Disable POLL_SENTINEL Event

---

src/main-sdl2.c

I tried to compile angband on Fedora 35 and found a problem with the menu, I can navigate through it, but I can't click on the buttons (similar to the #4762 issue), this happens to me while using X11 and Wayland. 
I tried to debug the problem and noticed that whenever I made a mouse click, the app receives a SDL_KEYMAPCHANGED event before the SDL_MOUSEBUTTONDOWN event, breaking the menu loop before it can handle the mouse click event. I don't know if this is an SDL problem, a Gnome problem, an expected behavior or a problem with my computer configuration, but since the game is not actually doing anything to handle those events, I made a patch to disable them.

Disable KEYMAPCHANGED event handling

---

src/obj-pile.c

Avoids use after free detected by address sanitation in the destruction and earthquake tests.

Clear links when orphaning an object

---

src/win/vs2019/Angband.vcxproj
src/win/vs2019/Angband.vcxproj.filters

Missed that in the "centered dot for SDL2" commit.

Visual Studio: include lib/customize/font-sdl2.prf in the list of files

---

src/ui-game.c

Fixes regression introduced by #5156 : the Mac front end prompts for using a panic save if the player selects File->New from the menu.

Protect against empty name when checking for panic save

---

src/cmd-obj.c
src/player-attack.c

One is per PowerWyrm's suggestion, http://angband.oook.cz/forum/showthread.php?t=10997 :  confirm unsafe casting before asking for a spell's target.
The others are similar situations with other commands.  Because of the enforcement of prerequisites by the textui interface, most of these won't affect what the player sees.
- In do_cmd_fire(), check the objects involved before targeting.
- When dropping, check for dropping a sticky equipped item before prompting for the quantity to drop (though, since equipped items are currently only in stacks of one item, there is no quantity prompt anyways in that case).
- Check light source before prompting for the stack to use when refueling.
- Check for whether studying is at all possible before prompting for the book to use in do_cmd_study_book().

Reorder checks/confirmations so they happen before additional prompts to the player

---

docs/hacking/compiling.rst
docs/hacking/debug.rst

Namely, add  a bit more about the 'S' and 'D' debugging commands and details about how to compile with statistics support.  Related to #4241 .

Documentation:  add notes about statistics

---

configure.ac
lib/gamedata/Makefile
mk/extra.mk.in
src/init.c

Considering [this conversation](http://angband.oook.cz/forum/showthread.php?t=10995), I thought it would convenient to add this option.
When enabled, it installs the gamedata folder in the libpath instead of the configpath.

Add configure option to store gamedata on libpath

---

lib/user/scores/Makefile
src/score.c

I don't see the convenience of including this empty file on instalation since the code actually checks if it exists and always creates a new one.
Also changed the return value of highscore_read when the file doesn't exist since it's not consistent with the function definition. It's also not used in the codebase.

Remove empty score file

---

.gitignore
src/Makefile
src/buildid.c
src/buildid.h
src/main-cocoa.m
src/main-sdl.c
src/main-test.c

That finishes off the current places where GNU Make was assumed.  The change here to generate version.h with the build number doesn't work cleanly on OpenBSD with the default make:  it always rebuilds buildid.o and relinks angband even though the timestamp on version.h didn't change.  On Linux with GNU Make, it does work as expected:  buildid.o is only rebuilt when version.h changes, and that happens when version.h doesn't exist or the output from scripts/version.sh changes.

Change how src/Makefile deals with the build ID to avoid requiring GNU Make

---

src/Makefile
src/Makefile.osx
src/tests/Makefile
src/tests/Makefile.inc

Can be invoked by the test-depgen rule in src/Makefile or src/Makefile.osx.
Did that since, after locally building the tests, the ones using player.h didn't automatically rebuild when that header changed.  Because the change affected the layout of struct player, saw test failures that would go away after running test-clean and then rebuilding the tests.

Add dependency generation for the tests cases modeled on that in src/Makefile.inc

---

src/main-test.c

Without the change, if the user running the test front end has a savefile matching what main.c selects, the birth/new-game-0 or birth/new-game-1 tests will fail if the character's race and class combination from the save file doesn't happen to match what the test checks for (those tests assume the first key press brings the game to the new character selection screen; with a savefile, the first key press either brings the game to the dungeon level the character is on or to the quick restart screen).

In test front end, reset savefile set in main.c so it doesn't interfere with the test

---

lib/user/archive/Makefile
src/main.c

- Make the archive directory readable by owner and others.  That's to allow the indexing in file_archive() to work (currently unused; all current callers pass an append string) with setgid installations.
- For main.c's option to change paths, allow all paths in setgid installations to be changed except those that require privilege changes to access (save, scores, archive, and panic).
- Fix main.c's -l option to work better with setgid installations.

Tweak some things for setgid installations

---

src/main-spoil.c
src/ui-knowledge.c
src/ui-player.c

To do that:
1. Include the seed in the character dump if randarts are used.
2. Extend the spoiler front end so it can accept a seed value as a way of specifying a randart set.  Processing the seed will have the side effect of generating the randart file and log.

Facilitate sharing randart sets by the seed value

---

src/mon-util.c

(This might be more a matter of a difference in vision for this mechanic that may or may not be in line with the project; feel free to close this if so.)
I found that it is more intuitive that if I try to steal from a monster with a full inventory, that rather than creating an overflow and automatically dropping something from my inventory, that I instead drop the item I tried to steal and then figure out which item from my inventory I'd like to drop to pick the stolen item back up, if the item is still worth taking.
For example, in my save, I stole a low-value item from a monster on a full inventory, which overflowed and made me drop one of my artifacts to pick up the stolen item. Since stealing can consume a turn, that also could have been a turn where a nearby monster breathes fire or …

Drop stolen items nearby instead of forcing inventory overflow for full players

---

src/obj-chest.c

Detected by the address sanitizer.

Prevent use of an unitialized variable when firing off a chest trap

---

src/player-path.c

Rearrange tests to avoid out-of-bounds index in path_dist()

---

src/effect-handler-general.c
src/list-mon-message.h
src/mon-attack.c

1. Avoid ordering problem mentioned in the comments on #2798 .
2. Account for visibility.
3. In the teleport handler, make the "no target squares" message depend on the context.
In regards to (2), this change won't generate a message in the out-of-sight case.  Should it (at least in the monster versus player scenario)?

Improve "puff of smake" messaging

---

lib/gamedata/monster.txt
src/mon-init.c
src/mon-spell.c
src/monster.h
src/tests/parse/r-info.c

Do so for some races, mostly jellies and quylthulgs.  Blink dogs, phase spiders, crows of Durthang (if those are like the ravens of the Hobbit and capable of speech, then that change may not be good), wolf chieftains, serpents of the brownlands, and serpents of chaos all have some customizations.
Did not supply any for magic mushrooms and will o' the wisps:  both are good candidates for custom messages, but I didn't know what would be appropriate.  Some others that might need customization are other spiders, golems (can iron golems, colbrans, or pukelmen speak?), elementals, and demons.
Tries to address https://github.com/angband/angband/issues/5062 .

Allow monster races to customize the spell casting messages

---

src/init.c

It's handled at installation and is not one created in the private user directories.

Don't create ANGBAND_DIR_HELP in create_needed_dirs()

---

src/mon-blows.c
src/mon-desc.c
src/tests/monster/desc.c

So, use "Morgoth's" rather than "Morgoth, Lord of Darkness's".

Drop phrase in monster name when forming a possesive

---

src/main-cocoa.m
src/main-nds.c
src/main-win.c
src/main-xxx.c
src/main.c
src/ui-birth.c
src/ui-game.c
src/ui-game.h

Resolves https://github.com/angband/angband/issues/2244 .  Since the selector includes a new game option, also check name generation during birth for whether the name would coincide with an existing savefile.
For the front-ends using main.c, the selector will be shown if the -c option is used on the command line.  That option will override the -n option if it is present.  There's some interaction between the -c and -f (force name) option as well.  If -f is used and the default savefile set by the front end is already present, the -c option won't include an option for a brand new game with a new savefile.
The other front ends don't use the selector and their interaction with play_game() is basically the same as before.  The difference is the argument to play_game() is now an enum rather …

Add an option to play_game() for an in-game savefile selector.

---

.github/workflows/release.yaml
CMakeLists.txt
Makefile
configure.ac

Make it opt-in, even if sphinx-build is available.  For autoconf, build the documentation as part of the all rule rather than deferring it to the install rule.
The former is so someone with sphinx-build installed isn't forced into building the documentation.
The second lets,
```
make
sudo make install
```
be safer - the documentation will be built in the first invocation of make and not when invoked by root (sphinx-build and the better theme, if used, will still have to be available to both the regular user and for root even after this change).

Tweak how building the documentation is integrated with autoconf/CMake

---

docs/hacking/compiling.rst
src/Makefile.3ds
src/Makefile.nds.arm9
src/main-nds.c
src/nds/nds-buttons.c
src/nds/nds-draw.c
src/nds/nds-draw.h
src/nds/nds-event.c
src/nds/nds-keyboard.c
src/nds/nds-screenkeys.c
src/nds/nds-slot2-ram.c
src/nds/nds-slot2-ram.h
src/nds/nds-slot2-virt.c
src/nds/nds-slot2-virt.h
src/z-virt.h

This just contains two small compile fixes after recent breakage, as well as a bit of documentation that I wrote up on how to build and debug NDS/3DS builds of the game (I hope I got the syntax right).

nds: Compile fixes and documentation

---

src/effect-handler-general.c
src/trap.c

- Don't allow trap doors (i.e. from a trap creation projection) in a single combat arena
- Don't allow the alter reality effect in a single combat arena.
The first plugs a possible one route out of a single combat arena that doesn't involve killing the monster:  read a trap creation scroll (or have a monster trigger that projection), get a trap door, and fall through it.
Since there's no current way to trigger an alter reality effect in a single combat arena (no device, activation, paladin spell, or monster spell uses it), the second is only protecting against possible future changes.

More single combat paranoia

---

lib/icons/Makefile
lib/icons/angband-sdl.desktop
lib/icons/angband-sdl2.desktop
lib/icons/angband.metainfo.xml

Updated desktop files and added a metainfo file.
Some general instructions when packaging on Linux:
* The .metainfo file should be packaged at {prefix}/share/metainfo/
* Desktop files expect for icons to be packaged at {prefix}/share/icons/hicolor/{res}/apps/angband.png
* The .metainfo.xml file expects that at least one of the desktop files to be packaged at {prefix}/share/applications/angband.desktop
References:
https://freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s07.html

Update Linux desktop files

---

src/savefile.c

May improve the error handling that led to this report, http://angband.oook.cz/forum/showpost.php?p=157868&postcount=38 , of a savefile failure.

Set character_saved to false if savefile could not be opened.

---

acinclude.m4
configure.ac

I'm not sure how I missed upstreaming this fix during my original PR, so here is the second part.

Fix up handling of the SDL/SDL2 prefix when configuring

---

.github/workflows/nintendo.yaml
.github/workflows/release.yaml

Added Nintendo workflow and release. 
Zip structure is prepared to copy and paste into the 3ds and nds sd card root.
**3ds**
Angband-4.2.4-9-g45dd706fa-3ds.zip
```
.
├── Angband-4.2.4-9-g45dd706fa.3dsx
└── angband
└── lib
```
**nds**
Angband-4.2.4-9-g45dd706fa-nds.zip
```
.
├── angband
│   └── lib
└── Angband-4.2.4-9-g45dd706fa.nds
```
I have tested the build on my New 3DS XL and only got the 3DS release running properly. I'll further check my 3DS setup soon since I get only a black screen when running nds using twilightmenu. 
Prerelease: https://github.com/kleo/angband/releases/tag/4.2.4-9-g45dd706fa
Workflow runs:
nintendo.yaml: https://github.com/kleo/angband/actions/runs/1964095445
release.yaml: https://github.com/kleo/angband/actions/runs/1964095445

Nintendo workflow and release

---

src/mon-timed.c

Released monsters continued to cast spells at the last monster the player commanded them to cast at. If this monster-monster target dies, there was a game crash (also fixed).

Fix strange monster behaviour and crash in necromancer command spell

---

src/mon-blows.h

Maybe these struct members are obvious to experienced angband devs, but for some reason confused me (regarding what was attacker, what was target) :)

Comment the confusing p, mon, t_mon members of struct melee_effect_handler_context_s

---

src/cmd-cave.c
src/cmd-wizard.c
src/effect-handler-attack.c
src/effect-handler-general.c
src/game-world.c
src/mon-attack.c
src/mon-blows.c
src/mon-make.c
src/mon-util.c
src/player-attack.c
src/player-timed.c
src/player-timed.h
src/player-util.c
src/project-player.c
src/tests/effects/chain.c
src/tests/object/slays.c
src/wiz-debug.c

if using an object is involved, the object is identified.  Resolves https://github.com/angband/angband/issues/5360 .  See also this post, http://angband.oook.cz/forum/showpost.php?p=150444&postcount=148 .  Alters the prototypes for player_set_timed(), player_inc_timed(), player_dec_timed(), and player_clear_timed().  For related reasons, also don't disturb the player when a chest trap is detected.
The messaging from a keymap with chained commands can be suboptimal.  A paladin with a keymap to cast Bless and Heroism will see "You feel like a hero!" on the top line of the main window if both spells are successfully cast.  Both spell messages are in the message log, but, because of multiple message_flush() calls during the process of menu display for the commands, the messages won't be …

Don't disturb player for changes in timed effects whose source is a player action and,

---

src/effects-info.c

This fixes the info text for short beam effects, matching the length calculation in `effect_handler_SHORT_BEAM`:
```
bool effect_handler_SHORT_BEAM(effect_handler_context_t *context)
{
...
int rad = context->radius + (addons ? player->lev / context->other : 0);
```

Fix effects info for SHORT_BEAM length

---

src/ui-target.c

commit 496fc1c51d5276100d924c5a64ca1585f676c205 changed the "You see" message
when examining a square to "You recall" if the square wasn't visible in order
to avoid "seeing" while blind.
This has the unfortunate side effect of using "You recall" when detecting or using
telepathy.
Detect whether a visible monster is on the square that wouldn't have otherwise
been seen and infer that it was viewable via detection or telepathy.  This
unfortunately doesn't handle non-monsters viewable this way (such as doors via
"Read Minds" or shop entrances), but it clears up the common case of monsters

Modify text when player is aware of a monster via detection or telepathy

---

src/ui-store.c

There was a bug in menu_store_item that prevented the player from buying more than one item.

Fix bug in context_menu_store_item

---

src/ui-store.c

This changes what happens after a player presses the enter key within a store from the event being dropped to opening the context menu for the mouse. This helps playing the game on platforms without hardware keyboards (namely consoles and phones) but doesn't change any underlying behavior for PC players.

Change default enter behavior in stores

---

src/main-gcu.c
src/player-util.c

1) Repeated word in a comment in main-gcu.c.
2) In disturb()'s comments, remove references to two arguments that are no longer present.

Fix two comments

---

src/nds/nds-buttons.c
src/nds/nds-screenkeys.c
src/tests/z-util/util.c
src/z-util.c
src/z-util.h

Add an extra escape sequence, "\x", that can be used in
"button-mappings.txt" and "screen-keys.txt" to encode arbitrary
characters in the nds and 3ds port.
My use case for this is binding buttons to function keys (eg. f1, f2) which I can then bind to macros in-game.
An alternative would be creating an escape code for each function key, which would be easier to use (I had to use an angband installation on my computer to check the keycodes for the function keys). On the other hand, this solution is more general, and probably has some more uses that I'm not thinking of.

Add hex escape sequence for nds config files

---

src/tests/unit-test.h

The missing pair of braces cause the test harness to always print its verbose failure message even when verbose is disabled.

tests: fix missing braces in unit test harness

---

configure.ac
src/h-basic.h
src/z-queue.h

The only C99 compiler (to my knowledge) that ever shipped without stdint.h was MSVC versions prior to Visual Studio 2010. Given the age of that compiler, we can probably drop support for it by now and just assume a proper C99 environment.

configure: remove stdint.h check

---

configure.ac

This macro checks for the compiler not supporting const correctly. The manual for autoconf, even as far back as version 2.60 (~2007), described this as obsolescent and all existing C compilers do support const properly.

configure: remove AC_C_CONST check

---

.github/workflows/linux.yaml
configure.ac
src/h-basic.h
src/z-file.h
src/z-form.h
src/z-textblock.h

Having the configure script detect support for this by compiling a test program is a bit unnecessary - clang and gcc (~all versions) both support these attributes, and other compilers don't. We can just condition on the compiler type directly in src/h-basic.h and not have get the user to tell us whether their compiler supports a feature.

configure: remove printf format attribute check

---

src/main.c
src/z-virt.c
src/z-virt.h

This change:
1. Removes the -xmem-poison-* options
2. Removes the MEM_POISON_* flags used to implement them
3. Removes the extra memory overhead for allocation sizes in mem_alloc() and mem_realloc().
Since supporting MEM_POISON_* imposed one size_t of extra overhead on *every* allocation, the memory savings from this change are substantial.
I originally added these memory poisoning flags a bit over 10 years ago, but since that time valgrind has gotten a lot better and asan has become a thing. The malloc in glibc also does support far better memory poisoning configurable via env vars. Between those three much better options it makes little sense for Angband to pay an extra size_t on every allocation to support its own kind of poisoning.

z-virt: remove memory poisoning support

---

src/main-gcu.c
src/main-ibm.c
src/main-nds.c
src/main-sdl.c
src/main-sdl2.c
src/main-win.c
src/main-x11.c
src/main-xxx.c
src/ui-command.c
src/ui-map.c
src/ui-term.c
src/ui-term.h

On every platform, these were set to COLOUR_WHITE and ' ' respectively; replace them throughout with their manifest constants and remove them. It's not very obvious why they were originally added, since they were only used internally to Angband and never actually drawn on the screen - rather, any cell drawn with attr_blank and char_blank was considered empty and cleared in a platform-specific way. Making them configurable per-platform when in fact they were not exposed to the platform is somewhat puzzling.

ui-term: remove attr_blank & char_blank

---

src/mon-init.c

- Plug some memory leaks on error returns.
- Use a more appropriate parser error for an invalid monster base in monster.txt's friends-base directive.

Tidy some monster-related parsing

---

src/mon-init.c

With this fix, the monster hearing and smell distances scale with LoS size

Fix incorrect scaling of monster hearing and smell

---

src/generate.c

due to using the wrong variable to initialize the 'tx' test variable for the loop.

Bugfix: sanitize_player_loc() does not loop through the dungeon fully

---

src/player-spell.c

Items after the first one in magic_realm linked list are not initialized, leading to a crash if you define a multi-realm caster class.

Fix crash if there is a multi-realm caster class

---

src/cmd-cave.c

Related to the discussion for https://github.com/angband/angband/issues/5544 .

Skip confirmation for stepping into lava if the player's character is confused.

---

src/datafile.c
src/ui-entry.c

Resolves PowerWyrm's report here, http://angband.oook.cz/forum/showthread.php?t=11459 .

Avoid use after free when an error is reported from a parser's finish method

---

src/ui-context.c

The "Drop All" command key is currently 'k' in rogue keymap mode in the item context submenu of the inventory menu.  In all other menus 'j' and 'k' can be used to navigate up and down to select a menu item.  I propose this be changed to 'A'.

"Drop All" command key in rogue keymap mode

---

src/init.c

This bug can be triggered by starting angband with: ./src/angband -c
Enabling the animate_flicker option, killing your character, and choosing to start a new game.
The crash occurs because ui-display.c idle_update() calls functions expecting `cave` pointer to be valid.

Fix segfault after player death and starting a new game

---

src/datafile.c
src/datafile.h
src/effects.c
src/init.c
src/main-gcu.c
src/main-sdl.c
src/main-sdl2.c
src/main-spoil.c
src/message.c
src/obj-init.c
src/obj-tval.c
src/obj-util.c
src/option.c
src/parser.c
src/tests/parse/e-info.c
src/tests/parse/k-info.c
src/tests/parse/parse.c
src/ui-death.c

For integer conversions, strtol() and strtoul() define what happens when the input would overflow what can be represented internally.  Apparently, sscanf() does not define what happens in that case.  The use of sscanf() for extracting a string in grab_element_flag() could cause a buffer overflow with an appropriately crafted data file.  Avoiding sscanf() also avoids compiler warnings from Visual Studio when _CRT_SECURE_NO_WARNINGS is not set.

Avoid using sscanf()

---

src/obj-info.c

total_dam is in 10xhitpoints, crit_mul and crit_add are in 100xhitpoints, so (total_dam * crit_mul) is in 1000xhitpoints, so crit_add needs to be scaled to these units too.

Fix under-accounting for +dam from critical hits

---

lib/gamedata/constants.txt
src/init.c
src/init.h
src/mon-timed.h
src/obj-info.c
src/player-attack.c
src/player-attack.h
src/tests/parse/z-info.c
src/tests/z-util/rational.c
src/tests/z-util/suite.mk
src/z-util.c
src/z-util.h

Resolves part of https://github.com/angband/angband/issues/4803 . Fixes some mismatches between the critical calculations used for displayed object information and those used for combat.  In all instances the object information calculations were changed to match those for combat:
1) For non-O melee criticals, the normalization of the sums for the
additive term was wrong (500 instead of 1300).
2) For non-O melee criticals the to-hit value was scaled by 3 for
object information while the scale factor for combat was 1.
3) Non-O criticals summed over a range of powers that was w, the weight
of the missile or weapon, to w + a where a is 649 for melee criticals
and 499 for ranged criticals.  The range of powers in the combat
calculations is 1 + weight to 1 + weight + a.
4) For O criticals with …

Put constants for criticals in constants.txt

---

src/cmd-core.c

That's a correction for handling bloodlust from https://github.com/angband/angband/commit/d88b41a03f7fcd6a0d040fc2797447d543d8e845 .

Fix command annotation:  wielding takes energy

---

src/effect-handler-attack.c

Ask for direction before displaying the message, otherwise it's weird for the player to tell them an earthquake has occured before they picked a direction.  If they decline to pick a direction, abort out of handling the effect.

Clean up message handling on targeted earthquakes.

---

src/cocoa/snd-cocoa.m

Avoids a file descriptor leak seen with initWithContentsOfFile since macOS 10.15 (Catalina).

Mac:  use NSSound's initWithData

---

docs/command.rst
docs/playing.rst

That reflects the change in https://github.com/angband/angband/commit/afd45b56894440f89af75c4d8d15a2c793bc94fa and that there doesn't appear to be a compilation option to prevent the "double ctrl-z escape death trick".

Update docs about interrupt handling

---

src/player-path.c
src/target.c
src/ui-target.c

Closes a possible cause for https://github.com/angband/angband/issues/5295 : magic mapping includes a grid with a secret door, monster opens or breaks that door, now that grid is "interesting" even if the player hasn't seen or mapped the grid since the door was opened or broken.

Use player's view for square_isinteresting() calls

---

src/gen-cave.c
src/gen-util.c
src/generate.c
src/generate.h
src/wiz-stats.c

Resolves https://github.com/angband/angband/issues/5490.  Uses uncreate_artifacts() from Narsil.  Adds an argument to all the level builders to specify a string describing a failure.  For the scale of the artifact loss issue, generated many levels at level 50 and level 95:  the change protected against zero lost artifacts in the 10000 successful generations at level 50 and eight lost artifacs in the 10000 successful generations at level 95.

Generation failures: protect against artifact loss and better messages

---

.github/workflows/release.yaml

The typos weren't detrimental with the current form of Makefile.src.

Release workflow: fix typos in name extraction

---

docs/attack.rst

That's to match how the BLESSED object flag works in 4.2.*.  Resolves part of https://github.com/angband/angband/issues/5062 .

Update documentation for Holy Avenger and Blessed egos

---

lib/gamedata/monster.txt

See the discussion here, http://angband.oook.cz/forum/showthread.php?t=11492 , including Nick's suggestion, adopted here, for the demonic quylthulgs.

Drop "light" from the descriptions of some quylthulg varieties

---

src/ui-context.c
src/ui-output.c
src/ui-output.h
src/ui-term.c
src/ui-term.h

The artifacts seen were failures to clear or redraw when scrolling through the entries or if backing out one level of the menu and not at the top level of the menu.

Avoid drawing artifacts with the enter menu and big tiles

---

lib/gamedata/monster.txt

That's for consistency with the other mature dragons.  Drop OPEN_DOOR and BASH_DOOR on shadow drakes since they have PASS_WALL.  Resolves https://github.com/angband/angband/issues/5673 .

Drop OPEN_DOOR on Kavlax and mature white and multi-hued dragons.

---

src/gen-cave.c

Increase the constraint that was already present for persistent levels.  The intent is to avoid stairs clustering in certain special rooms.  There's some discussion here, http://angband.oook.cz/forum/showthread.php?t=11522 .

Impose a distance constraint for non-entry stairs of the same type

---

src/store.c

Resolves https://github.com/NickMcConnell/FAangband/issues/383 (the real price of a stocked item generated by store_create_random() is positive, but the player perception of that can be negative leading to a zero priced item with the former pricing scheme).  Also, always constrain the price per item to be at least one when the store is selling.

For baseline store sale price, use max(player's perceived price, real price)

---

src/main-nds.c

Not sure why this isn't an issue anywhere else (thinking about it, what does an alpha value even do when writing to a framebuffer?), but Citra on Wayland actually draws with an alpha value, causing the game to be completely transparent (as in "you can actually see the Desktop, and pretty much only that).

nds: Set an alpha value for translated colors

---

src/mon-spell.c

Those can be triggered when the spell is cast (avoiding a NULL pointer dereference).  Related to https://github.com/NickMcConnell/NarSil/issues/299 .

Add diagnostics for missing monster spell messages

---

src/obj-info.c

Fixes a regression introduced by 7ca6c3760ed01c2bcfde11254daad04eee7b0986 .  Caused chance of a critical (and therefore reported average damage) to be overstated for melee weapons with the O-combat option off.  There's no visible change for ranged weapons (the chance-offset from constants.txt is zero for those).

Object information: have critical chance calculations include chance-offset

---

src/obj-info.c
src/tests/object/info.c

With that and the error corrected by https://github.com/angband/angband/pull/5705 , tighten the tolerances in the tests of the damage reported by the object information calculations.

Object information: be more careful about rounding for damage results

---

src/tests/object/info.c

Avoids infrequent test failures when get_obj_num() cannot get the desired type of ammunition at level 1.

Object information tests:  use lookup_kind() when get_obj_num() fails

---

src/ui-object.c

Was using floor_list's type, which is the same and will likely remain the same as floor_list's type.

Have allocation for throwing_list use its type

---

src/ui-display.c

Resolves https://github.com/angband/angband/issues/5713 .

Rearrange UI's handling of a new level to avoid monster list leaking info

---

src/cave-square.c
src/cave.h
src/effect-handler-attack.c
src/effect-handler-general.c
src/tests/effects/destruction.c
src/tests/effects/earthquake.c

Resolves https://github.com/angband/angband/issues/5723 .  Likely resolves https://github.com/NickMcConnell/FAangband/issues/331 .  May impact https://github.com/NickMcConnell/FAangband/issues/332 .  Extend test cases for destruction and earthquake effects so they can detect, if compiled with the address sanitizer, the buggy behavior causing https://github.com/angband/angband/issues/5723 .

Destroyed grid: remove any orphaned objects with a known counterpart there

---

src/borg/borg7.c
src/borg/borg9.c

ya! I think fixed myself so I have only one commit in here! 
This will have to do till I can rework activations.  Sadly my research shows 
1) borg isn't using potions of dragon breath
2) borg isn't using wands of dragon breath
so he will only come across this with dragon armor.   The attack code is also wrong because it just randomly picks one of the attacks and assumes it will be that... the least it should do is pick the worst case and assume it will be that.  Be bad if it thought it was going to take out a unique in one blow and ends up doing a breath it is immune to.  Stupid stupid borg.

a temporary fix to the activation of something that allows selection

---

src/ui-effect.c

In the current code, the random option is always requested so the player will not see a change in how the menu behaves.

Effect selection menu: only add the random option if requested

---

src/Makefile.std

Like configure and cmake, default to compiling the Borg but not include Borg players in the high scores.

Makefile.std: add lines for compiling the Borg

---

src/Makefile.std

The former works with both GNU make and BSD make.  Fixes a regression introduced by 4.2.5:  on OpenBSD would have to use gmake rather than make to use Makefile.std (still have to change gcc to cc or clang, but that was also true with 4.2.4).

Makefile.std: use suffix rules rather than pattern rules

---

.github/workflows/linux.yaml

CMakeLists.txt dropped that option in https://github.com/angband/angband/commit/6d447386ba10f3836468a2e36d62730fe7d52a81 .  Format argument checking for gcc and clang was made the default in https://github.com/angband/angband/commit/838f0f3030c3dcc1dbcbdb5daa565743a454490a .

Workflows: drop USE_PRINTF_STYLE_CHECKS for builds with CMake

---

src/ui-input.c

1) Use get_com_ex() rather than get_com() so the argument for ^ is not coerced to a char.
2) Only use KTRL() to encode the keystroke if ENCODE_KTRL() for the argument to ^ is true; otherwise put KC_MOD_CONTROL in the modifiers.
Resolves https://github.com/angband/angband/issues/5748 .

Generalize handling of ^

---

src/Makefile
src/Makefile.src

That's to address part two of Magnate's request here, http://angband.oook.cz/forum/showpost.php?p=161423&postcount=1 .  Also use $(PROGNAME).o rather than angband.o in the clean rule so forks have one less thing to change.

Have "make clean" remove all optional intermediates

---

src/mon-lore.c

Ported from NarSil, where it prevents crashes during lore updates after a monster dies on its own turn.

When appending spells to monster lore, set ref_race for expressions

---

src/borg/borg1.c
src/borg/borg1.h
src/borg/borg4.c
src/borg/borg6.c
src/borg/borg7.c
src/borg/borg9.c

This includes 
1) the rest of the "easy to handle" activations.  There are still a few that the borg either doesn't do or hasn't had code for the base object added.  For example, wand of dragon breath and its corresponding activation don't have code yet
2) moved some globals into the borg_skill array.  Basically the code should have "borg_notice fills in borg_skill and similar arrays, borg_power only looks at the borg_skill and similar arrays to know what the borgs power level is" and over time other globals have migrated in and code has been added to borg_power that looks directly at items.  It works but will make it hard to reimplement the dynamic calculations.

wrap up another pass at random artifact activations

---

src/cmd-obj.c

Resolves PowerDiver's report here, http://angband.oook.cz/forum/showpost.php?p=161575&postcount=21 .

Don't deduct charge/item when using an unidentified item and effect is canceled

---

src/Makefile.3ds
src/Makefile.nds.arm9

NDS hardware is too limited to support the additional 400KB of memory usage, so discourage enabling the Borg there.

nds: Enable the Borg on the Nintendo 3DS

---

src/main-sdl2.c

Also avoids a gcc compiler warning (with -Wundef) about undefined preprocessor macros.

SDL2: fix generation of stipple pattern on big-endian systems

---

src/borg/borg9.c

I should look into if keeping local state RNG values for the borg makes sense.

RNG shouldn't be reset if the command will be repeated

---

configure.ac
src/h-basic.h

These typedefs aren't used anywhere in the source and it's hard to conceive of a situation where one would want to enable them, given that they have been fully replaced with standard C types.

configure: remove skip-old-int-typedefs option

---

src/effect-handler-general.c
src/main-stats.c
src/mon-desc.c
src/mon-group.c
src/mon-make.c
src/mon-move.c
src/mon-predicate.c
src/mon-predicate.h
src/mon-timed.c
src/mon-util.c
src/object.h
src/project-mon.c
src/ui-map.c
src/wiz-stats.c

See http://angband.oook.cz/forum/showthread.php?t=11589 .  Refactor monster_is_unique() so it tests the unshifted shape and add monster_is_shape_unique() to test the current shape.  The results of those can only differ if the monster is currently shape shifted.  Use those functions instead of direct tests of a monster's race->flags or original_race->flags.  Where that intentionally changes the prior behavior is in nominating a new group leader, compacting monsters, protecting a unique from trampling, computing saving throw against timed effects, calculating the difficulty of player thefts, protecting a unique from death to non-player hits or projections, protecting a unique from polymorph, and handling of uniques in the statistics code.  In all cases except for trampling, the prior code …

Check unshifted shape rather than current shape when testing for Banish

---

src/Makefile.osx

That would include files like .DS_Store or .deps that may have been generated in the source directory.

macOS: avoid cruft in the application bundle's lib/tiles directory

---

src/Makefile.blocksds.arm7
src/Makefile.blocksds.arm9
src/nds/nds-slot2-ram.c
src/nds/nds-slot2-ram.h
src/nds/nds-slot2-virt.c

The big change here is that BlocksDS is providing its own Slot-2 RAM API - providing faster I/O on supported cartridges, as well as support for more cartridges than the dated `ram.c` library.

Nintendo BlocksDS: update to BlocksDS 0.11.0

---

src/tests/parse/ptimed.c

Also fix some formatting inconsistencies and typos in the comments or messages for those tests.

Slightly tighten player_timed.txt parsing tests

---

lib/gamedata/class.txt
lib/gamedata/object.txt
lib/gamedata/old_class.txt
src/cave-map.c
src/cave-square.c
src/cave.h
src/cmd-cave.c
src/cmd-pickup.c
src/effect-handler-general.c
src/game-world.c
src/list-effects.h
src/player-util.c

In the split, one part handles money (SENSE_GOLD and DETECT_GOLD) and the other (SENSE_OBJECTS and DETECT_OBJECTS) handles all other objects.  That's to match how gold gets different treatment in other parts of the game and to resolve PowerDiver's report here, https://forum.angband.live/forum/showpost.php?p=162031&postcount=14 , of inconsistent messaging.  Give square_sense_pile() and square_know_pile() an additional argument to select which objects in the pile are processed.  Add forgetting remembered objects that are no longer there to square_sense_pile():  square_know_pile() already has it and the sense effect was implementing it separately for remembered piles that had completely gone away.  All objects and spells with SENSE_OBJECTS or DETECT_OBJECTS also get the _GOLD effect: …

Rename DETECT_GOLD to DETECT_ORE; split SENSE_OBJECTS and DETECT_OBJECTS

---

CMakeLists.txt
docs/customize.rst
src/Makefile.msys2.sdl2
src/Makefile.src
src/main-sdl2.c
src/sdl2/pui-ctrl.c
src/sdl2/pui-ctrl.h
src/sdl2/pui-dlg.c
src/sdl2/pui-dlg.h
src/sdl2/pui-misc.c
src/sdl2/pui-misc.h
src/sdl2/pui-win.h

Intended as preparation for adding a font selection dialog like the SDL front end now has.  The changes to appearance reduce the role of color in the menus, so as long as the colors at COLOUR_WHITE is distinct from the colors at COLOUR_SHADE and COLOUR_DARK, the menus should be usable.  That resolves https://github.com/angband/angband/issues/5596 .  Allows keyboard navigation of the menus (to avoid conflicts with user keymaps, no key is assigned for transferring focus to a menu; such keys can be configured with the "Menu Shortcuts" menu item).  Should allow mouse wheel events to change the integer menu entries (font and tile size).  Adds entries to sdl2init.txt so copies of that file generated by this version can not, without editing, be used by previous versions.
This is a rebased …

SDL2: refactor event handling and change drawing for menu items

---

docs/copying.rst

They are now available under CC-BY 4.0. (see http://www.dubtrain.com/angband/).

Update licence info re Dubtrain sounds

---

src/ui-death.c
src/ui-object.c
src/ui-options.c
src/ui-player.c
src/ui-spell.c
src/wiz-spoil.c

Resolves https://github.com/NickMcConnell/FAangband/issues/397 (also present in vanilla).
The handling of some strings whose encoding is unknown (namely results from directory reads) or strings which are hardwired in the source code and currently do not contain multibyte characters has not changed. Those are:
- Formatting of entries for the save files in main.c
- The speed indicator in ui-display.c
- The depth indicator in ui-display.c
- The section labels for the resistances panel in ui-player.c

Handle padding of text that could contain multibyte UTF-8 characters

---

src/obj-randart.c
src/tests/object/info.c
src/tests/z-util/meanvar.c
src/tests/z-util/suite.mk
src/z-util.c
src/z-util.h

Allow the caller to request the fractional part of the result.  If the fractional part is not requested, the returned value is rounded to the nearest integer rather than the prior behavior of rounding towards zero.  Avoid overflow in the internal calculations.  For variance() if the result would be greater than INT_MAX, return INT_MAX.  For variance(), give the option to normalize by size minus one rather than size.  Also give an option for variance() to scale the result by one over size to correspond to the expected variance of a mean estimate.
Use the new forms of mean() and variance() in the object damage information test cases.  Avoids the accumulation of roundoff error that the previous version of those test cases had.  Allows increasing the number of hit simulations in those tests …

Extend mean() and variance()

---

src/main-sdl2.c

Resolves Ituirth's report here, https://forum.angband.live/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248123#post248123 , that the menu entry for selecting the size was always disabled for a TrueType font.  That is a regression introduced by d6886368017822967efa5911a64b8819502fd7e4 .

SDL2: enable font size selection for vector fonts

---

src/obj-info.c

These changes are already incorporated in https://github.com/NickMcConnell/FAangband/pull/405 for FAangband.

Correct out-of-date comments for critical calculations in obj-info.c

---

src/sdl2/pui-ctrl.h

Suggested by Ituirth.  For the default menu bar font, reproduces the height of the menu bar from before the refactoring of the SDL2 front end.  Resolves tangar's complaint here, https://forum.angband.live/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248157#post248157 , about less usable space with the refactored front end.

SDL2: use a smaller border around controls in menus and dialogs

---

src/tests/object/info.c

Regression introduced by 8a21bbe0686d08a981bf57f92a10c49d4caa1ce2 .  Saw at least one test failure when NHITS is 100000000 (default is 10000); possible cause is that there is still some sloppy rounding in obj-info.c's damage calculations.
This change is already incorporated in https://github.com/NickMcConnell/FAangband/pull/405 for FAangband.

Unit tests: correct variance calculation for weapon damage

---

src/mon-lore.c

There's no current effect for obvious flags (in Vanilla all those happen to fall in the range handled by mflag_union()) but the flags learned on monster death are affected.  Ported from https://github.com/NickMcConnell/NarSil/pull/394 .

Use rf_union() rather than mflag_union() in lore_update()

---

src/player-util.c

Could erroneously set the fractional hit points to zero rather than the fractional spell points.  Seen while looking for the source of https://github.com/NickMcConnell/FAangband/issues/406 but should have no effect on that issue.

Fix handling of negative spell points

---

src/player-calcs.c

Ported from https://github.com/NickMcConnell/FAangband/pull/407 .  There should be no observable change to what the player experiences (all the tested flags are tied to the player's class, calc_bonuses() is called at least twice after starting/loading a game before the player can act, and for the affected calculations there's no hysteresis with the old versions of the calculations if they happen to use potentially stale versions of the flags).

player-calcs: use updated flags rather than flags from prior state

---

src/main-sdl2.c
src/sdl2/pui-ctrl.c
src/sdl2/pui-ctrl.h
src/sdl2/pui-dlg.c
src/sdl2/pui-dlg.h
src/sdl2/pui-win.h

May resolve Ituirth's report here, https://angband.live/forums/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248173#post248173 (dangling reference/use after free for a dialog leads to a crash), and other problems after using a menu shortcut and then trying to interact with the menu using the mouse.

SDL2: rework transferring focus

---

src/gen-room.c
src/mon-make.c
src/trap.c
src/z-bitflag.c

That's so other logic that assumes what the assertion tests happens after the assertion.  Fixes an instance reported by PowerWyrm here, https://angband.live/forums/forum/angband/vanilla/10689-angband-4-2-5?p=248214#post248214 .  Remove some redundant assertions.

Move some assertions

---

src/effect-handler-attack.c
src/effect-handler-general.c
src/game-world.c
src/list-mon-message.h
src/mon-attack.c
src/mon-blows.c
src/mon-blows.h
src/mon-msg.c
src/mon-msg.h
src/player-util.c
src/player-util.h
src/project-mon.c
src/project-player.c

For player damage to monsters, provide damage notifications for projections and effects that do not use projections.
For damage to a player, provide damage notifications for all but the poison, cut, and starvation damage applied in process_world().  The damage notifications now include the effects of player invulnerability, player damage reduction, and changes to damage in monsters' blow handlers.
Resolves https://github.com/angband/angband/issues/5862 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780770 .
Side effect of these changes are:
1) Messages for monsters affected by an earthquake now use add_monster_message()
and that implies some changes to the text of the messages, ordering of the messages, and handling of duplicate messages.
2) To have the damage notifications for …

Improve the show_damage option

---

.github/workflows/dos.yaml
.github/workflows/linux.yaml
.github/workflows/mac.yaml
.github/workflows/msbuild.yaml
.github/workflows/msys2.yaml
.github/workflows/nintendo.yaml
.github/workflows/nmake.yaml
.github/workflows/release.yaml
.github/workflows/windows.yaml

See GitHub's notice here, https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ , about the Node 16 to Node 20 transition.

Workflows: update versions of used actions for compatibility with Node 20

---

src/cmd-cave.c

The specific conditions it would happen are an equipped weapon with a sticky curse and the best digger the character has is in a stack of more than one digger in the pack.

Avoid losing objects in pack for digging corner case

---

lib/gamedata/activation.txt
lib/gamedata/class.txt
lib/gamedata/object.txt
lib/gamedata/old_class.txt

That is with spells, objects, or activations so the effect never damages the player invoking the effect.  Resolves https://github.com/angband/angband/issues/5866 .

Use SPHERE rather than SPOT with LIGHT_WEAK or DARK_WEAK

---

src/cmd-cave.c
src/player-calcs.c
src/player-calcs.h
src/player-path.c

Resolves https://github.com/angband/angband/issues/5867 .
When running along the computed path, only open a door or clear impassable rubble if all the neighbors of the door or rubble are known.  Otherwise, stop before the door and rubble and let the player decide what to do.  For known visible traps, always stop unless the player is trapsafe.
When computing the path to a previously mapped location, prefer that the path only go through previously mapped squares.  if no such path is found, then allow going through squares that have not been mapped before.
When computing a path, prefer that the path does not include a known visible trap.  If no such path is found, then allow going through known visible traps.
For tests of known terrain when computing the path, use the player's memory of the …

Allow player pathfinding to go through closed doors, impassable rubble, traps

---

src/cave-square.c
src/cmd-cave.c
src/mon-move.c
src/project-feat.c
src/trap.c
src/trap.h

Resolves https://github.com/angband/angband/issues/5683 .  Rename square_remove_trap() to square_remove_all_traps_of_type().  Use it for removing webs, glyphs of warding, decoys, and door locks.  Add new function, square_remove_trap(), to remove one trap.  Use it when disarming a trap and in hit_trap().  Change the meaning of square_set_trap_timeout() so it returns whether a trap was disabled rather than whether there was a trap in the grid.

Have more logic accommodate multiple traps in a square

---

src/sdl2/pui-dlg.c
src/sdl2/pui-misc.c

They happen with gcc using -Wundef and -Wold-style-definition.

SDL2: avoid some compiler warnings

---

CMakeLists.txt
docs/hacking/compiling.rst

Fixes building the documentation when cross-compiling for Windows on Unix and no version stamp file was present (build ID was not set in that case causing the rewritten conf.py for the manual to call version.sh; version.sh not availble at the expected relative path to the rewritten conf.py).

CMake: use version.sh to get build ID when the host is Unix

---

src/cave-square.c

Reported by agoodman00.  Regression was introduced post 4.2.5 in c631b56681b414593cedd1e46c2b63c89e735c17 .

Fix regression: monster opening secret door triggers assertion

---

src/borg/borg-trait.c

just a typo in how a couple of the curses are applied.  did
borg.trait[BI_SPEED] = -5;
not 
borg.trait[BI_SPEED] -= 5;

borg: typo in calc of a couple of curses.  -= not =-

---

src/game-world.c

Resolves https://github.com/angband/angband/issues/5886 (single combat used in dungeon while recall counter in progress; assertion failure when recall triggers) and player getting stuck in an empty arena (single combat used in town while recall counter in progress; recall triggering in the arena kills the monster and transports player to an emtpy arena).

Suspend word of recall counter when in an arena

---

src/main-sdl2.c

Resolves part of Ituirth's report here, https://angband.live/forums/forum/angband/vanilla/10748-proposed-changes-for-sdl2?p=248346#post248346 , of problems with two entries in tangar's font.

SDL2: map 127 to whatever the font has rather than a space

---

src/main-sdl2.c
src/z-util.c

Also fix compilation error (mismatched static/non-static declaration) when compiling main-sdl2.c.  That error would happen in the old version when NDEBUG was defined and is a post 4.2.5 regression introduced by d6886368017822967efa5911a64b8819502fd7e4 .

Fix instances of using "ifdef NDEBUG" where "ifndef NDEBUG" was intended

---

src/cave-map.c
src/cave.c
src/cmd-cave.c
src/effect-handler-general.c
src/project-feat.c
src/ui-target.c

In particular:
1) square_note_spot() used square_isknown() to shield a call to square_memorize(), but !square_isnotknown() is better to handle cases where the grid is known but misremembered.
2) The MAKE_DOOR projection handler tested the grid where a door was created with square_isknown() to decide whether to set obvious to true in the event handler context; using square_isseen() is better if the grid is not seen but has been seen before.
3) The RUBBLE effect used count_feats(), causing rubble to be added only in known grids.  Use count_neighbors() instead so both known and unknown grids can be affected.
4) All uses of count_feats() are for testing whether a direction argument is necessary for a cave-altering command.  count_feats() tested the actual cave for the presence of the type of …

Correct some logic where square_isknown() is used

---

src/tests/game/basic.c

The cause was moving away from the stairs and then have a monster move to the stairs before being able to move back.  Also, call on_new_level() after most reloads in that test so player->state and player->known_state are filled as they would be when play_game() is called.

Plug source of occasional test failure in tests/game/basic

---

src/cave-map.c
src/cave-square.c
src/cave.h
src/cmd-cave.c
src/effect-handler-general.c

The new name for square_isnotknown() is square_ismemorybad().  In the case where it is passed a chunk that is neither cave nor player->cave, it will return true (no player memory).  That makes it equivalent to !square_isknown() and a check on whether the terrain in player->cave and cave is the same.  Resolves https://github.com/angband/angband/issues/5879 .

Rename square_isnotknown(); make it and square_isknown() useful for player->cave

---

src/cave-map.c
src/trap.c

Copy the modified timeouts for the traps from the actual cave to the player's memory if the grid is seen.  Use the player's memory of the traps in map_info().  Prevents a change to the map if a trap is disabled while blind.

Correct map updates after disabling a trap

---

src/borg/borg-caution.c
src/borg/borg-escape.c
src/borg/borg-fight-attack.c
src/borg/borg-fight-attack.h
src/borg/borg-flow-kill.c
src/borg/borg-flow.c
src/borg/borg-messages.c
src/borg/borg-think-dungeon-util.c
src/borg/borg-think-dungeon.c
src/borg/borg-trait.h
src/borg/borg.c

- arc/cone/spray processing, which mostly gives splash damage but still requires a direct targeting of one creature (so no offset attack like you can get from ball attacks). 
- made the ^z % ask if you want to see "arc" projection or just beam.
- removed a "guess if I am on the stairs" flag which gives trouble with the new auto-explore/go to nearest stairs code.  Also updated to remove looking for the (para) "you aren't on stairs, dummy" text and look for the messages being not on stairs but using the "go up" or "go down" button.  I think the removed flag was useful when the borg used to screen scrape but now uses an api which should properly give "this square is stairs" even if it just shows the player or a monster.  It has used that api for a long time (since 3.4.1 at least) but no one …

Borg: arc attack and stairs flag and flee boring levels 

---

src/cmd-cave.c
src/player-path.c
src/player-path.h
src/player-util.c
src/player.c
src/player.h
src/tests/Makefile
src/tests/unit-test-data.h
src/tests/z-queue/qp.c
src/tests/z-queue/suite.mk
src/z-queue.c
src/z-queue.h

For calculating multiple paths from the same starting point, make the distance array calculation public and have it return its results rather than storing them in a static array.  In the internals of that calculation, replace the point set with a queue and explicitly have the edges of the cave as unreachable to simplify bounds checks.
With that distance calculation available, have the nearest staircase/nearest unexplored calculations in do_cmd_navigate_down(), do_cmd_navigate_up(), and do_cmd_explore() use the expected number of turns to navigate the path rather than distance().  Move the search for the nearest to path_nearest_known() and path_nearest_unknown() (declared in player-path.h; implemented in player-path.c).
Change the interface of find_path() so it returns the steps in the …

Refactor player-path

---

docs/hacking/modifying.rst
lib/gamedata/player_timed.txt
src/player-calcs.c
src/player.c
src/ui-entry.c

That means player_timed.txt is the sole source (with the exception of a hack for TRAPSAFE) of information about linkages between timed effects and resistances or object flags.  Does have a performance cost (loop over TMD_MAX) in the affected calculations.

Have player calculations use resist and flag-synonym from player-timed.txt

---

src/wiz-debug.c

Matches what the birthing process and do_cmd_wiz_cure_all() do for the hunger meter.

Cheating death: leave at 89% full rather than 99% full and slowed

---

docs/hacking/compiling.rst

Do not need the extra packages installed by -toolchain.  Also, do not imply that the ncurses dependency is needed for SDL2.

MSYS2 and SDL2 compiling documentation: recommend -gcc over -toolchain

---

src/Makefile.msys2.sdl2

Likely resolves crash reported here, https://angband.live/forums/forum/angband/vanilla/248431-fresh-install-noob-trouble-compiling-sdl2-w-sound-version?p=248453#post248453 , by smbhax .  Drop linking with libSvtAv1Dec as it is not a dependency for libavif.

MSYS2 and SDL2: link to ntdll rather than ntoskrnl

---

src/player-path.c

Fixes a regression from 4d76112f25e5287b9c2ebfdaef80c72d13928900 .  An infinite loop happens if there is no feasible destination with the most restrictive settings on the path finding.

Prevent infinite loops in path_nearest_*()

---

src/cmd-cave.c
src/cmd-core.c
src/cmd-core.h
src/cmd-obj.c
src/init.c
src/obj-ignore.c
src/player-birth.c
src/player-path.c

Generally gives better behavior than 4.2.5 when repeating the last command after an interrupted pathfinding command:  repeats the pathfinding command rather than the last run used to take a step along the path.  Fixes a regression introduced by 4d76112f25e5287b9c2ebfdaef80c72d13928900 : when compiled with -fsanitize=address and -fsanitize=undefined, repeating the last command after an interrupted pathfind when no normal run had been used in the session would trigger a crash in run_test() (in that case, the last command is run with a direction of zero and prev_run_dir is zero).

Mark commands used internally by pathfinding as background commands

---

src/main-sdl2.c

Fixes a post 4.2.5 regression introduced by d6886368017822967efa5911a64b8819502fd7e4 .

SDL2: do not reset all flags when changing a subwindow's purpose

---

src/main-sdl2.c

Resolves https://github.com/angband/angband/issues/5840 .  Resolves https://github.com/angband/angband/issues/5841 .
Adds entries to sdl2init.txt ("window-full-rect-fs" and "subwindow-full-rect-fs") which are not backwards compatible with previous versions.  To go back when sdl2init.txt has "window-fullscreen:true", delete the "window-full-rect:" and "subwindow-full-rect:" lines and then change "window-full-rect-fs" to "window-full-fect" and "subwindow-full-rect-fs" to "subwindow-full-rect".  To go back when sdl2init.txt had "window-fullscreen:false", delete the "window-full-rect-fs" and "subwindow-full-rect-fs" lines.
Does not allow the fullscreen and not fullscreen modes to have different configurations for the font, subwindow visibility, and subwindow transparency.

SDL2: store separate layouts for fullscreen/not fullscreen modes

---

src/borg/borg-messages.c

@agoodman00 , this appears to ~resolve~ reduce instances with the borg getting hung up at a direction prompt after killing a monster with Vampire Strike.

Borg: fix extraction of target's name after casting Vampire Strike

---

src/player-util.c

Allows the borg to correctly record the cause of death when the cheat_live option is on.

Note cause of death before "Die ?" prompt

---

docs/hacking/compiling.rst

The "Source code" links on github's releases page do not include the configure script.  The source code archives, for instance Angband-4.2.5.tar.gz, that were explicitly generated by the release workflow do include the configure script.
The SHARED_INSTALL and READONLY_INSTALL options for CMake require running "make install".

Add some details to the compiling documentation

---

src/borg/borg-log.c

On macOS with an executable compiled with "-fsanitize=address -fsanitize=undefined", caused a crash when a borg-controlled character died. The cause of the crash was "AddressSanitizer: heap-buffer-overflow". The offending address was zero bytes to the right of the 1640 bytes allocated for borg.has.

Borg: fix dump of traits in borg_write_map()

---

src/tests/z-file/path-normalize.c
src/z-file.c

Pair mem_free() rather than free() with mem_alloc.  Explicitly check for device paths rather than treating them as UNC paths.  Use GetFullPathNameA() to get the current directory for a drive.  Tighten check on returned value from second call to GetCurrentDirectory().

Correct path_normalize() for Windows

---

configure.ac

Makefiles and the game do not use those, but some test cases do.  Allows the test cases using set_file_paths() to work on Windows from builds using configure.

configure: change default configpath/libpath/varpath for Windows

---

src/tests/run-tests

That happens on MSYS2 (mingw32 environment) running on Windows with test cases from a configure-based build using --enable-win (so using carriage return + line feed as line endings) while run-tests running within the MSYS2 environment expects Unix-style line endings.

run-tests: tolerate trailing carriage return on summary line from test

---

src/tests/parse/parse.c

Avoids compiler warnings with MSVC.

Fix wchar_t assignment to char in a test case

---

configure.ac

Replace instances of '==' with '=' when used with the test command line utility. '==' is not documented and might lead to portability problems.  Put the logic for the spoiler, statistics, and test front ends before the logic for the Windows front end so the resetting of MAINFILES by the Windows front end has its full intended effect.

Clean up configure a little

---

src/borg/borg-fight-attack.c
src/borg/borg-trait-swap.c

borg_item->brands and borg_item->slays can never be null since both of these are inline array members of the struct in question, so testing whether they are non-null is always true.

borg: fix two warnings

---

.github/workflows/linux.yaml

That way, have one workflow, configure-win in msys2.yaml, running the tests via configure and another, Tests in linux.yaml, running the tests via CMake.

Workflows: use CMake rather than configure for Linux tests

---

src/main.c

Crash reported by vext01 in the comments on #5952 .

Avoid crash with -l option when there are no savefiles to list

---

src/ui-display.c

This will help reading message if multiple events has occurred while a state has changed(ie. 1 key is pressed). Like when a monster attacks multiple times in single turn, Its hard to distinguish what are the recent updates in message subwindow,
Output looks like this
Implementation is kind of hacky, there was another way to have a flag `is_fresh` in message structure, i thought this was little cleaner, let me know if you want me to try that

Display recently updated messages in RED colour in message subwindow

---

src/borg/borg-junk.c

borg shouldn't be taking off un-id'd items generally but, if they are cursed, just take them off

borg: remove cursed semi-id'd items

---

src/effect-handler-attack.c

One instance of that out-of-bounds write was caught by the address sanitizer when a borg player cast a targeted earthquake.

Prevent out-of-bounds write to stack array in earthquake handler

---

src/obj-knowledge.c

I mentioned this change in the forum.  It makes it so both ID and selling an object that is in a strange state go to fully assessed.  I don't know if this is the best way to handle this since I am less familiar with base code than borg code.  
Really, the best solution is to figure out where the object got in the strange state but so far I haven't been able to track that down or even get it to happen again.

set an object to assessed that has all its runes known

---

src/borg/borg-cave-view.h
src/borg/borg-cave.h
src/borg/borg-light.c
src/borg/borg-think-dungeon-util.c
src/borg/borg-update.c

From @backwardsEric 
1. Be willing to ignore what is in the map so the borg does not repeatedly cast stone to mud on a grid that is not seen.
2. Reset the vein list like other digging does.
(1) takes care of the remaining cases I've seen where the borg pauses for extended periods of time repeating "vault excavation" for a grid.

borg: more tweaks for excavating vaults

---

src/borg/borg-light.c
src/borg/borg-store-sell.c

had a borg shooting beam of light over and over at a spot.  This seems to clean that up.
borgs generally hold onto things (weapons/armor) that need ID but if they stack it seems like selling one will help the ID process for non-mages.

borg: light beam seems wrong and selling unID'd items if they stack

---

src/borg/borg-home-notice.c
src/borg/borg-home-power.c
src/borg/borg-inventory.c
src/borg/borg-item-id.c
src/borg/borg-item-id.h
src/borg/borg-power.c
src/borg/borg-store-sell.c
src/borg/borg-trait-swap.c
src/borg/borg-trait.c
src/borg/borg-trait.h
src/borg/borg.txt

A simple change as usual flowers out to a bunch of changes.  Started with  
1) Make the borg better about selling non-ID'd items if he has two of the same thing
ran into 
2) Priests and Paladins get a minor bonus for using blessed items and no penalty.  Make the borg more likely to do that.
3) teleport staffs kept being sold then the borg would be out of them and want some later.  Since old v3x used to have them very common for purchase and 4x doesn't, keep a stack of them in the home
4) the "use low cal food when hi cal isn't around" stuff was making the borg keep low cal even when high cal was available.  Hopefully tweaked this to make it better.
5) the borg wouldn't bother ID'ing things if he was wielding an artifact in that slot (so no bothering to ID an unIDed sword if he was …

Borg: a few changes, selling un ID'd and using unblessed

---

src/borg/borg-update.c

The borg creates a list of "wanks" (monsters and objects) then decides if they are monsters or items.  It was deleting them after using them but when a monster was sitting on an object it only got one of the two.  If it got the object and not the monster it could die from being attacked by something it didn't realize was there. If it was "afraid" when this happened, it would try to walk onto the object then get stuck because there was a monster in the way.
I am not sure this is the best (most efficient and clear) answer or if I should create a second "wank" when there is an object under the monster.. but I think this works.

borg: fix new object/monsters

---

src/borg/borg-fight-defend.c
src/borg/borg.c

Wasn't handling Tremor spell correctly (I didn't have it targeted, it was treated like a small Earthquake) and when a command could be ambiguous I recoded it to error if the direction wasn't queued and handed buffered keys better.

borg: tremor spell and queued response to Direction correction

---

src/cmd-pickup.c

This is an issue in NarSil, https://github.com/NickMcConnell/NarSil/issues/443 .  Vanilla Angband does not currently seem to be affected, but do this for symmetry with how player_pickup_item() tolerates a full inventory when obj is NULL.

Tolerate non-NULL obj argument and full inventory in player_pickup_item()

---

src/ui-input.c

Introduced by d581dcade0d0ece98a72dc1adc7e2bf524f8a475 .  Should resolve case pointed out by agoodman00 in https://github.com/angband/angband/pull/5998 where -more- is not preceded by a space.

Fix regression where -more- prompt overwrites part of message

---

src/generate.c
src/player-quest.c

Currently (without this PR), quest.txt isn't actually used to place particular quest monsters on levels, and most `struct quest` properties (like cur_num, max_num) are unused.
This PR replaces hard-coded placement of QUESTOR monsters with use of quest.txt data. It also now supports quantities of quest monsters (assuming they aren't uniques).
There are a few things worth thinking about:
1. QUESTOR flag is almost useless after this PR. It is only used to print the lore message "You feel an intense desire to kill this monster... ". Perhaps the flag could be eliminated, with this last usage replaced by looking at player->quests?
2. Currently (both with and without this PR), FORCE_DEPTH monster flag is used to prevent questors appearing on the wrong level. A variant generating random quests …

Use quest.txt for placement of quest monster(s), and quest completion logic

---

src/cmd-wizard.c

That's the "air swing" curse in Vanilla.  Regression introduced by this post 4.2.5 change, https://github.com/angband/angband/commit/ad290fbb4b9f738f16d48b4689dd02ffd78aa699 .

Allow debugging commands to add first curse from curse.txt

---

src/ui-player.c

That's for consistency with the general rule that information presented to the player should come from the known version of the object.  In Vanilla, has no effect in normal operation:  damage dice, damage sides, to-hit bonuses, and damage bonuses are automatically known when an item is wielded.

Use known version of equipment for combat information on character sheet

---

src/main.c

Regression introduced by the post 4.2.5 change, 515cbb3e855ccc8b8afdc62ad8b90384911d46a5.

Avoid possible use after free when "-l" option fails

---

src/score.c

Address the crashing part of https://github.com/angband/angband/issues/6022 but not whatever caused openng the locking file to fail.

Avoid crash when locking file for high scores could not be opened

---

src/wiz-stats.c

Used wrong size for allocation (would be under the necessary size if sizeof(struct grid*) < sizeof(struct grid)) and would reallocate when there was still space for one more entry.

Correct reallocation used in the disconnection statistics command.

---

src/main-win.c

See https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170 .  Also, if either is already set, undefine first in case the compiler issues a warning for redefining a macro to a different value.

Windows:  set both WINVER and _WIN32_WINNT to enforce minimum version

---

src/borg/borg-item-analyze.c

I think adding this code means I can remove some checks for special items like Rings of the Dog.  Will do that after testing more.

borg: don't try to sell rings with negative modifiers

---

src/main-sdl2.c

Resolves https://github.com/angband/angband/issues/6043 .

SDL2: size limit for vector font is one less than it should be

---

src/borg/borg-caution.c
src/borg/borg-escape.c
src/borg/borg-flow-stairs.c
src/borg/borg-flow.c
src/borg/borg-init.c
src/borg/borg-think-dungeon-util.c
src/borg/borg-think-dungeon.c
src/borg/borg.h
src/borg/borg.txt

okay with issue https://github.com/angband/angband/issues/6034 I decided to see what would happen if I just turned off him going upstairs and "flowing" to up stairs (targeting them as a destination).  Well, it kinda works but really it should give an error and say "don't do that".  So I decided to split the difference and add an option to allow it for those brave souls who want to see the borg die of not being able to go to town and making stupid decisions based on being able to.  It defaults to false so if a user really wants to, they can make it true and allow "strange" options.

Borg strange opts

---

src/main-sdl2.c

May resolve problem reported by smbhax here, https://angband.live/forums/forum/angband/development/249329-sdl2-front-end-text-has-zero-width-error-with-ttf-set-as-default_font#post249329 .

SDL2: set size appropriately if falling back to a vector DEFAULT_FONT

---

src/main-sdl2.c

Also remember both size and position before switching.  May help diagnose what is reported in https://github.com/angband/angband/issues/6050 .

SDL2: check for error when switching fullscreen mode

---

docs/playing.rst
lib/help/commands.txt
lib/help/r_comm.txt

Not sure if this was intentional or not, but seems non-functional since commit 7497c1a5aa94ffc834c5c6037aa96aaa79262ce4. (v4.0, 2015)
Instead, re-entering a shop can be done by staying still with `,` (`.` via the roguelike keyset; "`CMD_HOLD`") or `5`.
(Apologies if this is incorrect; this is my first time playing Angband)

Remove obsolete "Enter store" command from documentation

---

lib/gamedata/slay.txt
src/cave-square.c

Add missing word in slay.txt.  Use the Javadoc/doxygen lead-in for the comments describing the square_apparent_*() calls.

Fix some comments

---

src/borg/borg-magic.c
src/borg/borg-magic.h
src/borg/borg-think.c
src/borg/borg-trait.c
src/borg/borg.c

this breaks the structure of getting all information from screen scraping but the code to scrape the spell information from the screen is long gone.  Even if i was to put it back I would need to use this sort of cheat code or add a lot of processing to handle the borg menu commands

borg: make sure spell information is retrieved before borg_notice

---

src/borg/borg-reincarnate.c

try to make sure rebuilding the player variable doesn't mess with the cave.  There is some monster activity that still goes on in the background after "Die?" and before "you cheat death".  Since the borg code rebuilds the player between using player_init and outfitting with a new class/race etc, we have to make sure the cave is not messed with.  This means both the cave variable and the player->cave variable.
I am hopefully that this will fix the reincarnation crashes but I have been hopeful before.  I guess I can say that it fixes -this- (https://github.com/angband/angband/issues/6074) reincarnation crash.

borg: reincarnation crash

---

src/borg/borg-flow.c

only seems to happen when digging out vaults.  Other paths here make sure you aren't stepping on walls.

borg: got stuck beating head against perm wall

---

.github/workflows/release.yaml

GitHub's runner for Ubuntu 24.04 is an example of such an environment.  An alternative to this would be to use a theme that is packaged with Sphinx or is available as a package in Ubuntu.

Get release workflow to work with an "externally manage environment"

---

src/main-sdl2.c

Has no effect on the ordering: decomposition of font A's file name now handled the same as font B's.

SDL2: tidy font sorting

---

src/borg/borg-escape.c
src/borg/borg-fight-attack.c
src/borg/borg-messages.c
src/borg/borg-prepared.c
src/borg/borg-prepared.h
src/borg/borg-trait.h
src/borg/borg-update.c

Triggering the reset of recall depth on the unique will keep it from resetting when you are exploring deep but then run out of stuff and now are only prepared for shallow.  
This code should also now better take into account that deep descent is delay action.

borg: change how deep descent works and when recall is reset

---

src/mon-init.c
src/tests/parse/r-info.c

Those are the last three that would access a NULL pointer for a misplaced directive rather than signal a parsing error on a specific line.

monster.txt: return missing record header for misplaced base, glyph, blow

---

src/ui-prefs.c

Resolves https://github.com/angband/angband/issues/6127 .

Avoid coercing a trap's character to a char when parsing preferences

---

src/obj-slays.c

1.  Do not learn monster flags on ranged attacks when the missile does not have a relevant brand or slay.  Fixes a regression introduced by https://github.com/angband/angband/commit/f8f1bc2cf6eff9802cd7d5c5d2d1bf6f8b356cb3 .
2.  If the monster resists a brand, do not learn about the vulnerable flag, if the brand has one, since the damage is not affected by whether the monster has the vulnerable flag in that case.  Has no effect in Vanilla since there are no monsters that both have the resist and vulnerable flag for a brand.
3.  Tolerate brands which do not have a resist flag (not currently relevant in Vanilla:  all brands have a resist flag).
4.  Tolerate slays which are based on a monster base rather than a flag (not currently relevant in Vanilla:  all slays are based on a flag).

Tweak learning of brands and slays

---

src/borg/borg-fight-attack.c
src/borg/borg.c

I tried to make this look at the item the borg was standing on.  The problem is the borg only knows about the top item of stacks so this didn't work.  I decided it was better to make it check for the prompt that says it is looking at "throwable" items and react with a / since the borg only throws items from inventory.

borg: standing on a throwable messes the check.  Make it a reaction

---

src/mon-lore.c

The drops would be written correctly if all were specified by tval; otherwise, the results would not be as expected because the kind field of the first drop was reused for subsequent drops.

Correct lore writing if there is more than one known drop

---

src/Makefile.msys2.sdl2

May be able to revert this at some point in the future depending on the resolution of https://github.com/msys2/MINGW-packages/issues/22439 .

MSYS2 and SDL2: work around inability to statically link libSvtAv1Enc

---

src/borg/borg-item.h
src/borg/borg-trait-swap.c
src/borg/borg-trait.c
src/borg/borg.c

Quiver slots were calculated based on number of ammo/size of a slot but if you have different types they will each take up a slot. I  also noticed that the swap routines were using the "do I have this" rather than the "is this equip able" call so I fixed that while I was in there.

borg: miscalculating quiver slots

---

.github/workflows/release.yaml

That is a temporrary workaround until the build for NDS can be adapted to libnds 2.0.0 changes, see https://devkitpro.org/viewtopic.php?f=13&t=9662&sid=b65090a79d677dfa0d97f11996a2a107#p18269 .

Disable building release for NDS

---

src/main-sdl2.c

Resolves https://github.com/angband/angband/issues/6057 (a regression introduced by d6886368017822967efa5911a64b8819502fd7e4 ).  Simplify resizing:  do not recreate the menu bar.  Match the initial state of the move/size toggles to what's present for the window.

SDL2: reset alpha when toggling off moving/resizing

---

src/main-sdl2.c

Resolves https://github.com/angband/angband/issues/6060 , a regression introduced by 850810f00481b854d10415395ed064d9cea80d60 .

SDL2: when changing fullscreen, resize backing textures if needed

---

src/borg/borg-danger.c
src/borg/borg-fight-attack.c
src/borg/borg-fight-defend.c

There are various things wrong with the teleport other code.  It wasn't calculating the danger correctly and was treating it as a beam not a bolt.  Sometimes it would even error out because it tried to cast without a target.

Borg teleport other fixes

---

src/borg/borg-fight-attack.c
src/borg/borg-flow-take.c
src/borg/borg-formulas.c
src/borg/borg-home-notice.c
src/borg/borg-inventory.c
src/borg/borg-item-analyze.c
src/borg/borg-item-use.c
src/borg/borg-item-wear.c
src/borg/borg-junk.c
src/borg/borg-power.c
src/borg/borg-reincarnate.c
src/borg/borg-store-buy.c
src/borg/borg-store-sell.c
src/borg/borg-trait-swap.c
src/borg/borg-trait.c

sometimes the borg was using items when they weren't "aware" by looking at the sval when it shouldn't.  It also used the "kind" index to tell if it was aware rather than using the aware flag.
also tossed in a fix to do an extra "ESCAPE" when buying things because the "how many" prompt doesn't happen if the borg can only afford one or there is only one in the store making the extra ENTER put up a menu that needs to be ESCAPEd out of.

Borg aware

---

src/main-sdl2.c
src/snd-sdl.c
src/sound-core.c
src/sound.h

The intended use is for diagnosing problems with the SDL2 front end.  The -v suboption, "angband -msdl2 -- -v", will cause details about the SDL2 installation to be pushed through SDL_Log() so those details will be printed on standard error for most platforms (Windows and Android are the known exceptions).  The "SDL Details..." entry in the first menu will dump the details to a simple dialog.  That menu entry for the main window will provide more information (library versions, platform, current video driver, list of connected displays, and audio information).  For other windows, only the details specific to that window are displayed.  For problems that cause the application to exit in init_systems(), only the -v suboption will be useful, and it will only provide limited information in …

SDL2: provide ways to summarize details about the SDL2 installation

---

src/main-cocoa.m

A dead key is a key combination that does not have a Unicode equivalent with the current keyboard mapping.  Potentially allows for more key combinations to be used as keymap triggers:  on macOS 12.7.6 with the US keyboard mapping, Option+E is passed to the game's core as {A}e rather than being ignored.

macOS: allow dead key events to be passed to the game's core

---

lib/gamedata/monster.txt

In current vanilla, hill orc friends were effectively a synonym for Grishnákh.  Resolves https://github.com/angband/angband/issues/6083 .

Convert hill orc friends to cave orcs

---

src/tests/parse/objbase.c

Set error return in teardown_tests() in some cases where it was missed.  Make sure verbose is checked before printing error messages.  Simplify comments about test ordering.  Correct typos in comments and messages.

Clean up unit test for object base parsing

---

src/generate.c

Prevents the conflicting stair posititions that caused https://github.com/angband/angband/issues/6190 .

Persistent levels: correct logic for looking one past missing adjacent level

---

src/gen-chunk.c

For cases where mon_skip is nonzero, that should avoid downstream problems if push_object() moves the mimicked object or a projection reveals the mimic (see project-obj.c).

Adjust object's mimicking_m_idx in chunk_copy()

---

src/effect-handler-general.c
src/player-util.c

Since the player has the choice of recall depth with persistent levels, resetting the recall and maximum depth only artficially limits which levels can be the destination for the recall.  In https://github.com/angband/angband/issues/6190 , very likely was the reason why the player could not recall to a previously visited level.
Also address two corner cases when getting the recall depth with persistent levels:  if the character has not visited the dungeon or is playing with forced descent on, there's no real choice for the destination so do not prompt for it.

Persistent levels:  don't allow reset of recall depth

---

lib/gamedata/object.txt

Suggested by Mitze here, https://angband.live/forums/forum/angband/vanilla/252105-rebalancing-device-difficulty?p=252113#post252113 .  Its ability to remove curses is now mostly between that of a scroll of remove curse and a scroll of *remove curse*.  Increase the cost and power of the staff to reflect the better effect.

Increase the curse removal power of a staff of remove curse

---

src/player-attack.c
src/player-calcs.c
src/ui-player.c

Better matches the description of BLESS_WEAPON.  Resolves https://github.com/angband/angband/issues/6156 .

Apply BLESS_WEAPON to-hit bonus only to melee, not ranged

---

src/borg/borg-escape.c
src/borg/borg.c

If the borg gets an unknown rod of recall and is not at max depth and tries it it will get an unexpected "Set recall depth to current depth? [y/n]" prompt.  Now it will just give a 'n' if it gets that prompt when it wasn't expecting it.  I should check for other prompts that might happen from unknown objects.
While in there I redid the check for if it should reset the recall depth to be clearer (should work the same).

borg: unexpected 'set recall depth' prompt

---

src/borg/borg-light.c

this is actually more complicated a fix than is needed since the borg grabs the last of an item with the routine it is using and that is always non-everburning but I thought it was clearer written out.

borg: don't refuel from everburning

---

src/borg/borg-store-sell.c

additionally I put in the selling of ammo to the general store and allowed the borg to dump stuff at the black market if he is configured not to make any money on sales.
I think this issue only came up when the Alchemist (correct store for potions and scrolls) was full.

borg: shouldn't sell potions and scrolls to the wrong store

---

src/borg/borg-item-analyze.c

sets any items with a flag that is negative (power < 0) to "cursed".  This way the borg won't try to sell them.  I may need to adjust this later in case the borg is filtering out things that have a small negative and a large positive. I don't think that will happen since the "cursed" flag is mostly used in sales as opposed to the "uncursable" flag which is used when removing curses.

borg: set items with negative flags to cursed

---

src/gen-chunk.c
src/mon-make.c

Resolves a regression introduced by 5540d48fb9608dbb26cf0adff2b91cbc7f44851e which made delete_monster_idx() less similar to wipe_mon_list() and plugs a memory leak in FAangband when a skipped player ghost carries objects.  To avoid the opportunity for use after free or double frees, have chunk_copy() reset the carried or mimicked objects to NULL for a monster in the source chunk once those objects have been transferred to the destination.

Have delete_monster_idx() always call object_delete() on a carried object

---

src/main-x11.c

Seen with clang 16.0.6 on OpenBSD.

Avoid set but unused warnings

---

src/borg/borg-fight-attack.c
src/borg/borg-io.c
src/borg/borg-io.h
src/borg/borg-light.c
src/borg/borg-magic.c

this fixes the issue.  I don't love it because I find it less clear than having the "invalid UTF" right in the comment, which is why I just let it sit this way but it is valuable to not have the warnings.  Probably more valuable than the comment being 100% obvious.

Clang warning invalid utf8 in comment

---

src/borg/borg-messages-react.c
src/borg/borg-messages-react.h
src/borg/borg.c

One of the rare effects of WONDER (either activation or wand) is Banishment which gives an additional prompt.  I think it is the only effect that needs more prompting than the initial aim and shoot. I made the borg watch for "Choose a monster race (by symbol) to banish" and just escape out to avoid the keypress queue getting munged.
I also moved around the "messages the borg needs to react to immediately" code so it wasn't cluttering up the borg.c code.

borg: react when banishment is the wonder effect

---

src/obj-randart.c
src/ui-knowledge.c
src/ui-prefs.c
src/wiz-spoil.c

Seen with gcc 12.2.0 on a 32-bit versions of Debian 12.  Three (one in writing the randart file and two in writing monster spoilers) came from assuming that a wchar_t could be trivially converted to a char.

Avoid warnings for mismatched format arguments with 32-bit compilation

---

lib/gamedata/class.txt
src/effect-handler-attack.c

Do not require a known grid.  Target the player if target is a direction or is not in the line of sight.  Resolves https://github.com/angband/angband/issues/6013 .

Change target handling for Lightning Strike

---

src/borg/borg-fight-attack.c

make sure with lightning strike the borg has projection to the target.  A failed guess hurts the caster so don't guess that blank squares are floor.

borg: don't let lightning strike guess floor

---

src/z-file.c

Happens when PRIVATE_USER_PATH with its default value, "~/.angband", is used.  Resolves https://github.com/angband/angband/issues/6237 .

Avoid extraneous path separator in the user and archive directories

---

src/savefile.c
src/tests/unit-test-data.h
src/z-dice.c

The text of such warnings begins with "warning: initializer-string for array of 'unsigned char' truncates NUL terminator but destination lacks 'nonstring' attribute".  Those warnings are controlled by the -Wunterminated-string-initialization option.

Avoid warnings on msys2 about truncation when initializing array from string

---

src/mon-util.c
src/project-mon.c

Noted when trying to diagnose https://github.com/NickMcConnell/FAangband/issues/426 .  Specifically the changes are:
1) A non-player projection can no longer kill an arena monster.  Has an impact only if there are monster spells that can affect the caster.
2) Shapechanged monster reverts to original shape on death for a non-player hit or non-player projection.  The death message due to a player projection is now set after reverting the shape rather than before.  Might impact https://github.com/angband/angband/issues/4245 , but only so far as the misleading death message prior to this change confused the player.  Cases where there's mulitple history entries for killing the unique would not be fixed.

Better match death logic for projections or non-player hits to mon_take_hit()

---

src/ui-game.c

That is necessary for correct operation with setgid installations.

Use extra privileges for existence check in savefile_name_already_used()

---

docs/hacking/borg.rst
docs/index.rst

From issue: https://github.com/angband/angband/issues/6253
Creates the initial Borg developer documentation.
This is just the start of the documentation that we can build upon. I have additional thoughts and questions that I'll post in the issue linked above.
Screenshots of rendered html:

Add Initial Borg Developer Documentation

---

docs/hacking/borg.rst
docs/playing.rst
src/borg/borg.c

From issue https://github.com/angband/angband/issues/6253#issuecomment-2989128387
Documentation `docs/hacking/borg.rst`:
- Add context about borg name origin and primary use case
- Replace outdated `borgread.txt` reference with step-by-step usage instructions
- Add comprehensive command interface documentation with all main, flag, and cheat commands
- Organize commands alphabetically for easier reference
Command Interface `src/borg/borg.c`:
- Add missing `C` (List nasties) and `;` (Display glyphs) commands to in-game help
- Improve help text clarity
Playing Guide `docs/playing.rst`:
- Update `^z` key documentation from "unused" to "Borg commands (if available)"

Borg docs name/history/commands + command interface completeness

---

src/Makefile
src/tests/Makefile

Prior version was leaving .gcno and .gcda files in src/tests and its subdirectories.  At least with gcov 12.2.0 on Debian 12, there were also "borg#*.c.gcov" files left in src.

Clean more with "make clean-coverage"

---

docs/hacking/borg.rst
src/borg/borg.txt

From: https://github.com/angband/angband/issues/6253
Improves the Borg documentation by:
- Adding a new section on how to adjust the Borg's speed, a common setup step.
- Introducing the `dynamic formula` system and how to enable it.
- Adding a comment to `borg.txt` that directs users to the documentation for a high-level overview.

Borg docs misc improvements

---

src/borg/borg.txt

From: https://github.com/angband/angband/issues/6253
- Modernize formatting by removing double spaces after periods.
- Various spelling and grammar improvements.
- Depersonalize and delete reference to DrAngband.
- Delete the outdated recommendation to add more terminal windows to slow down the borg. Multi window recommendation is now in official doc.
- Delete commented out lines from formula section.

Modernize and clean up borg.txt

---

src/borg/borg.txt

From: https://github.com/angband/angband/issues/6253
Reorganized `borg.txt` to improve readability, while maintaining all existing content. This makes it easier to understand and brings it more in line with other documentation `.txt` files in the repo.
- Consistent Section Headers: Replaced inconsistent comment styles with a standard `### Header ###` format for all sections.
- Standardized Spacing: Enforced consistent blank lines between comment blocks and their corresponding configuration values, and between distinct sections.
- Logical Reorganization: Moved the `borg_uses_dynamic_calcs` setting to be immediately before the `[BEGIN FORMULA SECTION]` to group related configurations.

borg.txt reorganize existing content

---

src/player-calcs.c

Resolves: https://github.com/angband/angband/issues/6226
Changes the misleading "armor encumbers your movement" message to accurately reflect that heavy armor reduces maximum SP for spellcasters, not movement speed.
Very open to the specific wording.

cumber_armor message clarity

---

.gitignore
src/doc/doxygen-mainpage.md
src/doc/doxygen.conf

This PR re-enables Doxygen documentation generation, addressing this comment from [issue #5206](https://github.com/angband/angband/issues/5206#issuecomment-999990671).
> getting the doxygen build running and up somewhere would probably be a good idea, although it was only ever partially done
This is a simple starting point to get Doxygen docs building and ready for publication.
- Updates `src/doc/doxygen.conf`
- Adds a stub `doxygen-mainpage.md` for the Doxygen homepage
- Adds `src/doc/_doxygen/` to `.gitignore` to avoid committing built files
From the project root, run `doxygen src/doc/doxygen.conf` to build documentation into a gitignored directory.
- If this looks good, we can manually copy the built files to the `gh-pages` branch for publication at …

Re-enable Doxygen: config updates, mainpage, and output dir ignore

---

configure.ac

Per https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Prerequisite-Macros.html#Prerequisite-Macros , if/else and case statements that are not within AC_DEFUN() and use macros should be rewritten with AS_IF() or AS_CASE().  Do so for all if/else and case statements in configure.ac, regardless of whether they invoke a macro, for simplicity.

configure: replace if/else and case with AS_IF() and AS_CASE()

---

src/player-path.c
src/player-util.c
src/project-feat.c
src/project.c
src/store.c
src/ui-command.c
src/ui-context.c
src/ui-display.c
src/ui-help.c
src/ui-input.c
src/ui-knowledge.c
src/ui-map.c
src/ui-mon-lore.c
src/ui-options.c
src/ui-player.c
src/ui-score.c
src/ui-store.c
src/ui-target.c
src/ui-term.c
src/ui-term.h
src/wiz-debug.c
src/wiz-spoil.c
src/z-form.c
src/z-rand.c
src/z-textblock.c

Follow up from https://github.com/angband/angband/pull/6283
Removes remaining `Hack --` comments in `src` directory.
Leaves in `Mega-Hack` comments.
Replaced comment to say `HACK` for hacky solutions.

Remove 'Hack --' src comments part 2

---

src/sdl2/pui-dlg.c

I'm not sure at all what is up with the warning for line 1204 of sdl2/pui-dlg.c: "argument 'if' of command @param is not found in the argument list of sdlpui_open_dialog".

Resolve most of the doxygen warnings for the SDL2 code

---

src/borg/borg-fight-attack.c

make sure 
1) the player has 50hp left after casting crush (previously was 5hp)
2) the player has twice as many hp as the "new danger" after casting (previously was equal to danger level).
The borg I am testing with still cast crush a bunch but this should help him from killing himself with it.

borg: reduce overuse of Crush

---

src/borg/borg-init.c
src/borg/borg-init.h
src/borg/borg.c
src/borg/borg.h
src/borg/borg.txt

and there is now a borg.txt setting to allow it to be restored when the borg stops.

borg: turn off ignore settings while the borg is running

---

src/ui-curse.c
src/ui-effect.c
src/ui-input.c
src/ui-menu.c
src/ui-menu.h
src/ui-object.c
src/ui-spell.c
src/ui-target.c
src/ui-target.h

Only recognize a keymap trigger if its action is one walk or run command.  Also, depending on the context, allow a keymap trigger whose first key in the action is ESCAPE to break out of the selection process.  The latter resolves https://github.com/angband/angband/issues/6297 .  Such a keymap trigger can also break out of item, spell, curse, or effect selection.  They do not affect retrieving the input when the player is prompted for a string, quantity, confirmation, or single character.  Menus used in the knowledge or preferences menu are not affected unless they use the item/spell/curse/effect input methods.

Rework how keymaps are handled when extracting a direction

---

docs/hacking/debug.rst
src/cmd-wizard.c
src/wiz-stats.c
src/wizard.h

The number of simulations is now the number of simulations to perform at each depth.  The results written to the message window, when looping over multiple depths, are the sum of the histograms at each depth.  The histograms at each depth and the sum over depth of those histgrams are written to the file.  Shorten the messages written to the message window:  what was "Type: Animals, Number: 310." is now "Type Animals: 310.".

Allow the pit statistics to loop over depth and write results to a file

---

docs/option.rst
docs/playing.rst
lib/help/commands.txt
lib/help/r_comm.txt
src/cmd-cave.c
src/list-options.h
src/ui-context.c

That option, autoexplore_commands, is off by default.  When that option is on, modify the player's context menu so the autoexplore commands are available.  Resolves https://github.com/angband/angband/issues/6324 .  Some discussion is here, https://angband.live/forums/forum/angband/development/252252-suggestion-re-navigating-to-the-nearest-staircase .

Hide autoexplore commands behind option

---

docs/hacking/compiling.rst

Relabel 'Documentation' as 'User Documentation' and include in it how to build the user manual when using configure or CMake.  Add a section, 'Developer Documentation' and specify how to run doxygen there.

docs: rework the section on how to compile the documentation

---

src/doc/doxygen.conf

The former was the intent of 2e5285aedd5eb3aa5dc6732865b685716d03fa32 .  Resolves https://github.com/angband/angband/issues/6341 (by hiding the problem; that issue could come back if doxygen is told to process the test cases).  Reduces the erroneous references links in https://github.com/angband/angband/issues/6340 (the specific case mentioned there no longer occurs; need more auditing of doxygen's output to know if other bogus references links remain).

doxygen: exclude test cases and external include files for Windows

---

src/z-queue.c

Callers were not handling NULLs returned by q_new() or qp_new() so quit in cases where the size overflows.  4d76112f25e5287b9c2ebfdaef80c72d13928900 mixed calls to malloc(), mem_alloc(), free(), and mem_free() for queues.  Use mem_alloc() and mem_free() throughout to fix that regression.

Prevent NULL returns from queue functions; remore mix of allocation functions
